Bug 1716955: Initial implementation of the rate metric
mozilla/glean.js pull request #1006
Opened 2021-12-01 23:12 UTC by ChinYing-Li

### Pull Request checklist ###

- [ ] **Quality**: Make sure this PR builds and runs cleanly.
  - Inside the `glean/` folder, run:
    - `npm run test` Runs _all_ tests
    - `npm run lint` Runs _all_ linters
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes a changelog entry to `CHANGELOG.md` or an explanation of why it does not need one
- [ ] **Documentation**: This PR includes documentation changes, an explanation of why it does not need that or a follow-up bug has been filed to do that work
  - Documentation should be added to [The Glean Book](https://mozilla.github.io/glean/book/index.html) when making changes to Glean's user facing API
    - When changes to the Glean Book are necessary, link to the corresponding PR on the [`mozilla/glean`](https://github.com/mozilla/glean) repository
  - Documentation should be added to [the Glean.js developer documentation](https://github.com/mozilla/glean.js/tree/main/docs) when making internal code changes

2021-12-01 23:13 UTC, ChinYing-Li commented
Hello, 
I just realized that in the glean library (https://github.com/mozilla/glean), there's no unit test for the rate metric. Is this by purpose?

2021-12-02 12:18 UTC, Dexterp37 commented
> Hello, I just realized that in the glean library (https://github.com/mozilla/glean), there's no unit test for the rate metric. Is this by purpose?

There's a [smoke test here](https://github.com/mozilla/glean/blob/4e56b157196350a4a2b605423dbfd1ce7c42d160/glean-core/rlb/src/private/rate.rs#L74) and a [schema test here](https://github.com/mozilla/glean/blob/1a8ad8003c220281e2f1cddc3b6aeabe7875cd35/glean-core/rlb/tests/schema.rs#L101). I believe that given the time pressure, no other test was added.

2021-12-02 14:26 UTC, ChinYing-Li commented
The PR is now ready for review; any suggestion is appreciated!

2021-12-02 22:16 UTC, chutten reviewed
This is looking good to me so far. I'll bring in @brizental to make sure I'm not allowing strange patterns in just because I'm unfamiliar with how metric types are implemented in the Glean JS SDK.

2021-12-02 22:16 UTC, chutten commented on glean/src/core/metrics/types/rate.ts
> +   * Gets the currently stored value as a string.
It doesn't appear to return a string

2021-12-02 22:16 UTC, chutten commented on glean/src/core/metrics/types/rate.ts
> +   * this function will return the unencoded URL for convenience.
I'm not sure this comment is correct for this type.

2021-12-02 22:16 UTC, chutten commented on glean/tests/unit/core/metrics/rate.spec.ts
> +    const metric = new RateMetricType({
You add a test rate metric in the metrics.yaml, but here you manually create one. I don't understand why you don't use the rate metric from the metrics.yaml and save yourself the boilerplate.

2021-12-06 08:59 UTC, brizental requested changes
Hey @ChinYing-Li this is looking really great. I like the way you implemented the metric, very clean.

I left some comments. Implementation looks really good. I would like to have more tests as well. 

Once we are done with these changes we will also need to update [the docs](https://mozilla.github.io/glean/book/reference/metrics/rate.html). Feel free to simply file a follow up for that if you don't want to work on it.

2021-12-06 08:59 UTC, brizental commented on glean/src/core/metrics/types/rate.ts
> +  // The denominator
nit: These two comments are redundant.

2021-12-06 08:59 UTC, brizental commented on glean/src/core/metrics/types/rate.ts
> +  add_to_numerator(amount: number): void {
nit: 
```suggestion
  addToNumerator(amount: number): void {
```

2021-12-06 08:59 UTC, brizental commented on glean/src/core/metrics/types/rate.ts
> +  add_to_denominator(amount: number): void {
nit:
```suggestion
  addToDenominator(amount: number): void {
```

2021-12-06 08:59 UTC, brizental commented on glean/tests/unit/core/metrics/rate.spec.ts
> +    const metric = new RateMetricType({
That metrics.yaml is only used by the integration tests. On the unit tests we are required to instantiate the metrics, so this is correct :)

2021-12-06 08:59 UTC, brizental commented on glean/tests/unit/core/metrics/rate.spec.ts
> +});
nit:
```suggestion
});

```

2021-12-06 08:59 UTC, brizental commented on glean/tests/unit/core/metrics/rate.spec.ts
> +  it("smoke test for rate metric", async function() {
Hm, I understand this is the only test we have for this metrics on glean-core. However, since we are not time constrained here I would prefer to have a more comprehensive test suite.

I am fine if you'd prefer to make that a follow-up PR :) And feel free to ask any questions with regards to the tests you want to add. 

You can also base yourself off of other metrics suites, such as the [BooleanMetric](https://github.com/mozilla/glean.js/blob/main/glean/tests/unit/core/metrics/boolean.spec.ts). At least the four tests you see there we have for all metric types, so this is a good baseline. Since this is a more complex metric type, there might be other tests that make sense here as well.

2021-12-06 08:59 UTC, brizental commented on glean/package-lock.json
> -    "@typescript-eslint/scope-manager": {
Hm, let's please drop these changes from this PR.

2021-12-06 09:00 UTC, brizental commented on glean/tests/unit/core/metrics/rate.spec.ts
> +  it("smoke test for rate metric", async function() {
I just remembered this metric may also record errors, so we should cover that in the test suite as well. See example in the [CounterMetric](https://github.com/mozilla/glean.js/blob/main/glean/tests/unit/core/metrics/counter.spec.ts#L82-L101) test suite.

2021-12-06 12:09 UTC, ChinYing-Li commented on glean/tests/unit/core/metrics/rate.spec.ts
> +  it("smoke test for rate metric", async function() {
Just added a few test cases, taking reference from the Counter Metric. Let me know if you think there's any cases I missed.

2021-12-06 12:50 UTC, brizental commented on glean/package-lock.json
> -    "@typescript-eslint/scope-manager": {
Looks like the changes are still here, so I am unresolving. Perhaps rebasing the PR will make this change unnecessary.

2021-12-06 13:17 UTC, brizental requested changes
Thanks for adding the tests! Not much is missing, left some inline commments and through the tests found a bug in the implementation. Easy to fix though.

2021-12-06 13:17 UTC, brizental commented on glean/tests/unit/core/metrics/rate.spec.ts
> +    assert.deepStrictEqual(await metric.testGetValue("aPing"), {numerator: 0, denominator: 0});
Hm, this is not the behaviour I would expect. If I try to set incorrect values, `testGetValue` should return `undefined`. I think this is problem on the implementation, good thing we are adding tests :D 

Indeed, [here](https://github.com/mozilla/glean/blob/main/glean-core/src/metrics/rate.rs#L117) you should return early after recording the error. [Like it is done in glean-core](https://github.com/mozilla/glean/blob/main/glean-core/src/metrics/rate.rs#L59-L68). Same goes for the `addToDenominator` function.

2021-12-06 13:17 UTC, brizental commented on glean/tests/unit/core/metrics/rate.spec.ts
> +    assert.deepStrictEqual(await metric.testGetValue("aPing"), {numerator: 0, denominator: 0});
Also, let's add checks for error recordings here.

2021-12-06 13:17 UTC, brizental commented on glean/src/core/metrics/types/rate.ts
> +   * Logs an error if the `amount` is negative.
nit:
```suggestion
   * Records an `InvalidValue` an error if the `amount` is negative.
```

2021-12-06 13:17 UTC, brizental commented on glean/tests/unit/core/metrics/rate.spec.ts
> +  });
Let's please use both `addToDenominator` and `addToNumerator` APIs in all there three first test cases.

2021-12-06 13:17 UTC, brizental commented on glean/tests/unit/core/metrics/rate.spec.ts
> +    assert.deepStrictEqual(await metric.testGetValue("threePing"), expectedValue);
Let's add two more transformations here. To check that transforming the numerator and denominator after they were set once, also works as expected.

2021-12-06 13:17 UTC, brizental commented on glean/tests/unit/core/metrics/rate.spec.ts
> +});
Unresolving because the new line at the end is still missing :)

2021-12-06 13:17 UTC, brizental commented on glean/src/core/metrics/types/rate.ts
> +   * Logs an error if the `amount` is negative.
```suggestion
   * Records an `InvalidValue` error if the `amount` is negative.
```

2021-12-06 13:18 UTC, ChinYing-Li commented on glean/package-lock.json
> -    "@typescript-eslint/scope-manager": {
Yes rebasing the PR eliminates the diff.

2021-12-07 09:03 UTC, ChinYing-Li commented on glean/tests/unit/core/metrics/rate.spec.ts
> +    assert.deepStrictEqual(await metric.testGetValue("aPing"), {numerator: 0, denominator: 0});
The [smoke test in glean-core](https://github.com/mozilla/glean/blob/4e56b157196350a4a2b605423dbfd1ce7c42d160/glean-core/rlb/src/private/rate.rs#L74) actually expects "setting negative value" to be no-op. Please let me know if you'd still like to have "invalidate the metric if invalid value is passed" as the expected behavior.

2021-12-07 09:10 UTC, brizental commented on glean/tests/unit/core/metrics/rate.spec.ts
> +    assert.deepStrictEqual(await metric.testGetValue("aPing"), {numerator: 0, denominator: 0});
Indeed, but it's not returning `undefined` (or `None` in their case), [because the metric was set to `0` initially](https://github.com/mozilla/glean/blob/4e56b157196350a4a2b605423dbfd1ce7c42d160/glean-core/rlb/src/private/rate.rs#L92-L93).

2021-12-07 10:00 UTC, ChinYing-Li commented on glean/tests/unit/core/metrics/rate.spec.ts
> +    assert.deepStrictEqual(await metric.testGetValue("aPing"), {numerator: 0, denominator: 0});
The test case here also set to 0 initially; did I miss anything?

2021-12-07 10:47 UTC, brizental commented on glean/tests/unit/core/metrics/rate.spec.ts
> +    assert.deepStrictEqual(await metric.testGetValue("aPing"), {numerator: 0, denominator: 0});
Woof, I am sorry _I_ was the one missing something. I missed the setting to zero.

Either way, it's still important to return early. I would even remove the lines where we set to zero, just to be sure we catch any problem with this behaviour in the future.

2021-12-09 15:12 UTC, brizental approved these changes
Some final nits, otherwise, looks god!

Thanks so much for the work here @ChinYing-Li 🎉

2021-12-09 15:12 UTC, brizental commented on glean/src/core/metrics/types/rate.ts
> +
nit: Extra blank line.
```suggestion
```

2021-12-09 15:12 UTC, brizental commented on glean/src/core/metrics/types/rate.ts
> +          `Added negative value ${amount} to numerator.`
```suggestion
          `Added negative value ${amount} to denominator.`
```

2021-12-09 15:12 UTC, brizental commented on glean/src/core/metrics/types/rate.ts
> +   * this function will return the RateInternalPresentation for convenience.
```suggestion
   * This function will return the RateInternalPresentation for convenience.
```

2021-12-09 15:56 UTC, brizental commented
Oh, yeah. Also, please add a changelog entry for this.

2021-12-09 23:11 UTC, ChinYing-Li commented on glean/src/core/metrics/types/rate.ts
> +          `Added negative value ${amount} to numerator.`
Oof, so sorry for the stupid mistake! Thank you for pointing this out.

2021-12-10 10:12 UTC, brizental commented on glean/src/core/metrics/types/rate.ts
> +          `Added negative value ${amount} to numerator.`
Nothing to be sorry about. Happens to all of us :) That's why we have reviews!

2021-12-10 10:13 UTC, brizental commented on CHANGELOG.md
> +* [#1006](https://github.com/mozilla/glean.js/pull/1006): Implement the rate metric.
Actually this should go on the `Unreleased changes` section :)

2021-12-13 13:58 UTC, merged