Bug 1699392 - Enable running the glean command offline
mozilla/glean.js pull request #1178
Opened 2022-02-10 16:58 UTC by brizental

...And with as many arguments as the users wants to.

### Pull Request checklist ###

- [ ] **Quality**: Make sure this PR builds and runs cleanly.
  - Inside the `glean/` folder, run:
    - `npm run test` Runs _all_ tests
    - `npm run lint` Runs _all_ linters
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes a changelog entry to `CHANGELOG.md` or an explanation of why it does not need one
- [ ] **Documentation**: This PR includes documentation changes, an explanation of why it does not need that or a follow-up bug has been filed to do that work
  - Documentation should be added to [The Glean Book](https://mozilla.github.io/glean/book/index.html) when making changes to Glean's user facing API
    - When changes to the Glean Book are necessary, link to the corresponding PR on the [`mozilla/glean`](https://github.com/mozilla/glean) repository
  - Documentation should be added to [the Glean.js developer documentation](https://github.com/mozilla/glean.js/tree/main/docs) when making internal code changes

2022-02-11 09:59 UTC, badboy requested changes

2022-02-11 09:59 UTC, badboy commented on glean/package.json
> +    "sqlite3": "^4.2.0",
What's the reason for the version change here?

2022-02-11 09:59 UTC, badboy commented on glean/src/cli.ts
> +  const isOnlineArg = await isOnline() ? "online" : "offline";
This will contact _several_ external services, including Google, Apple and icanhazip.com.
I'm not really convinced our tool should do that _by default_ _every time_

Maybe this should be just a flag by the user (or env variable)?
Really all that flag really does it not trying to install Glean Python.
It won't even use the network if it can find a installed Glean Python (of the right version) first.

2022-02-11 09:59 UTC, badboy commented on glean/src/cli.ts
> +    sys.exit(1)
Wrong de-indent?
This should only exit in case `offline` is requested.
If it's online, it will try to install Glean and if that succeeds, it should continue.

2022-02-11 10:12 UTC, brizental commented on glean/package.json
> +    "sqlite3": "^4.2.0",
`npm audit` was complaining about it, see [4b03566](https://github.com/mozilla/glean.js/pull/1178/commits/4b0356610790dd120128158c3882f8a8446a85f9)

2022-02-11 10:13 UTC, brizental commented on glean/src/cli.ts
> +  const isOnlineArg = await isOnline() ? "online" : "offline";
yeap you are right, env var is better solution. i really should have looked at that before adding the dependency, nice catch!!!

2022-02-16 14:57 UTC, badboy approved these changes

2022-02-16 18:10 UTC, merged