1699674 - Fix support for ES6 importing
mozilla/glean.js pull request #123
Opened 2021-03-19 14:10 UTC by brizental

2021-03-19 14:15 UTC, Dexterp37 approved these changes
Thanks for the great work.

2021-03-19 14:16 UTC, Dexterp37 commented on glean/package.json
> +    "build:webext:lib:esm": "tsc -p ./tsconfig/webext/esm.json && echo '{\"type\": \"module\"}'> dist/webext/esm/package.json",
Please make sure to add a changelog entry fo rthis.

2021-03-19 17:19 UTC, brizental commented on glean/package.json
> +    "build:webext:lib:esm": "tsc -p ./tsconfig/webext/esm.json && echo '{\"type\": \"module\"}'> dist/webext/esm/package.json",
Yeap, will do on Monday. Until then, would you kindly give this another review? There were a few changes to get tests and webpack to work again :D

2021-03-22 08:02 UTC, Dexterp37 requested changes
Let's add a changelog entry :)

2021-03-22 08:02 UTC, Dexterp37 commented on glean/tests/core/metrics/labeled.spec.ts
> -import { JSONObject } from "../../../dist/webext/types/core/utils";
Great catch!

2021-03-22 08:02 UTC, Dexterp37 commented on glean/package.json
> +    "build:webext:lib:cjs": "tsc -p ./tsconfig/webext/cjs.json && echo '{\"type\": \"commonjs\"}'> dist/webext/esm/package.json",
Mh, given the configuration option, I would have expected this to happen automatically. Do we need to change [this](https://github.com/mozilla/glean.js/blob/6489e685ddcede776041dbea9af695b1d52c7a86/glean/tsconfig/webext/esm.json#L10) to commonjs?

2021-03-22 08:32 UTC, brizental commented on glean/package.json
> +    "build:webext:lib:cjs": "tsc -p ./tsconfig/webext/cjs.json && echo '{\"type\": \"commonjs\"}'> dist/webext/esm/package.json",
Nope, the config you linked to is the ESM config, that needs `type: module`. Note that [before](https://github.com/mozilla/glean.js/pull/123/commits/93e9f37aae3e6e6739593d8e0ae0eb17e49ba33b) I had added the `type: module` to the ESM builds. For tests to work it is easier to leave the `type: module` declaration in the main package.json and override it with a `type: commonjs` in the commonjs config instead. Does this make sense?

2021-03-22 08:33 UTC, brizental commented on glean/package.json
> +    "build:webext:lib:cjs": "tsc -p ./tsconfig/webext/cjs.json && echo '{\"type\": \"commonjs\"}'> dist/webext/esm/package.json",
> given the configuration option, I would have expected this to happen automatically

How so?

2021-03-22 08:34 UTC, Dexterp37 commented on glean/package.json
> +    "build:webext:lib:cjs": "tsc -p ./tsconfig/webext/cjs.json && echo '{\"type\": \"commonjs\"}'> dist/webext/esm/package.json",
NVM, you clarified it above, thanks.

2021-03-22 09:02 UTC, Dexterp37 approved these changes
r+wc

2021-03-22 09:02 UTC, Dexterp37 commented on CHANGELOG.md
> +  * Include `.js.` extensions in all local import statements.
```suggestion
  * Include `.js` extensions in all local import statements.
```

like this?

2021-03-22 09:06 UTC, merged