Bug 1761485 - Expose ErrorType through its own entry point.
mozilla/glean.js pull request #1318
Opened 2022-04-19 22:15 UTC by tawahpeggy

### Pull Request checklist ###

- [ ] **Quality**: Make sure this PR builds and runs cleanly.
  - Inside the `glean/` folder, run:
    - `npm run test` Runs _all_ tests
    - `npm run lint` Runs _all_ linters
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes a changelog entry to `CHANGELOG.md` or an explanation of why it does not need one
- [ ] **Documentation**: This PR includes documentation changes, an explanation of why it does not need that or a follow-up bug has been filed to do that work
  - Documentation should be added to [The Glean Book](https://mozilla.github.io/glean/book/index.html) when making changes to Glean's user facing API
    - When changes to the Glean Book are necessary, link to the corresponding PR on the [`mozilla/glean`](https://github.com/mozilla/glean) repository
  - Documentation should be added to [the Glean.js developer documentation](https://github.com/mozilla/glean.js/tree/main/docs) when making internal code changes

2022-04-20 09:38 UTC, Dexterp37 requested changes
Hi @tawahpeggy and thank you for your contribution!

This needs a few changes before we can merge it: because you're using an old version of npm, the lock files have been rewritten in an old format, making CI fail.

In addition to the above, would you kindly add an entry for this change at the top of the `CHANGELOG.md` file?

2022-04-20 09:38 UTC, Dexterp37 commented on glean/package-lock.json
> -  "packages": {
Looks like you're using an outdated `npm` and the lockfile was rewritten with an older version. Would you kindly update your local npm and drop this change?

2022-04-20 09:38 UTC, Dexterp37 commented on glean/package.json
> +    "./error": "./dist/core/error/error_type.js",
Would you kindly make this the first entry in this object? (i.e. move this before `.package.json`)

2022-04-20 09:38 UTC, Dexterp37 commented on glean/tests/unit/platform/utils/webext/sample/package-lock.json
> +  "lockfileVersion": 1,
Same consideration as the other lockfile. Would you kindly drop this change?

2022-04-21 09:16 UTC, tawahpeggy commented
Thank you very much for your review, will update the PR ASAP

2022-04-21 10:05 UTC, Dexterp37 requested changes

2022-04-21 10:05 UTC, Dexterp37 commented on glean/package.json
> +    "@typescript-eslint/eslint-plugin": "^5.20.0",
@tawahpeggy while it's eventually desirable, we should not be updating the versions of the dependencies as part of this PR if possible. Thanks!

2022-04-21 10:05 UTC, Dexterp37 commented on CHANGELOG.md
> +* [#1318](https://github.com/mozilla/glean.js/pull/1318):Expose ErrorType through its own entry point.
```suggestion
* [#1318](https://github.com/mozilla/glean.js/pull/1318): Expose `ErrorType` through its own entry point.
```

2022-04-21 11:14 UTC, tawahpeggy commented
Hello @Dexterp37, please do you have an idea why some tests fail?

2022-04-21 11:42 UTC, Dexterp37 commented
> Hello @Dexterp37, please do you have an idea why some tests fail?

It doesn't seem to be able to import `ErrorType`. I believe the imports need to be adjusted :)

```
TSError: ⨯ Unable to compile TypeScript:
tests/unit/index.test.ts:6:10 - error TS2614: Module '"@mozilla/glean/webext"' has no exported member 'ErrorType'. Did you mean to use 'import ErrorType from "@mozilla/glean/webext"' instead?

6 import { ErrorType } from "@mozilla/glean/webext";
           ~~~~~~~~~

    at createTSError (/home/circleci/project/samples/browser/webext/node_modules/ts-node/src/index.ts:820:12)
    at reportTSError (/home/circleci/project/samples/browser/webext/node_modules/ts-node/src/index.ts:824:19)
    at getOutput (/home/circleci/project/samples/browser/webext/node_modules/ts-node/src/index.ts:1014:36)
    at Object.compile (/home/circleci/project/samples/browser/webext/node_modules/ts-node/src/index.ts:1322:43)
    at transformSource (/home/circleci/project/samples/browser/webext/node_modules/ts-node/src/esm.ts:380:37)
    at load (/home/circleci/project/samples/browser/webext/node_modules/ts-node/src/esm.ts:280:51)
    at async ESMLoader.load (node:internal/modules/esm/loader:359:20)
    at async ESMLoader.moduleProvider (node:internal/modules/esm/loader:280:47)
    at async link (node:internal/modules/esm/module_job:70:21)

Exited with code exit status 1

CircleCI received exit code 1

```

2022-04-21 11:43 UTC, Dexterp37 commented on glean/package-lock.json
> -  "packages": {
@tawahpeggy this was fully removed instead of restored, would you kindly restore the file?

2022-04-21 13:49 UTC, tawahpeggy commented
> > Hello @Dexterp37, please do you have an idea why some tests fail?
> 
> It doesn't seem to be able to import `ErrorType`. I believe the imports need to be adjusted :)
> 
> ```
> TSError: ⨯ Unable to compile TypeScript:
> tests/unit/index.test.ts:6:10 - error TS2614: Module '"@mozilla/glean/webext"' has no exported member 'ErrorType'. Did you mean to use 'import ErrorType from "@mozilla/glean/webext"' instead?
> 
> 6 import { ErrorType } from "@mozilla/glean/webext";
>            ~~~~~~~~~
> 
>     at createTSError (/home/circleci/project/samples/browser/webext/node_modules/ts-node/src/index.ts:820:12)
>     at reportTSError (/home/circleci/project/samples/browser/webext/node_modules/ts-node/src/index.ts:824:19)
>     at getOutput (/home/circleci/project/samples/browser/webext/node_modules/ts-node/src/index.ts:1014:36)
>     at Object.compile (/home/circleci/project/samples/browser/webext/node_modules/ts-node/src/index.ts:1322:43)
>     at transformSource (/home/circleci/project/samples/browser/webext/node_modules/ts-node/src/esm.ts:380:37)
>     at load (/home/circleci/project/samples/browser/webext/node_modules/ts-node/src/esm.ts:280:51)
>     at async ESMLoader.load (node:internal/modules/esm/loader:359:20)
>     at async ESMLoader.moduleProvider (node:internal/modules/esm/loader:280:47)
>     at async link (node:internal/modules/esm/module_job:70:21)
> 
> Exited with code exit status 1
> 
> CircleCI received exit code 1
> ```

Hmmmmm this is strange and I do not even know what I have done wrong.
everything is underlined in the test file :sad: .
![image](https://user-images.githubusercontent.com/40355086/164472197-57a63851-5fed-4038-934b-0dab12702ca8.png)

2022-04-27 16:58 UTC, Dexterp37 commented
> Hmmmmm this is strange and I do not even know what I have done wrong. everything is underlined in the test file :sad: . 

In this PR you're changing the way the `ErrorType` symbol is being exported. Without this PR, things are being exported via the platform-specific endpoints, e.g. `import { ErrorType } from "@mozilla/glean/webext";`.
This PR exposes it through its own entry point and so call sites need to be adjusted like this:

`import { ErrorType } from "@mozilla/glean/error";`

2022-04-28 12:39 UTC, Dexterp37 commented
@tawahpeggy note that the proper import need to be applied to all the samples and in all the other locations within the codebase.

2022-04-29 10:08 UTC, Dexterp37 requested changes

2022-04-29 10:08 UTC, Dexterp37 commented on glean/package.json
> +  "exports": {
nit: please remove the trailing whitespaces on this line

2022-04-29 10:08 UTC, Dexterp37 commented on glean/src/core/error/index.ts
> -import type { ErrorType } from "./error_type.js";
I'm not sure this change is required: this is internal, and so we can directly reference the file as we did before. We only need to change occurrences of imports that import the "exposed" entrypoint.

2022-05-02 11:46 UTC, Dexterp37 requested changes
We're almost there! I think with the last two requested changes it should be ok for merging.

2022-05-02 11:46 UTC, Dexterp37 commented on glean/src/core/error/index.ts
> +import { ErrorType } from "./error_type.js";
Would you kindly add back the `type`?

2022-05-02 11:46 UTC, Dexterp37 commented on glean/src/entry/qt.ts
> +import type { ErrorType } from "@mozilla/glean/error";
Was this change required?

2022-05-10 10:15 UTC, tawahpeggy commented
Hello @Dexterp37, hope you are having a great day.
please help check this PR and see if there's something else to be done

2022-05-11 09:21 UTC, Dexterp37 commented
> Hello @Dexterp37, hope you are having a great day. please help check this PR and see if there's something else to be done

Hi @tawahpeggy , I'm doing great, thanks. Note that the PR is still failing the tests (see the failing CI jobs), so we can't merge it: would you kindly fix the codebase to make sure tests run ok? You can also run them locally to reduce the turnaround time.

2022-05-18 14:47 UTC, tawahpeggy commented
> > Hello @Dexterp37, hope you are having a great day. please help check this PR and see if there's something else to be done
> 
> Hi @tawahpeggy , I'm doing great, thanks. Note that the PR is still failing the tests (see the failing CI jobs), so we can't merge it: would you kindly fix the codebase to make sure tests run ok? You can also run them locally to reduce the turnaround time.

I noticed the failed test but I really do not know how to fix it. any heads up?

2022-05-23 10:41 UTC, Dexterp37 commented
> > > Hello @Dexterp37, hope you are having a great day. please help check this PR and see if there's something else to be done
> > 
> > 
> > Hi @tawahpeggy , I'm doing great, thanks. Note that the PR is still failing the tests (see the failing CI jobs), so we can't merge it: would you kindly fix the codebase to make sure tests run ok? You can also run them locally to reduce the turnaround time.
> 
> I noticed the failed test but I really do not know how to fix it. any heads up?

I think we need to add something like this

```
      "error": [
        "./dist/types/core/error/error_type.d.ts"
      ]
```

after `"testing"` in [here](https://github.com/mozilla/glean.js/blob/e7e5bd3a19f81082f9c0cba08d6e0ad4f817c67f/glean/package.json#L43)

2022-06-17 12:33 UTC, tawahpeggy commented
Thank you @Dexterp37, 
I get this message at the end. when I run  the test, please is it something I should worry about? ![image](https://user-images.githubusercontent.com/40355086/174298540-371b79c2-af58-4dc9-9774-4c7cb9a6cab1.png)

2022-06-20 09:14 UTC, moz-glean commented
# Build size report

Merging https://github.com/mozilla/glean.js/pull/1318 into [main](https://github.com/mozilla/glean.js) will:
* **Leave** the size of full **Web Extension** bundle **unchanged**.
* **Leave** the size of full **Website** bundle **unchanged**.
* **Leave** the size of full **Node.js** bundle **unchanged**.
* **Leave** the size of full **Qt/QML** bundle **unchanged**.

---

| | Current size | New size | Size increase |
|--:|:---:|:---:|:---:|
| **Web Extension** |
| core only | 55 KB | 55 KB | 📉 0 bytes |
| full bundle | 95 KB | 95 KB | 📉 0 bytes |
| **Website** |
| core only | 56 KB | 56 KB | 📉 0 bytes |
| full bundle | 96 KB | 96 KB | 📉 0 bytes |
| **Node.js** |
| core only | 55 KB | 55 KB | 📉 23 bytes |
| full bundle | 101 KB | 101 KB | 📉 23 bytes |
| **Qt/QML** |
| core only | 78 KB | 78 KB | 📉 0 bytes |
| full bundle | 78 KB | 78 KB | 📉 0 bytes |

2022-06-20 09:16 UTC, Dexterp37 approved these changes

2022-06-20 09:17 UTC, merged

2022-06-21 17:48 UTC, tawahpeggy commented
> > Thank you @Dexterp37, I get this message at the end. when I run the test, please is it something I should worry about? ![image](https://github.com/assets/40355086/371b79c2-af58-4dc9-9774-4c7cb9a6cab1)
> 
> I don't think we should worry about that as long as this runs on CI. Let me check :)

Okay understood thanks.