Bug 1761495: apply timeout in worker
mozilla/glean.js pull request #1361
Opened 2022-05-30 14:22 UTC by neel-desh

### Pull Request checklist ###

- [ ] **Quality**: Make sure this PR builds and runs cleanly.
  - Inside the `glean/` folder, run:
    - `npm run test` Runs _all_ tests
    - `npm run lint` Runs _all_ linters
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes a changelog entry to `CHANGELOG.md` or an explanation of why it does not need one
- [ ] **Documentation**: This PR includes documentation changes, an explanation of why it does not need that or a follow-up bug has been filed to do that work
  - Documentation should be added to [The Glean Book](https://mozilla.github.io/glean/book/index.html) when making changes to Glean's user facing API
    - When changes to the Glean Book are necessary, link to the corresponding PR on the [`mozilla/glean`](https://github.com/mozilla/glean) repository
  - Documentation should be added to [the Glean.js developer documentation](https://github.com/mozilla/glean.js/tree/main/docs) when making internal code changes

2022-05-30 14:23 UTC, neel-desh commented
@Dexterp37

2022-05-30 15:46 UTC, neel-desh commented
How do I go about tests and documentation?
I believe I should include a tests for the platforms without timeouts to check if it works as expected, and also include a test for core with timeout. Im not sure where to start.

2022-05-31 05:50 UTC, neel-desh commented on glean/src/core/upload/worker.ts
> +        timeoutTaskId = Context.platform.timer.setTimeout(()=>{resolve(new UploadResult(UploadResultStatus.RecoverableFailure));}, DEFAULT_UPLOAD_TIMEOUT_MS);
Can this `timeoutTaskId` be zero? From what i have read it will be incremented for every setTimeout call. [stackoverflow post](https://stackoverflow.com/questions/3943553/can-settimeout-ever-return-0-as-the-id)

If yes then I should add a check at line 129, other wise it can be evaluated to be false, i guess.

2022-06-01 06:05 UTC, neel-desh commented
ping @Dexterp37

2022-06-01 13:52 UTC, Dexterp37 commented
> How do I go about tests and documentation?

Code documentation will be sufficient in this case. This is an internal change, so no need for public documentation in our book.

> I believe I should include tests for core. or should I implement without timeout and tests if it timesout or not. Is there any specific test case that i can refer to?

One reference test is [this one](https://github.com/mozilla/glean.js/blob/e7e5bd3a19f81082f9c0cba08d6e0ad4f817c67f/glean/tests/unit/core/upload/worker.spec.ts#L402-L438).

2022-06-01 14:37 UTC, Dexterp37 requested changes
Thank you for this! This is a nice good start. I have some minor changes recommended below.

2022-06-01 14:37 UTC, Dexterp37 commented on CHANGELOG.md
> +  * Applied `DEFAULT` timeout on ping upload worker.
```suggestion
* [#1361](https://github.com/mozilla/glean.js/pull/1361): BUGFIX: Guarantee that custom uploaders will timeout even if they do not implement a timeout mechanism.
```

2022-06-01 14:37 UTC, Dexterp37 commented on glean/src/core/upload/worker.ts
> +        timeoutTaskId = Context.platform.timer.setTimeout(()=>{resolve(new UploadResult(UploadResultStatus.RecoverableFailure));}, DEFAULT_UPLOAD_TIMEOUT_MS);
This line is definitely too long. Not sure why the linter hasn't complained, but would you kindly break it down?

2022-06-01 14:57 UTC, neel-desh commented on glean/src/core/upload/worker.ts
> +        if(result.status && timeoutTaskId){
Sure,

2022-06-01 15:56 UTC, neel-desh commented on glean/tests/unit/core/upload/worker.spec.ts
> +    );
@Dexterp37 I'm not sure how do I test it.

2022-06-03 14:23 UTC, neel-desh commented on glean/tests/unit/core/upload/worker.spec.ts
> +    );
How do i make the upload task to timeout.

2022-06-07 16:18 UTC, neel-desh commented on glean/tests/unit/core/upload/worker.spec.ts
> +    );
ping @Dexterp37

2022-06-08 14:32 UTC, Dexterp37 requested changes

2022-06-08 14:32 UTC, Dexterp37 commented on glean/src/core/upload/worker.ts
> +        }
```suggestion
        if (result.status) {
          Context.platform.timer.clearTimeout(timeoutTaskId);
        } else {
          log(LOG_TAG, "Timeout while attempting to upload ping.", LoggingLevel.Error);
        }

        return result;
```

2022-06-08 14:32 UTC, Dexterp37 commented on glean/src/core/upload/worker.ts
> +
```suggestion
```

2022-06-08 16:39 UTC, neel-desh commented on glean/tests/utils.ts
> +    });
@Dexterp37  something like this?

2022-06-12 15:27 UTC, neel-desh commented
@Dexterp37 does this look good?

2022-06-23 16:36 UTC, neel-desh commented
@Dexterp37 ping

2022-07-26 07:26 UTC, neel-desh commented
@Dexterp37 Ping.....

2022-07-26 07:41 UTC, Dexterp37 commented
> @Dexterp37 Ping.....

Hey @neel-desh , sorry for the delay - I'm sorry things are a bit convoluted on our end and this might take a bit longer to get reviewed and merged.

2022-09-09 09:42 UTC, neel-desh commented
> > @Dexterp37 Ping.....
> 
> Hey @neel-desh , sorry for the delay - I'm sorry things are a bit convoluted on our end and this might take a bit longer to get reviewed and merged.

hey any update on this?

2022-09-14 08:44 UTC, Dexterp37 commented
> > > @Dexterp37 Ping.....
> > 
> > 
> > Hey @neel-desh , sorry for the delay - I'm sorry things are a bit convoluted on our end and this might take a bit longer to get reviewed and merged.
> 
> hey any update on this?

Hi @neel-desh , we'll prioritize reviewing this after our company all Hands. Sorry again for the delay.

2022-09-14 19:49 UTC, rosahbruno requested changes
I am not as knowledgable about this process as @Dexterp37 , so these are more general thoughts that him and I will discuss and I will update this PR with more comments later.

2022-09-14 19:49 UTC, rosahbruno commented on glean/tests/utils.ts
> +}
Small things
- Typo in `resolve`
- If you prefix a variable name with `_` you don't also need the eslint-ignore, they accomplish the same thing
- Formatting

```suggestion

export class TimeoutTaskMockUploader extends Uploader {
  public count = 0;

  async post(_url: string, _body: string): Promise<UploadResult> {
    this.count++;
    return new Promise<UploadResult>((resolve) => {
      setTimeout(() => {
        resolve(new UploadResult(UploadResultStatus.RecoverableFailure));
      }, 1500);
    });
  }
}

```

2022-09-14 19:49 UTC, rosahbruno commented on glean/tests/unit/core/upload/worker.spec.ts
> +  it("test for timeout.", async function () {
**nitpick**: The names of the tests typically don't end with a period. Also, can we make this test name a bit more descriptive?

Also, I am not sure this tests everything that we would want it to test. I would think that we would want to create a test that utilizes a `PingUploadWorker` and make one of those tasks timeout.

The test should look more like this - https://github.com/mozilla/glean.js/blob/main/glean/tests/unit/core/upload/worker.spec.ts#L402

Although I defer to @Dexterp37 for confirmation of that

2022-09-21 15:52 UTC, Dexterp37 commented on glean/tests/unit/core/upload/worker.spec.ts
> +  it("test for timeout.", async function () {
Yes, I concur with you, @rosahbruno

2023-11-13 14:05 UTC, rosahbruno commented
After some consideration and chatting with the team, we are going to close this out. We've made some decisions about major changes to Glean.js recently and this will not be needed any longer.

We appreciate the contribution, thanks so much!

2023-11-13 14:05 UTC, closed without merging