Bug 1716954 - Implement the Timing Distribution Metric
mozilla/glean.js pull request #1475
Opened 2022-09-08 20:39 UTC by rosahbruno

This is a first pass at the timing distribution metric implementation. I wanted to put this up to get some feedback and see if anyone sees anything immediately apparent that needs to be addressed or anything I may have missed while porting over the Rust implementation.

**Todo**
- [ ] Additional tests for the different time units
- [ ] Tests for the histogram implementations
- [ ] Testing this out in sample projects

### Pull Request checklist ###

- [ ] **Quality**: Make sure this PR builds and runs cleanly.
  - Inside the `glean/` folder, run:
    - `npm run test` Runs _all_ tests
    - `npm run lint` Runs _all_ linters
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes a changelog entry to `CHANGELOG.md` or an explanation of why it does not need one
- [ ] **Documentation**: This PR includes documentation changes, an explanation of why it does not need that or a follow-up bug has been filed to do that work
  - Documentation should be added to [The Glean Book](https://mozilla.github.io/glean/book/index.html) when making changes to Glean's user facing API
    - When changes to the Glean Book are necessary, link to the corresponding PR on the [`mozilla/glean`](https://github.com/mozilla/glean) repository
  - Documentation should be added to [the Glean.js developer documentation](https://github.com/mozilla/glean.js/tree/main/docs) when making internal code changes

2022-09-12 22:53 UTC, rosahbruno commented
@badboy 
When I was updating the Glean docs I noticed that the `measure` API is not provided in all languages, is this something that we want to implement for Glean.js?

2022-09-15 11:35 UTC, badboy requested changes
Good work here!
Got a couple of nits and a few questions we should resolve before landing this.

2022-09-15 11:35 UTC, badboy commented on glean/src/core/metrics/types/timing_distribution.ts
> +  values: Record<TimerId, number>;
Why is this `TimerId` here? Arent' those just the bucket indices?

2022-09-15 11:35 UTC, badboy commented on glean/src/core/metrics/types/timing_distribution.ts
> +    const negativeDuration = (v as number[]).find((key) => !isNaN(+key) && +key < 0);
Why `+key`? Is this just to ensure this is a number? (I don't do nearly enough js/ts, so I will occasionally ask basic questions like this to understand)

2022-09-15 11:35 UTC, badboy commented on glean/src/core/metrics/types/timing_distribution.ts
> +
We already do this check at the beginning. I think we don't need it here anymore
(I saw we do the same on glean-core, but I don't see why. I think this is a left-over from some earlier refactoring).
```suggestion
```

2022-09-15 11:35 UTC, badboy commented on glean/tests/unit/core/metrics/timing_distribution.spec.ts
> +    assert.equal(await metric.testGetValue("aPing"), undefined);
Above should record an error, right? Let's check for that.

```suggestion
    assert.equal(await metric.testGetValue("aPing"), undefined);
    assert.equal(1, await metric.testGetNumRecordedErrors(ErrorType.InvalidValue));
```

2022-09-15 11:35 UTC, badboy commented on glean/tests/unit/core/metrics/timing_distribution.spec.ts
> +    assert.equal(0, await metric.testGetNumRecordedErrors(ErrorType.InvalidValue));
1 error, right?

```suggestion
    assert.equal(1, await metric.testGetNumRecordedErrors(ErrorType.InvalidValue));
```

2022-09-15 11:35 UTC, badboy commented on glean/tests/unit/core/metrics/timing_distribution.spec.ts
> +    // We should get a sample in 3 buckets.
2 buckets, just 2 values in one of them.

2022-09-15 11:35 UTC, badboy commented on glean/tests/unit/core/metrics/timing_distribution.spec.ts
> +    assert.ok(testValue?.sum || 0 > 0, "The sum of the distribution should be greater than 0.");
Huh, I read this as `(testValue?.sum) || (0 > 0)` and was seriously confused why one would write that :D 
No change necessary though.

2022-09-15 11:35 UTC, badboy commented on glean/tests/unit/core/metrics/timing_distribution.spec.ts
> +  it("unique IDs are persisted through restarts", async function () {
This is actually interesting as this is different from how it behaves on glean-core.
We don't persist started timers there, so started timers are lost after restarts.

I'm not opposed to just leaving this as is here, but it should be documented.

2022-09-15 11:35 UTC, badboy commented on glean/tests/unit/core/metrics/timing_distribution.spec.ts
> +  it("unique IDs are persisted through restarts", async function () {
Can you point me to where we persist the global timerid counter?

2022-09-15 12:01 UTC, rosahbruno commented on glean/src/core/metrics/types/timing_distribution.ts
> +    const negativeDuration = (v as number[]).find((key) => !isNaN(+key) && +key < 0);
Yep, +key is a just quick conversion to a number. This conversion is left over from the original implementation where I was storing the map rather than an array of numbers. So good call out, this extra casting shouldn't be needed anymore, I will remove.

2022-09-15 12:02 UTC, rosahbruno commented on glean/tests/unit/core/metrics/timing_distribution.spec.ts
> +    assert.ok(testValue?.sum || 0 > 0, "The sum of the distribution should be greater than 0.");
Haha yeah, the optionals are annoying, so unless I add the fallback it will treat it as possibly undefined and yell at me, so it looks a bit odd. Let me see if there is a way to make these look a little nicer

2022-09-15 12:06 UTC, rosahbruno commented on glean/tests/unit/core/metrics/timing_distribution.spec.ts
> +  it("unique IDs are persisted through restarts", async function () {
This was something I should've gotten some more clarification on I think. In the Rust implementation instead of using just an integer, it uses `AtomicUsize` instead. Since JS doesn't really have a similar implementation, I figured this would be the closest to that.

If you don't think we need to be this worried about assigning timer IDs, then that is fine. My worry was just that once we start a timer and if something happens or there is a restart, we are always going to grab the first ID again and we could end up overwriting previously saved info.

BUT, I could be making incorrect assumptions here or thinking about it wrong too.

2022-09-15 12:09 UTC, rosahbruno commented on glean/src/core/metrics/types/timing_distribution.ts
> +  values: Record<TimerId, number>;
The `TimerId` type is nothing more than a copy of the `number` type, it just exists for better readablity. So in reality, that statement is the same as `values: Record<number, number`.

But looking at it now, I don't really think it does us any good to have that alias, its obvious its an ID because it is the first argument for the `Record` and likely just makes things more confusing

2022-09-15 12:17 UTC, badboy commented on glean/tests/unit/core/metrics/timing_distribution.spec.ts
> +  it("unique IDs are persisted through restarts", async function () {
But in real-world use the only way Glean "restarts" is that someone reloads the webpage (assuming the glean.js-on-web usecase).
Any in-memory state is lost then, including `_timingDistributionId` in the context, right?
If so, I am confused why the test works. Maybe the "restart" machinery doesn't clear out that context correctly?

Are not-yet-stopped timers persisted? (that is: is their `timer id -> start time` mapping storred in the client?)

2022-09-15 12:18 UTC, badboy commented on glean/src/core/metrics/types/timing_distribution.ts
> +  values: Record<TimerId, number>;
But this is `bucket index -> count`, not `timer id -> start time` (or similar), right?

2022-09-15 12:22 UTC, rosahbruno commented on glean/src/core/metrics/types/timing_distribution.ts
> +  values: Record<TimerId, number>;
Yeah, that's true, that's a good point. I am going to just remove `TimerId` alias altogether anyways, it is being used incorrectly and doesn't really help make anything easier to understand

2022-09-15 12:23 UTC, rosahbruno commented on glean/src/core/metrics/types/timing_distribution.ts
> +  values: Record<TimerId, number>;
Removed in 8270f955be485847c86e9ed914a8cbe03611ba1c

2022-09-15 12:28 UTC, rosahbruno commented on glean/tests/unit/core/metrics/timing_distribution.spec.ts
> +    // We should get a sample in 3 buckets.
Yep, copied this comment directly from Rust, so we can likely update that too at some point
https://github.com/mozilla/glean/blob/main/glean-core/tests/timing_distribution.rs#L392

2022-09-15 12:29 UTC, rosahbruno commented on glean/tests/unit/core/metrics/timing_distribution.spec.ts
> +    // We should get a sample in 3 buckets.
Fixed 95632814c29afb4ff917264c89510f362e9450b5

2022-09-15 12:35 UTC, rosahbruno commented on glean/tests/unit/core/metrics/timing_distribution.spec.ts
> +    assert.equal(await metric.testGetValue("aPing"), undefined);
Yes, tested this locally and it works as expected.

2022-09-15 12:37 UTC, rosahbruno commented on glean/tests/unit/core/metrics/timing_distribution.spec.ts
> +    assert.equal(0, await metric.testGetNumRecordedErrors(ErrorType.InvalidValue));
Yes! Good call, this was due to me incorrectly setting the error type. I need to make another change for this to work, so I will just push a commit with this and the other change.

2022-09-15 12:40 UTC, rosahbruno commented on glean/tests/unit/core/metrics/timing_distribution.spec.ts
> +    assert.equal(0, await metric.testGetNumRecordedErrors(ErrorType.InvalidValue));
Fixed https://github.com/mozilla/glean.js/pull/1475/commits/ecbeedf5aa971056f95b85f7d61b8e7b5ac76763

2022-09-15 12:50 UTC, rosahbruno commented on glean/tests/unit/core/metrics/timing_distribution.spec.ts
> +    assert.ok(testValue?.sum || 0 > 0, "The sum of the distribution should be greater than 0.");
This would actually be better as just `assert.ok(!!testValue?.sum)` since truthy'ing the value makes sure that any integer is greater than 0. I will update to use that instead of the more confusing option

2022-09-15 12:55 UTC, rosahbruno commented on glean/tests/unit/core/metrics/timing_distribution.spec.ts
> +    assert.ok(testValue?.sum || 0 > 0, "The sum of the distribution should be greater than 0.");
I updated these checks to use the truthy check now instead. I also updated all the places where we manually checked the length of our values map (`Object.keys(values).length`) to use the `count` property for our `DistributionData`, which accomplishes the same thing - just much more easily.

2022-09-15 12:56 UTC, rosahbruno commented on glean/tests/unit/core/metrics/timing_distribution.spec.ts
> +  it("unique IDs are persisted through restarts", async function () {
I don't want to answer without looking into it, let me take a look and see what I can find

2022-09-15 18:37 UTC, rosahbruno commented on glean/tests/unit/core/metrics/timing_distribution.spec.ts
> +  it("unique IDs are persisted through restarts", async function () {
So I took a look, and what we talked about earlier was correct - they aren't persisting, the restart just isn't clearing out the important context.

Since this is not actually "persisting" anything and we don't need to worry about that, I refactored the implementation to just use a class variable to store the ID. Now instead of reading and writing from the global context, we just update the `timerId` in the class itself.

I re-ran all the tests and everything is still working as expected without the more global ID. So as long as you don't see any issues with just managing that ID in the class itself, this should be better.

2022-09-20 15:25 UTC, badboy approved these changes
few last nits, but then it's ready to go

2022-09-20 15:25 UTC, badboy commented on glean/tests/unit/core/metrics/timing_distribution.spec.ts
> +  it("attempting to start/accumulate when glean upload is disable is a no-op", async function () {
```suggestion
  it("attempting to start/accumulate when glean upload is disabled is a no-op", async function () {
```

2022-09-20 15:25 UTC, badboy commented on glean/tests/unit/core/metrics/timing_distribution.spec.ts
> +    const id2 = metric.start();
Can you add a comment that this is the one that records? `start` always works, we only check upload-enabled on `stop`

2022-09-20 16:21 UTC, rosahbruno commented on glean/tests/unit/core/metrics/timing_distribution.spec.ts
> +    const id2 = metric.start();
Good call, added a clarifying comment
https://github.com/mozilla/glean.js/pull/1475/commits/be8bbf182444056a6d7ccb9bc864d8bcb8099d8f

2022-09-21 12:55 UTC, merged