Bug 1790035 - Write python script to temp file, execute, then delete
mozilla/glean.js pull request #1500
Opened 2022-09-13 20:03 UTC by rosahbruno

On Windows, users were unable to use the `npm run glean` command because the way we passed the python script as a long, template literal broke the CLI.

By moving that script to its own file, executing it, then deleting it, we are able to successfully run the command.

**This is a bug fix, it does not require documentation changes.**

### Pull Request checklist ###

- [x] **Quality**: Make sure this PR builds and runs cleanly.
  - Inside the `glean/` folder, run:
    - `npm run test` Runs _all_ tests
    - `npm run lint` Runs _all_ linters
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes a changelog entry to `CHANGELOG.md` or an explanation of why it does not need one
- [x] **Documentation**: This PR includes documentation changes, an explanation of why it does not need that or a follow-up bug has been filed to do that work
  - Documentation should be added to [The Glean Book](https://mozilla.github.io/glean/book/index.html) when making changes to Glean's user facing API
    - When changes to the Glean Book are necessary, link to the corresponding PR on the [`mozilla/glean`](https://github.com/mozilla/glean) repository
  - Documentation should be added to [the Glean.js developer documentation](https://github.com/mozilla/glean.js/tree/main/docs) when making internal code changes

2022-09-13 20:21 UTC, rosahbruno commented
@Dexterp37 
Do you think this would be better in just its own file that we call? The reason that I am creating it locally and then removing it is so that we aren't trying to manually get to a certain path to execute the script. This goes hand-in-hand with the issue I am seeing with the `build:qt` command since I think that is happening because of the way we are traversing the file directories.

Either way, I think it would be good for us to chat about this and how you currently run `Glean.js` on your windows machine before we land these changes.

2022-09-14 07:30 UTC, Dexterp37 requested changes

2022-09-14 07:30 UTC, Dexterp37 commented on glean/src/cli.ts
> +  // causes issues on Windows machines. We are able to work around this by
Please mention that the issue is due to passing multiple lines to the `-c` argument.

2022-09-14 07:30 UTC, Dexterp37 commented on glean/src/cli.ts
> +    fs.writeFileSync("cli_util.py", PYTHON_SCRIPT);
Let's generate the script in a [temporary directory](https://nodejs.org/docs/latest-v16.x/api/fs.html#fs_fs_mkdtemp_prefix_options_callback) in the temporary directory for the OS. This has the major advantage of not polluting the directory in which we're calling this in case things go wrong.

2022-09-14 07:30 UTC, Dexterp37 commented on glean/src/cli.ts
> +      // after script succeeds, we remove it
```suggestion
      // After script succeeds, we remove it.
```

2022-09-14 07:30 UTC, Dexterp37 commented on glean/src/cli.ts
> +// For discover-ability, try to leave this function as the last one on this file.
nit: why this change? [discoverability](https://dictionary.cambridge.org/dictionary/english/discoverability) seems to be an appropriate word here

2022-09-14 07:31 UTC, Dexterp37 commented
> @Dexterp37 Do you think this would be better in just its own file that we call? The reason that I am creating it locally and then removing it is so that we aren't trying to manually get to a certain path to execute the script.

I believe we should stick, for now, to generating a temporary file with the content of the script, if only for consistency with the other SDKs which have the script "embedded" in the cli/plugin used for building Glean products.

> This goes hand-in-hand with the issue I am seeing with the `build:qt` command since I think that is happening because of the way we are traversing the file directories.

What are you seeing?

> Either way, I think it would be good for us to chat about this and how you currently run `Glean.js` on your windows machine before we land these changes.

Happy to chat!

2022-09-14 11:42 UTC, rosahbruno commented on glean/src/cli.ts
> +// For discover-ability, try to leave this function as the last one on this file.
My code spell checker recognized this as a typo, so mostly just fixed it so it stopped complaining. But I can change it back and just ignore this word in the future.

2022-09-14 11:47 UTC, rosahbruno commented
@Dexterp37 

> I believe we should stick, for now, to generating a temporary file with the content of the script, if only for consistency with the other SDKs which have the script "embedded" in the cli/plugin used for building Glean products.

Using a temporary directory sounds like a better idea, I will make some updates.

> What are you seeing?

When I try to run `npm run build` on my windows machine, the command fails. When you run it on windows, which shell are you using? When I try PowerShell or command prompt I get an error saying that it can't execute `rm` command. When I use bash, I get an issue that looks like it might be something to do with how we define the file path here https://github.com/mozilla/glean.js/blob/main/glean/package.json#L78.

2022-09-14 12:21 UTC, Dexterp37 commented on glean/src/cli.ts
> +// For discover-ability, try to leave this function as the last one on this file.
I think ignoring is fine, we use this word in some other places as well :)

2022-09-14 15:52 UTC, rosahbruno commented
@Dexterp37 
I was able to verify that this change works on both Mac and Windows. I ran into some issues with running things on Windows, but those will be addressed in a separate bug that I will be filing.

### Testing inside of Glean.js
- Pull down code on windows
- Run all commands using Git Bash
- Remove the `build:qt` command from the `npm run build` script
- Then run the node sample project (you will see the generated folder is now created and you can see `pings.js` is there)

### Testing sample project
I also copied over all the code into the sample project, patched the `node_module`, and then ran it again and `pings.ts` was created.

2022-09-14 16:52 UTC, Dexterp37 requested changes
Almost there! We should use `log` (as it's used throughout the file). We're good to go after these two last changes.

2022-09-14 16:52 UTC, Dexterp37 commented on glean/src/cli.ts
> +    console.error(error);
```suggestion
    log(
      LOG_TAG,
      ["Unable to write utility script to tmp directory.\n", error],
      LoggingLevel.Error
    );
```

2022-09-14 16:52 UTC, Dexterp37 commented on glean/src/cli.ts
> +    fs.writeFileSync(path.join(tmpDir, "script.py"), PYTHON_SCRIPT);
nit: `script.py` is used both here and in `cmd`: should we make it a const and share it?

2022-09-14 17:39 UTC, rosahbruno commented on glean/src/cli.ts
> +    fs.writeFileSync(path.join(tmpDir, "script.py"), PYTHON_SCRIPT);
Handled in latest commit

2022-09-15 08:37 UTC, Dexterp37 approved these changes
This looks good to merge with the one final change below merged. Thanks!

2022-09-15 08:37 UTC, Dexterp37 commented on glean/src/cli.ts
> +    return;
```suggestion
    process.exit(1);
```

2022-09-15 08:37 UTC, Dexterp37 commented on glean/src/cli.ts
> +    return;
Sorry I missed this in the last review.

2022-09-15 11:56 UTC, rosahbruno commented
@Dexterp37 
Good call, apologies for missing that. Once tests are completed, will merge. Thanks for the thoughtful reviews!

2022-09-15 17:25 UTC, merged