Use a custom uploader for the encryption test
mozilla/glean.js pull request #159
Opened 2021-03-30 11:33 UTC by Dexterp37

This fixes a couple of small bugs in the configuration object (first commit) and then converts a test to use the uploader instead of spies.

2021-03-30 11:33 UTC, Dexterp37 commented on glean/tests/plugins/encryption.spec.ts
> +      JSON.parse(body)!["payload"],
The linter is not being nice here. Any suggestion @brizental ?

2021-03-30 11:55 UTC, brizental commented on glean/src/core/config.ts
> +    this.plugins = config?.plugins;
It was on purpose that I did not include the plugins in the object but only in the configuration. The Glean singleton doesn't need to be aware of the plugins, each event is aware of the plugins related to it.

2021-03-30 11:57 UTC, brizental commented on glean/tests/plugins/encryption.spec.ts
> +      JSON.parse(body)!["payload"],
`body && body.payload ? payload : ""`?

2021-03-30 12:06 UTC, brizental commented on glean/tests/plugins/encryption.spec.ts
> +      JSON.parse(body)!["payload"],
Or, something uglier `const payload = body?.payload as string;`

2021-03-31 09:00 UTC, brizental requested changes

2021-03-31 09:00 UTC, brizental commented on glean/tests/plugins/encryption.spec.ts
> -    const encryptedPayload = (await Glean.pingsDatabase.getAllPings())[pingId]["payload"]["payload"];
We do this "get pings from database and mock upload" hack [all around](https://github.com/mozilla/glean.js/search?q=Disable+ping+uploading+for+it+not+to+interfere+with+this+tests.). Would you kindly file a bug for us to replace that with a propoer custom uploader?

2021-03-31 09:00 UTC, brizental commented on glean/tests/plugins/encryption.spec.ts
> +        uploadPromiseResolve({url, body, headers});
Why does this need to be a promise? Why not:

```ts
// Also, isn't there a clever Typescript way to 
// extract the function args instead of defining `UploadSignature`?
let interceptedArgs: UploadSignature;
...
post(args) { 
   interceptedArgs = args;
   ...
}
```

After writing this example, I realize you could probably go further and do something like:

```ts
const MockUploader: Uploader = {
   post: sinon.stub().returns(Promise.resolve({...}),
}
```

And then leverage sinon to do all the necessary assertions.

2021-03-31 12:38 UTC, Dexterp37 commented on glean/tests/plugins/encryption.spec.ts
> +    class MockUploader implements Uploader {
As per our discussion today I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1702206

2021-03-31 12:40 UTC, Dexterp37 commented on glean/tests/plugins/encryption.spec.ts
> -    const encryptedPayload = (await Glean.pingsDatabase.getAllPings())[pingId]["payload"]["payload"];
https://bugzilla.mozilla.org/show_bug.cgi?id=1702208

2021-03-31 14:57 UTC, Dexterp37 commented on glean/tests/plugins/encryption.spec.ts
> +        uploadPromiseResolve({url, body, headers});
As discussed, I've added a comment

2021-03-31 14:59 UTC, Dexterp37 commented on glean/tests/plugins/encryption.spec.ts
> +        uploadPromiseResolve({url, body, headers});
And filed https://bugzilla.mozilla.org/show_bug.cgi?id=1702251 :D

2021-03-31 15:16 UTC, merged