Bug 1679381 - Implement the datetime metric type
mozilla/glean.js pull request #16
Opened 2020-12-17 17:01 UTC by brizental

Get ready for some fun ~~string~~ date and timezone manipulation!

2020-12-17 17:08 UTC, brizental commented on src/metrics/time_unit.ts
> +  case TimeUnit.Nanosecond:
Javascript Date object only has milliseconds resolution. Which means nano and microseconds datetime metrics don't do anything different than record a payload with some extra zeroes at the end.

We could use the browser specific `window.performance` API to get up to microsecond precision, but I personally I am not sure if it is worth the effort and if it is I'd argue for making it a follow up.

My recommendation is that we leave it like this and have a glinter warning for people adding nanoseconds or microseconds datetimes and building for JS. If that is not possible a documentation + docstring note could suffice.

2020-12-17 17:08 UTC, brizental commented on src/metrics/time_unit.ts
> + * the timezone offset will be applied before transforming to an object.
This is not out of my head. It is the same behaviour as when you build a Date object from an ISO string with a different timezone than your local one.

2020-12-17 17:08 UTC, brizental commented on tests/metrics/time_unit.spec.ts
> +    Date.prototype.getTimezoneOffset.restore();
Hey, Alessio, you are more familiar with sinon than I am at this point. Should I be using sinon's sandbox here? Why is that better, if so?

2020-12-17 17:31 UTC, brizental commented on tests/metrics/time_unit.spec.ts
> +    Date.prototype.getTimezoneOffset.restore();
Nevermind, answered my own question and moved to user a sandbox.

2020-12-18 11:42 UTC, Dexterp37 requested changes
My main concern with this PR is the "guessing" part, which uncovered a problem that we'll definitely have with other metric types, too. We need to store extra metadata along with the data we store, and we don't necessarily want to send that. See my comments.

2020-12-18 11:42 UTC, Dexterp37 commented on src/metrics/time_unit.ts
> +  case TimeUnit.Nanosecond:
> 
> 
> Javascript Date object only has milliseconds resolution. Which means nano and microseconds datetime metrics don't do anything different than record a payload with some extra zeroes at the end.

Yeah, I feared as much :)

> We could use the browser specific `window.performance` API to get up to microsecond precision, but I personally I am not sure if it is worth the effort and if it is I'd argue for making it a follow up.
 
 I agree with you we probably don't need it for `DateTime`, but that's presumably what we'll want for `Timespan` and `TimingDistribution` or `Event`.
 
> My recommendation is that we leave it like this and have a glinter warning for people adding nanoseconds or microseconds datetimes and building for JS. If that is not possible a documentation + docstring note could suffice.

yes, I agree. Let's do this for the `DateTime` metric.

2020-12-18 11:42 UTC, Dexterp37 commented on src/metrics/time_unit.ts
> +    return "(\\d{4}-([0]\\d|1[0-2])-([0-2]\\d|3[0-1])(T(([0-1]\\d)|([0-2][0-3])))(:[0-5]\\d)(:[0-5]\\d)(\\.\\d{9}))";
Instead of the hard to debug string formatting madness here, what about using `theDate.setXX` and then `theDate.toISOString` or `toUTC` as needed?

2020-12-18 11:42 UTC, Dexterp37 commented on src/metrics/time_unit.ts
> +function guessTimeUnitPrecision(value: string): TimeUnit {
Wow. Why do we need this? Don't we always have the time unit?

2020-12-18 11:42 UTC, Dexterp37 commented on src/metrics/time_unit.ts
> +export function timeUnitFromString(unit: string): TimeUnit {
Instead of rolling out our own, can't we use [this](https://www.typescriptlang.org/docs/handbook/enums.html#reverse-mappings)? Do we **need** the string value to start by lowercase letters (since this makes it not possible to use the reverse-mappings above)

2020-12-18 11:42 UTC, Dexterp37 commented on src/metrics/datetime.ts
> +export function isDatetimeMetricPayload(v: unknown): v is DatetimeMetricPayload {
I think we should store the time unit (and any metadata we need for interpreting the data) in the database, as we do in the [SDK](https://searchfox.org/glean/rev/c0f26c283b1df6f354662ca8388a80e2075e7fbd/glean-core/src/metrics/mod.rs#101,173) and then have one specific function (as done in the SDK) to only get the data as Glean-payload JSON.

2020-12-18 11:42 UTC, Dexterp37 commented on src/metrics/datetime.ts
> +   * @param value Some Data value, with offset, to set the metric to.
```suggestion
   * @param value Some `Date` value, with offset, to set the metric to.
```

2020-12-18 12:24 UTC, brizental commented on src/metrics/time_unit.ts
> +  case TimeUnit.Nanosecond:
> I agree with you we probably don't need it for DateTime, but that's presumably what we'll want for Timespan and TimingDistribution or Event.

Note that this will give us microsecond precision, nanosecond precision, as far as I know, is out of reach in the browser.

2020-12-18 12:27 UTC, brizental commented on src/metrics/time_unit.ts
> +    return "(\\d{4}-([0]\\d|1[0-2])-([0-2]\\d|3[0-1])(T(([0-1]\\d)|([0-2][0-3])))(:[0-5]\\d)(:[0-5]\\d)(\\.\\d{9}))";
I am not sure I get what you mean here. If you mean that we can transform the date string into a Date object by calling `new Date(dateString)`, sadly no. Some of the strings formats Glean supports work, but micro and nanoseconds don't work, minutes and hours also don't. 

`theDate.toISOString` is not in the format Glean expects either.

2020-12-18 12:29 UTC, brizental commented on src/metrics/time_unit.ts
> +function guessTimeUnitPrecision(value: string): TimeUnit {
I thought about this, but wouldn't it be possible for a person to change the time unit of a given metric? That would render previous entries invalid if we always assume the entries are in the time unit of the Metric instance and we probably wouldn;t want to throw away previous entries because of a time unit change? Or is this not possible / we don't care to delte previous entries if the time unit changes?

2020-12-18 12:32 UTC, brizental commented on src/metrics/time_unit.ts
> +export function timeUnitFromString(unit: string): TimeUnit {
We can do [what I did for the Lifetime enum](https://github.com/mozilla/glean.js/blob/main/src/metrics/index.ts#L10-L17) and throw away this function. I had your comment about maybe not using strings to store informatin because that might be a problem performance issue when I made the decision to map the enum to numbers instead of strings. I can change it back to strings though, one less function wouldn't be a bad thing.

2020-12-18 12:43 UTC, brizental commented on src/metrics/time_unit.ts
> +function guessTimeUnitPrecision(value: string): TimeUnit {
Yeah disregard I see the problem with my comment already. If the person changes the time unit, the recorded time unit is still the same... Let me think on this a bit and send a new commit, or come back here with more thoughts.

Please do still let me know about this
> Or is this not possible / we don't care to delete previous entries if the time unit changes?

2020-12-18 13:27 UTC, Dexterp37 commented on src/metrics/time_unit.ts
> +  case TimeUnit.Nanosecond:
Yes, that's correct. We get microsecond resolution [according to our docs](https://developer.mozilla.org/en-US/docs/Web/API/DOMHighResTimeStamp).

2020-12-18 13:32 UTC, Dexterp37 commented on src/metrics/time_unit.ts
> +    return "(\\d{4}-([0]\\d|1[0-2])-([0-2]\\d|3[0-1])(T(([0-1]\\d)|([0-2][0-3])))(:[0-5]\\d)(:[0-5]\\d)(\\.\\d{9}))";
I was thinking of something like this (pseudocode):

```js
case TimeUnit.Hour: {
  let truncated = new Date(original.getTime());
  truncated.setMinute(0);
  truncated.setSecond(0);
  ...
}
```

As for the `theDate.toISOString`, what do you mean it's not in a format Glean expects? The function seems to return [ISO8601](https://mozilla.github.io/glean/book/dev/core/internal/payload.html#datetime) which is the same thing we [claim to send](https://mozilla.github.io/glean/book/dev/core/internal/payload.html#datetime) :)

2020-12-18 13:32 UTC, Dexterp37 commented on src/metrics/time_unit.ts
> +function guessTimeUnitPrecision(value: string): TimeUnit {
I don't have a good answer to this off the top of my head. Can you check what the SDK is doing in this case? I guess the old data gets discarded.

2020-12-18 13:43 UTC, brizental commented on src/metrics/time_unit.ts
> +    return "(\\d{4}-([0]\\d|1[0-2])-([0-2]\\d|3[0-1])(T(([0-1]\\d)|([0-2][0-3])))(:[0-5]\\d)(:[0-5]\\d)(\\.\\d{9}))";
> I was thinking of something like this (pseudocode):

Doing this wouldn't prevent us from doing string manipulation though. The resulting ISO string Javascript generates is always in the milliseconds format even if some of the information is `0`. For reference, this is what `toISOString` output looks like: `"2020-12-18T13:39:34.567Z"`.

> As for the theDate.toISOString, what do you mean it's not in a format Glean expects?

It doesn't include de timezone info for one, it ends with a `Z`. Also it is aways in the `milliseconds` format. As I mention above, we would need to manipulate the resulting string either way.

2020-12-18 13:50 UTC, Dexterp37 commented on src/metrics/time_unit.ts
> +    return "(\\d{4}-([0]\\d|1[0-2])-([0-2]\\d|3[0-1])(T(([0-1]\\d)|([0-2][0-3])))(:[0-5]\\d)(:[0-5]\\d)(\\.\\d{9}))";
Coo, let's ignore this, then! Thanks for looking into it.

2020-12-18 14:03 UTC, brizental commented on src/metrics/time_unit.ts
> +function guessTimeUnitPrecision(value: string): TimeUnit {
On the SDK we store the actual Datetime object. Then we serialize the stored object based on the stored time unit, we don't take into account the time unit of the current instance. We also don't discard anything.

Now that I think about this further, I guess the whole point of recording the datetime **and** the time unit is to be able to serialize it to the correct time unit at the time of recording, thus allowing people to change the time unit without breaking serialization if they want to. Otherwise we could just use the current time unit of the instance to serialize and not persist the time unit at all. Does this make sense?

What I mean is, if we don't want to have to guess the time unit and we also want to allow people to change the time unit if they want to, we must persist the time unit.

2020-12-18 14:45 UTC, brizental commented on src/metrics/time_unit.ts
> +function guessTimeUnitPrecision(value: string): TimeUnit {
> thus allowing people to change the time unit without breaking serialization if they want to

Not that it would break it on the SDKs case... I think it wouldn't break anything, since it stores the whole Datetime object. But the SDK does make a point about serializing to the recorded and not necessarily current time unit. I will file a documentation bug, the expected behaviour for when people change the time unit is not obvious and it is unclear if it is okay or not.

2020-12-18 15:42 UTC, brizental commented
Converting this to a draft because it turns out I have been wrongly assuming that `getISOString` returns the local time, when it actually returns UTC.

2021-01-04 16:49 UTC, brizental commented
Closing this in favour of the much simple (and correct) approach in #20.

2021-01-04 16:49 UTC, closed without merging