Update to glean-parser 8.1 and allow any patch version
mozilla/glean.js pull request #1750
Opened 2023-08-08 09:41 UTC by badboy

I copied the script from https://github.com/mozilla/glean/blob/3c1c083238876dd6cc4e7577c66b73d309ab83d8/gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy#L61

This now uses `~=` for the glean-parser install, so we don't need to update glean.js for every glean_parser patch update.

2023-08-09 13:32 UTC, badboy commented
Probably needs a fix to `bin/update-glean-parser-version.sh` to only set the `MAJOR.MINOR` version correctly.

What to test:

* Does it pick glean_parser 8.1.1 correctly on a clean source?
* Manually install glean_parser 8.1.0 -- does it work?

2023-08-09 14:49 UTC, rosahbruno commented
> Probably needs a fix to `bin/update-glean-parser-version.sh` to only set the `MAJOR.MINOR` version correctly.

It looks like this command only updates two spots
1. `cli.ts` - it will set whatever you pass in. If we run the script with version 8.0, it will set the value of `GLEAN_PARSER_VERSION` to 8.0
2. `qt/requirements.txt` - we are not currently supporting any projects on QT and plan to likely decommission support, so likely not worth extra work there to deal with this

> 
> What to test:
> 
>     * Does it pick glean_parser 8.1.1 correctly on a clean source?
> 
>     * Manually install glean_parser 8.1.0 -- does it work?

I was able to `git clean` my repo and run and it picked up 8.1.1. I then manually pulled in 8.1.0 and it seemed to work correctly too.

2023-08-10 13:55 UTC, rosahbruno approved these changes

2023-08-10 13:57 UTC, rosahbruno requested changes
Actually, before we merge. I think we should update these docs to specify that running this command should only use `<MAJOR>.<MINOR>` now.

https://github.com/mozilla/glean.js/blob/main/docs/guides/update_glean_parser.md?plain=1#L6

2023-08-24 14:47 UTC, merged