create-react-app sample project
mozilla/glean.js pull request #1754
Opened 2023-08-23 04:35 UTC by rosahbruno

This PR creates a new react sample app for Glean.js. This sample project shows how easy it is to integrate Glean.js and instrument an event for a button click.

### Pull Request checklist ###

- [ ] **Quality**: Make sure this PR builds and runs cleanly.
  - Inside the `glean/` folder, run:
    - `npm run test` Runs _all_ tests
    - `npm run lint` Runs _all_ linters
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes a changelog entry to `CHANGELOG.md` or an explanation of why it does not need one
- [ ] **Documentation**: This PR includes documentation changes, an explanation of why it does not need that or a follow-up bug has been filed to do that work
  - Documentation should be added to [The Glean Book](https://mozilla.github.io/glean/book/index.html) when making changes to Glean's user facing API
    - When changes to the Glean Book are necessary, link to the corresponding PR on the [`mozilla/glean`](https://github.com/mozilla/glean) repository
  - Documentation should be added to [the Glean.js developer documentation](https://github.com/mozilla/glean.js/tree/main/docs) when making internal code changes

2023-08-25 17:48 UTC, badboy requested changes

2023-08-25 17:48 UTC, badboy commented on samples/browser/react-sample/public/favicon.ico
this is the default react favicon, do we really need that?

2023-08-25 17:48 UTC, badboy commented on samples/browser/react-sample/public/logo192.png
same here. I don't think it's a good idea to commit the default images here, if only because I don't even know what their license is.

2023-08-25 17:48 UTC, badboy commented on samples/browser/react-sample/public/index.html
> +    <title>Sample React App</title>
Should we personalize this? 
```suggestion
    <title>Glean Sample React App</title>
```

2023-08-25 17:48 UTC, badboy commented on samples/browser/react-sample/public/index.html
> +    <noscript>You need to enable JavaScript to run this app.</noscript>
/o\ (it's fine)

2023-08-25 17:48 UTC, badboy commented on samples/browser/react-sample/public/index.html
> +    -->
Seems like this can go to.
```suggestion
```

2023-08-25 17:48 UTC, badboy commented on samples/browser/react-sample/src/index.js
> +const APP_NAME = 'sample-react-app';
```suggestion
const APP_NAME = 'glean-sample-react-app';
```

maybe?

2023-08-25 17:48 UTC, badboy commented on samples/browser/react-sample/src/index.js
> +reportWebVitals();
What is this? Do we need that in a minimal sample?

2023-10-04 18:15 UTC, rosahbruno commented
@badboy 
Everything you called out previously should be fixed plus a few new things
- Public license headers
- moving init to a custom React hook that would be more useful to devs to see than just init on index.js

2023-10-05 10:57 UTC, badboy approved these changes
One last thing, but otherwise good to go.

2023-10-05 10:57 UTC, badboy commented on samples/browser/react-sample/README.md
> +3. Create the Glean generated files
I wonder if we should call out from what it generates (reason I bring this up: Abhishek's recent report and his struggle to understand the connection between metrics.yaml and the generated code)

Maybe:

```suggestion
3. Generate the metrics API from the bundled `metrics.yaml` file. This will produce JavaScript files in `src/glean/generated`:
```

2023-10-05 17:27 UTC, merged