Bug 1695884 - Put PingType in a standalone file (#)
mozilla/glean.js pull request #183
Opened 2021-04-09 22:41 UTC by ChinYing-Li

This PR aims to fix [bug 1695884](https://bugzilla.mozilla.org/show_bug.cgi?id=1695884).
Any suggestion is appreciated!

2021-04-12 08:37 UTC, brizental requested changes
Hey @ChinYing-Li thank you for your contribution. This is looking great. I left a few comments to be addressed in the code.

2021-04-12 08:37 UTC, brizental commented on CHANGELOG.md
> +* [#183](https://github.com/mozilla/glean.js/pull/183): Put PingType in a standalone file
Not necessary to put this in the CHANGELOG.md file as it is just an internal change.

2021-04-12 08:37 UTC, brizental commented on glean/src/core/internal_pings.ts
> +import PingType from "./pings/pingtype.js";
Let's please use snake_case for file names to keep consistency i.e. `ping_type`.

2021-04-12 08:37 UTC, brizental commented on glean/src/core/pings/index.ts
> +export default CommonPingData;
I know CommonPingData was moved to another file in a previous PR. Would you mind rebasing your PR to include that change? You'll probably get some merge conflicts when you do that.

2021-04-13 08:14 UTC, brizental requested changes

2021-04-13 08:14 UTC, brizental commented on glean/src/core/pings/index.ts
>   * file, You can obtain one at http://mozilla.org/MPL/2.0/. */
since this file doesn't have anything on it anymore, feel free to delete it.

2021-04-15 11:13 UTC, ChinYing-Li commented
@brizental After rebasing, the PR is ready for review. Any suggestion is appreciated!
There's a conflict with `main` since I removed `glean/src/core/pings/index.ts`.

2021-04-15 11:43 UTC, brizental commented
Changes look good, but you need to resolve the conflict before I can merge :)

2021-04-16 06:55 UTC, ChinYing-Li commented
Closing this PR to open a clean one, as I don't have a quick solution to the conflicting index.ts; sorry for the inconvenience caused!

2021-04-16 07:12 UTC, brizental commented
Looks great! Thanks for the hard work in cleaning up your commit history, great job :) Note that you didn't need to close the PR, force pushing would have been enough.

2021-04-16 07:12 UTC, brizental approved these changes

2021-04-16 08:35 UTC, merged