Gleanjs session implementation
mozilla/glean.js pull request #1850
Opened 2023-12-16 00:24 UTC by rosahbruno

Todo
- [ ] PR for schema changes - optional `session_id` & `session_count`
- [ ] Update docs
- [ ] Changelog

### Pull Request checklist ###

- [ ] **Quality**: Make sure this PR builds and runs cleanly.
  - Inside the `glean/` folder, run:
    - `npm run test` Runs _all_ tests
    - `npm run lint` Runs _all_ linters
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes a changelog entry to `CHANGELOG.md` or an explanation of why it does not need one
- [ ] **Documentation**: This PR includes documentation changes, an explanation of why it does not need that or a follow-up bug has been filed to do that work
  - Documentation should be added to [The Glean Book](https://mozilla.github.io/glean/book/index.html) when making changes to Glean's user facing API
    - When changes to the Glean Book are necessary, link to the corresponding PR on the [`mozilla/glean`](https://github.com/mozilla/glean) repository
  - Documentation should be added to [the Glean.js developer documentation](https://github.com/mozilla/glean.js/tree/main/docs) when making internal code changes

2023-12-21 21:32 UTC, chutten requested changes
We're firm on 30mins? Might make testing difficult (btw, where are the tests?) unless we make that parametrized. (in addition to the existing testing difficulties with using `Date`)

2023-12-21 21:32 UTC, chutten commented on glean/src/metrics.yaml
> +    lifetime: user
Innnnteresting. Not `application`? Oh! Right! Because `application` doesn't preserve across navigation, does it?

2023-12-21 21:32 UTC, chutten commented on glean/src/metrics.yaml
> +      A UUID uniquely identifying the client's current session.
Define or link to a definition of what a session is, please.

2023-12-21 21:32 UTC, chutten commented on glean/src/metrics.yaml
> +      A running counter of the number of sessions for this client.
Define or link to a definition of what a session is, please.

2023-12-21 21:32 UTC, chutten commented on glean/src/core/internal_metrics.ts
> +   * 1. If this is the first session, then we set a new session ID and a
```suggestion
   * 1. If this is the first session (there is no existing session ID), then we set a new session ID and a
```

2023-12-21 21:32 UTC, chutten commented on glean/src/core/internal_metrics.ts
> +    this.sessionId.set(generateUUIDv4());
We don't have `generateAndSet()` in gleanjs?

2023-12-21 21:32 UTC, chutten commented on glean/src/core/sessions.ts
> +  const thirtyMinutesAgo = new Date(Date.now() - (60000 * 30));
Thoughts on 

```js
let earlier = new Date();
earlier.setMinutes(earlier.getMinutes() - 30);
```

2024-02-01 21:55 UTC, rosahbruno commented on glean/src/metrics.yaml
> +    lifetime: user
Well this can change depending on the client. On a client where they are using basic HTML or something of that nature, it will initialize every page load. For a single page application, if will not initialize every page load. I think we need to cover as many cases as possible and just make the metric tied to the user lifetime so that we can maintain the value across different initializations.

2024-02-01 21:58 UTC, rosahbruno commented on glean/src/core/internal_metrics.ts
> +   * 1. If this is the first session, then we set a new session ID and a
Fixed in b0c301c4c1fb532c53ae7d6ec5b618222673f024

2024-02-01 21:59 UTC, rosahbruno commented on glean/src/core/internal_metrics.ts
> +    this.sessionId.set(generateUUIDv4());
Ahh, good callout. I will fix this.

2024-02-01 22:06 UTC, rosahbruno commented
> We're firm on 30mins? Might make testing difficult
Based on everything that Abhishek found when researching sessions, it seems like 30 minutes is the standard here. I believe we can make 30 minutes the default.

> (btw, where are the tests?)
Tests are on their way (after I fix the last part)

> unless we make that parametrized. (in addition to the existing testing difficulties with using `Date`)
I agree this should be parameterized. I think 30 will be the default value unless someone provides a different value when initializing Glean. I will make some changes and push that up.

2024-02-02 04:43 UTC, rosahbruno commented on glean/src/core/internal_metrics.ts
> +    this.sessionId.set(generateUUIDv4());
Fixed in https://github.com/mozilla/glean.js/pull/1850/commits/4a183f86f6520e5c951226aca2e7845f2007dc9f

2024-02-02 07:19 UTC, rosahbruno commented on glean/src/core/sessions.ts
> +  const thirtyMinutesAgo = new Date(Date.now() - (60000 * 30));
Fixed in https://github.com/mozilla/glean.js/pull/1850/commits/b30774da1da358c9b7c5b76fcc8acc6678262417

2024-02-07 17:25 UTC, rosahbruno commented on glean/src/metrics.yaml
> +      A UUID uniquely identifying the client's current session.
I've added a more thorough description of what a session is in the metrics.yaml for both metrics.

2024-02-07 19:52 UTC, chutten commented on automation/compat/index.js
> +        elem.innerHTML = "Session IDs updated successfully.";
I know this doesn't matter, but my reflexes are forcing me to ask that this become `innerText`

2024-02-07 19:52 UTC, chutten commented on glean/src/core/config.ts
> +  // Allow the client to explicitly define the length of a session in MINUTES.
"client" is one of those words we define in different ways, but I'm not sure is suitable here. "Embedder", perhaps?

2024-02-07 19:52 UTC, chutten commented on glean/src/core/internal_metrics.ts
> +  readonly sessionCount: CounterMetricType;
...in what way is sessionCount not a session id? Do we even need a session id if we have a session count and a client id?

Also, how does this interact with pings forbidding client_id? Do we forbid session_id as well? (If we don't, we could deanonymize)

2024-02-07 19:52 UTC, chutten commented on glean/src/core/internal_metrics.ts
> +   * the app is initialized and on every read/write to storage.
"on" here meaning "just before" or "just after"?

2024-02-07 19:52 UTC, chutten commented on glean/src/core/internal_metrics.ts
> +   * the app is initialized and on every read/write to storage.
Also: we update `lastActive` on reads as well as writes?

2024-02-07 19:52 UTC, chutten commented on glean/src/core/internal_metrics.ts
> +    }
Remind me: this only happens for SSR?

2024-02-07 19:52 UTC, chutten commented on glean/src/core/internal_metrics.ts
> +    // Set the session new session last active time in LocalStorage.
"Set the session new session last..." huh?

2024-02-07 19:52 UTC, chutten commented on glean/src/metrics.yaml
> +      A running counter of the number of sessions for this client. A session is
We might want to spell out that this is client's lifetime count, it is only reset on opt-out. (Actually, does glean.js wipe `glean_client_info` on opt-out? I think it's supposed to)

2024-02-07 21:04 UTC, rosahbruno commented on glean/src/core/internal_metrics.ts
> +  readonly sessionCount: CounterMetricType;
> ...in what way is sessionCount not a session id? Do we even need a session id if we have a session count and a client id?

The `session_count` is the total number of sessions that this client has had. This gets updated every time that we trigger a new session. GA has a similar `session_number` that they track.

> Also, how does this interact with pings forbidding client_id? Do we forbid session_id as well? (If we don't, we could deanonymize)

This is not something that we have discussed. As a data steward, what are your thoughts here? Should we allow for session information without a client ID? Or should pings with no client ID also have no session info?

2024-02-07 21:09 UTC, rosahbruno commented on glean/src/core/internal_metrics.ts
> +   * the app is initialized and on every read/write to storage.
> "on" here meaning "just before" or "just after"?

It is happening immediately after read/writes. Since everything is running synchronously, this will always execute before we return from the functions. So I don't think "on" is technically incorrect, but I see what you are saying and I can adjust to say "just after".

> Also: we update lastActive on reads as well as writes?

Yes. Basically anytime that something on the screen is being interacted with. We wouldn't trigger a read or a write unless the user was interacting with the page. We don't have the traditional "onpageload" that we can fire in all applications, so this is the most reusable way we can accomplish this.

2024-02-07 21:09 UTC, rosahbruno commented on glean/src/core/config.ts
> +  // Allow the client to explicitly define the length of a session in MINUTES.
Maybe I will just remove it altogether. Say something like "Allow for overriding the default session length of 30 minutes".

2024-02-07 21:11 UTC, rosahbruno commented on glean/src/core/internal_metrics.ts
> +    }
Yes, this is our check to ensure that we aren't trying to do any sort of storage actions on the server side.

2024-02-07 21:16 UTC, rosahbruno commented on glean/src/metrics.yaml
> +      A running counter of the number of sessions for this client. A session is
> We might want to spell out that this is client's lifetime count, it is only reset on opt-out.

Good call, I will update this.

> (Actually, does glean.js wipe glean_client_info on opt-out? I think it's supposed to)

Yes, on opt out all the metrics are cleared from all the local databases (events, pings, metrics).

2024-02-07 21:20 UTC, rosahbruno commented on automation/compat/index.js
> +        elem.innerHTML = "Session IDs updated successfully.";
Easy enough, I will update

2024-02-07 21:44 UTC, rosahbruno commented on glean/src/core/internal_metrics.ts
> +    // Set the session new session last active time in LocalStorage.
Fixed in https://github.com/mozilla/glean.js/pull/1850/commits/9f89f0acf6e11a76be0571df25a3eb92fecaccc1

2024-02-12 17:18 UTC, quiiver approved these changes
:shipit:

2024-02-12 17:32 UTC, quiiver commented
> This is not something that we have discussed. As a data steward, what are your thoughts here? Should we allow for session information without a client ID? Or should pings with no client ID also have no session info?

Probably best to disallow session tracking if client_id is disabled

2024-02-12 19:28 UTC, chutten requested changes
I don't know how easy it'll be, but if we want to support pings without `client_id` we need to ensure we aren't making it trivially obtainable via `session_id`

2024-02-12 19:28 UTC, chutten commented on glean/src/core/internal_metrics.ts
> +  readonly sessionCount: CounterMetricType;
(( The reason I ask about session count is because `client_id` + `session_count` has identical uniqueness semantics to `session_id`, but using less data. It's not a point that needs close interrogation (especially since not all pings have a `client_id` to make a `session_count` useful), but it's a note towards how we might want to think about identifiers. ))

Pings without client_id should also be without session_id. Otherwise it can be trivial to supply a client_id for most pings by joining on session_id.

Or, differently put: Any `session_id` on a ping without a `client_id` must not be linkable to a `session_id` on a ping of any other doctype (with `client_id` or not). (They _can_ have a `session_id`, but it must not be shared with any other ping or else they'll be linkable)

2024-02-13 19:00 UTC, rosahbruno commented
@chutten 
So I just want to make sure I am understanding - a ping sent with no `client_id` should also not include the `session_id` or the `session_count`? I agree with what you've said above, I just want to make sure I understand completely what the ask is before I start making any changes.

2024-02-13 21:28 UTC, chutten commented
> @chutten So I just want to make sure I am understanding - a ping sent with no `client_id` should also not include the `session_id` or the `session_count`? I agree with what you've said above, I just want to make sure I understand completely what the ask is before I start making any changes.

I don't know of a strong reason to exclude `session_count`. Yeah, there's some timing fingerprinting possible, but given the sizes of our populations and the ability for custom ping definitions to limit the precision of the timestamps, I'm not too worried.

But, yes, if there's no `client_id` there should be no `session_id` (as that would trivially permit deriving the `client_id` by looking for a ping where a `client_id` is sent and it shares the same `session_id`).

2024-02-21 16:47 UTC, rosahbruno commented
@chutten 
I've made updates to exclude the `session_id` whenever the ping doesn't include the `client_id`. 

A ping for reference: https://debug-ping-preview.firebaseapp.com/pings/glean-from-website/fa376d6f-f83d-45c6-a697-9fecdcfededf#L18

2024-02-21 17:30 UTC, chutten approved these changes

2024-02-21 17:30 UTC, chutten commented on glean/src/metrics.yaml
> +      new session, the session_id will be updated.
Please update the description to note that this isn't included for pings where `include_client_id` is `false`

2024-02-22 22:23 UTC, merged