Bug 1683846 - Decouple metrics recorded format from expected ping payload format
mozilla/glean.js pull request #19
Opened 2021-01-04 10:40 UTC by brizental

2021-01-04 10:42 UTC, brizental commented on src/metrics/validation.ts
> +/* This Source Code Form is subject to the terms of the Mozilla Public
Cannot put this code in `metrics/index.ts` because it will cause circular import errors.

2021-01-04 14:58 UTC, Dexterp37 commented on src/database.ts
> +function createExternalMetricsPayload(v: MetricsPayload): MetricsPayload {
I don't think I like the idea of having "two payloads" (internal vs external). There's no such thing as "internal payload", it's just metrics data in the end. Payload as a concept only makes sense when it comes to pings.

The internal data should probably just be "storedMetrics" and the payload... well, is the payload .

2021-01-04 15:08 UTC, brizental commented on src/database.ts
> +function createExternalMetricsPayload(v: MetricsPayload): MetricsPayload {
Yeap I agree, names chosen here are terrible. I'll try to think of something better and get back here. Suggestions 100% welcome.

2021-01-04 16:13 UTC, brizental commented on src/database.ts
> +function createExternalMetricsPayload(v: MetricsPayload): MetricsPayload {
I tried something (https://github.com/mozilla/glean.js/pull/19/commits/d2e5ab36cdce913aca29c644c68137949aee9cc4), let me know what you think.

2021-01-07 08:56 UTC, Dexterp37 requested changes

2021-01-07 08:56 UTC, Dexterp37 commented on src/database.ts
> + * Creates an external metrics payload from an internal metrics payload.
This comment needs an update :=)

2021-01-07 08:56 UTC, Dexterp37 commented on src/metrics/index.ts
> + * This format must be the exact same as described in [the Glean schema](https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/master/schemas/glean/glean/glean.1.schema.json).
```suggestion
 * - `InternalRepresentation`: is the format in which this metric will be stored in memory.
 *    This format may contain extra metadata, in order to allow deserializing of this data for testing purposes.
 * - `PayloadRepresentation`: is the format in which this metric will be represented in the ping payload.
 *    This format must be the exact same as described in [the Glean schema](https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/master/schemas/glean/glean/glean.1.schema.json).
```

2021-01-07 09:57 UTC, Dexterp37 approved these changes

2021-01-07 10:12 UTC, merged