Bug 1679381 - Implement the datetime metric type
mozilla/glean.js pull request #20
Opened 2021-01-04 16:48 UTC by brizental

This is built on top of https://github.com/mozilla/glean.js/pull/19 thus it is blocked by it.

I am opening anyways to illustrate how the changes added by https://github.com/mozilla/glean.js/pull/19 can be used in a more complex way than the cases in https://github.com/mozilla/glean.js/pull/19 itself.

The commit that matters here is fb5c0e8. All the other are part of #19.

2021-01-04 16:50 UTC, brizental commented on src/metrics/datetime.ts
> +    return this._inner.timeUnit as TimeUnit;
No need for this casting here... This is leftover from development.

2021-01-04 16:51 UTC, brizental commented on src/metrics/datetime.ts
> +    const timezoneVerification = "timezone" in v && isNumber(v.timezone);
Unsure if I should go further and check that timezone is a possible timezone value e.g. between -12 * 60 and 14 * 60.

2021-01-04 16:52 UTC, brizental commented on src/metrics/datetime.ts
> +  payload(): string {
This function turned out being the uglyest... I am sorry and open for suggestions on how to make it nicer :)

2021-01-04 16:52 UTC, brizental commented on src/metrics/datetime.ts
> + *  A boolean metric.
Ops, forgot to update comment.

2021-01-04 16:56 UTC, brizental commented on src/metrics/datetime.ts
> +  async testGetValue(ping: string): Promise<Date | undefined> {
On the Glean SDK we zero out information that is too precise for the current time unit (see: https://github.com/mozilla/glean/blob/main/glean-core/src/metrics/datetime.rs#L161). I am not doing it here, seemed like superfluous work for testing APIs. Do you have issues with this choice?

2021-01-07 10:47 UTC, Dexterp37 requested changes

2021-01-07 10:47 UTC, Dexterp37 commented on src/metrics/datetime.ts
> +    const timezoneVerification = "timezone" in v && isNumber(v.timezone);
Mh, no, let's not for now. In the future, it might be worth reporting an error.

2021-01-07 10:47 UTC, Dexterp37 commented on src/metrics/datetime.ts
> +    const year = this.date.getFullYear().toString().padStart(2, "0");
Another option for all these date/time manipulation insanities would be to use [`toLocaleDateString`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString) and provide `en-US` as the locale (since that's the one we stick to). Did you try that out already?

2021-01-07 10:47 UTC, Dexterp37 commented on src/metrics/datetime.ts
> +   */
Can you please mention the same things we mention in the [other bindings](https://searchfox.org/glean/rev/58fa076222be375a4e5f46baa6275043721603c0/glean-core/android/src/main/java/mozilla/telemetry/glean/private/DatetimeMetricType.kt#54-58) for all the docstrings ?

2021-01-07 10:47 UTC, Dexterp37 commented on src/metrics/datetime.ts
> +    const metric =  new DatetimeMetric({
```suggestion
    const metric = new DatetimeMetric({
```

Does eslint support a rule to detect "double spacing"?

2021-01-07 10:47 UTC, Dexterp37 commented on src/metrics/datetime.ts
> +  async testGetValue(ping: string): Promise<Date | undefined> {
This makes writing tests using this impossible/harder :-) We can't check if a date we set is then returned properly, after truncation.

Don't we have a test specifically for testing this, in the SDK?

2021-01-07 10:47 UTC, Dexterp37 commented on src/metrics/time_unit.ts
> +  // Truncate to nanosecond precision.
This does not represent a truncation, necessarily! See https://searchfox.org/glean/source/glean-core/android/src/main/java/mozilla/telemetry/glean/private/TimeUnit.kt :-)

2021-01-07 10:47 UTC, Dexterp37 commented on src/metrics/datetime.ts
> +  async testGetValue(ping: string): Promise<Date | undefined> {
Oh yes, we do: https://searchfox.org/glean/source/glean-core/tests/datetime.rs

2021-01-07 10:47 UTC, Dexterp37 commented on tests/metrics/datetime.spec.ts
> +describe("DatetimeMetric", function() {
Can you kindly port over the tests from glean-core, too? https://searchfox.org/glean/source/glean-core/tests/datetime.rs

Don't forget that in the SDK they are split between the bindings and the core, but here everything is together so tests can be together too.

2021-01-07 10:55 UTC, brizental commented on src/metrics/datetime.ts
> +  async testGetValue(ping: string): Promise<Date | undefined> {
Truncating in Glean.js happens when we call the `payload` function on a concrete Datetime metric. I added tests for each one of the time units truncations. This specific function returns a Date object, no truncation happens here.

2021-01-07 10:57 UTC, brizental commented on tests/metrics/datetime.spec.ts
> +describe("DatetimeMetric", function() {
I based myself off of these tests. Which one do you see missing? I did not check the bindings tests though, will do that too.

2021-01-07 10:57 UTC, brizental commented on src/metrics/datetime.ts
> +    const year = this.date.getFullYear().toString().padStart(2, "0");
toLocalteDateString does not return an ISO string.

2021-01-07 13:25 UTC, brizental commented on tests/metrics/datetime.spec.ts
> +describe("DatetimeMetric", function() {
I checked bidnings tests and added some extra date cases (prior to UNIX epoch  and date after 2038), other than that I did not see any other missing test cases.

2021-01-07 13:33 UTC, Dexterp37 commented on src/metrics/datetime.ts
> +    const year = this.date.getFullYear().toString().padStart(2, "0");
Isn't it easier to convert it to that format starting from what toLocaleDateString gives? Alternatively, we could also try to just use `Date().toISOString()` and split/crop. Otherwise, we can leave it as it is.

2021-01-07 13:38 UTC, Dexterp37 commented on tests/metrics/datetime.spec.ts
> +      assert.deepStrictEqual(snapshot, {
This tests something a bit different than [this test](https://searchfox.org/glean/source/glean-core/tests/datetime.rs#110). You're testing the snapshot, which ideally users won't have access to. Users will have to use the testing APIs, which currently do not truncate.

2021-01-07 13:45 UTC, brizental commented on tests/metrics/datetime.spec.ts
> +      assert.deepStrictEqual(snapshot, {
`testGetValueAsString` does truncate because it returns `DatetimeMetric.payload`, only when we get it as a Date object it doesn't truncate. This means that, if the metric is `TimeUnit.Hours` the `Date` object returned by `testGetValue` may come with minute, seconds and etc not zeroed out. Do you think that is a problem?

About this specific test, I can change to do exactly what the SDK does.

2021-01-07 13:47 UTC, Dexterp37 commented on tests/metrics/datetime.spec.ts
> +      assert.deepStrictEqual(snapshot, {
Yes, I think this is a problem (sorry, that's what I was trying to say). Using the testing API returns a different result than what user would expect.

As for the tests, in general I'd recommend sticking to the same tests we have for the SDK, to make sure we're not introducing problems in the tests.

2021-01-07 14:06 UTC, brizental commented on src/metrics/datetime.ts
> +    const year = this.date.getFullYear().toString().padStart(2, "0");
So, the issue with toISOString is that it always returns a string in UTC, so we lose timezone information. It also wouldn't be easier to split by toLocaleDateString, IMO, but even if it were, it doesn't contain all the information that we can get directly from the date object, such as timezone information.

I did spot a bug here, if the user changes timezones from the moment they recorded the metric to the moment they access the metrics payload, we create an incorrect string... I will fix this in my next commit.

2021-01-07 16:44 UTC, brizental commented on src/metrics/datetime.ts
> +    const year = this.date.getFullYear().toString().padStart(2, "0");
Fixed it https://github.com/mozilla/glean.js/pull/20/commits/065f63f01a05faeacbfbb05c6a262f66a25aaddf.

2021-01-07 16:45 UTC, brizental commented on src/metrics/datetime.ts
> +  async testGetValue(ping: string): Promise<Date | undefined> {
I now zero out everything that is too precise at the time of recording: https://github.com/mozilla/glean.js/pull/20/commits/11d9387b95a7356a55f06b0283e83743b2e2d2af

2021-01-07 17:34 UTC, Dexterp37 approved these changes

2021-01-08 08:48 UTC, merged