Bug 1701889 - Implement the ping testing api
mozilla/glean.js pull request #202
Opened 2021-04-14 06:00 UTC by Dexterp37

This implements the pings testing API, as discussed and designed in the related bug.

2021-04-14 13:01 UTC, brizental requested changes
I am ok with the overall approach. I don't see any other way to implement this feature either. I'll move Bug 1682771 to P2 though. Disallowing test APIs outside of tests seems even more important with this feature.

2021-04-14 13:01 UTC, brizental commented on glean/src/core/pings/index.ts
> +  async testBeforeNextSubmit(validatorFn: ValidatorFunction): Promise<void> {
Shouldn't it instead return `testValidatorPromise`?

2021-04-14 14:32 UTC, brizental commented on glean/src/core/pings/index.ts
> +  async testBeforeNextSubmit(validatorFn: ValidatorFunction): Promise<void> {
Argh, I get why it returns this promise now.

2021-04-14 17:01 UTC, Dexterp37 commented on glean/src/core/pings/index.ts
> +  private testResolutionFunction?: (value: void | PromiseLike<void>) => void;
This is used to resolve the promise returned by `testBeforeNextSubmit`. Without this, we'd have no way to resolve it.

2021-04-14 18:09 UTC, Dexterp37 commented on glean/src/core/pings/index.ts
> +  private testValidatorPromise: Promise<void>;
Mh, what's wrong with the use of validator here? I wanted to make sure the intent was clear. Callback, IMHO, might be a bit misleading: it may give the impression that callback could be used to wait on the submission, while it's really useful exclusively for validating.

2021-04-14 18:11 UTC, Dexterp37 commented on glean/src/core/pings/index.ts
> +    // will always resolve due to the use of `finally`.
Note to self: update the comment to remove the mention to finally.

2021-04-15 08:53 UTC, brizental requested changes
Will continue on the tests I was doing yesterday, my concerns still remain. I explained what are these concerns on the comment I left on the tests code.

2021-04-15 08:53 UTC, brizental commented on glean/src/core/pings/index.ts
> +          this.internalSubmit(reason, rejecter);
Do we want to submit even if the validator got an error? This is testing code, it is better to raise an exception if a test error happened, otherwise output is misleading i.e. it looks like the tests passed when there are actually error logs around (encountered this confusing scenario many times yesterday when testing this PR).

2021-04-15 08:53 UTC, brizental commented on glean/src/core/pings/index.ts
> +      console.error(`There is an existing test call for ping "${this.name}": ignoring.`);
```suggestion
      console.error(`There is an existing test call for ping "${this.name}". Ignoring.`);
```

Just to keep consistency with other messages around the code.

2021-04-15 08:53 UTC, brizental commented on glean/tests/core/pings/index.spec.ts
> +  it("runs a validator: sorry", async function() {
LOL

2021-04-15 08:53 UTC, brizental commented on glean/tests/core/pings/index.spec.ts
> +      assert.strictEqual(value, 100);
Note: the fact that this assertion passes is the issue. Not sure it did pass, because we currently raise an error when Validators reject, but if it did, it shouldn't.

We record to the counter _after_ the next submit, so `value` should be `undefined` when this assertion is executed. From my tests yesterday I did not reach a conclusion as to whether that was indeed the case, I'll do more testing after this review.

From how I understand this code works, there is no way to guarantee this will be executed before the `counter.add` calls below, unless we `await p` before going into the `counter.add` loop.

2021-04-15 09:59 UTC, Dexterp37 commented on glean/src/core/pings/index.ts
> +          this.internalSubmit(reason, rejecter);
Yes, I think we should submit the ping regardless. I'd rather not change the code too much, we should keep this as close as production as possible, with the only exception that some test code runs before the submission.

The code already rejects/throws (exceptions will cause rejections anyway): see the related test.

2021-04-15 10:42 UTC, Dexterp37 commented on glean/tests/core/pings/index.spec.ts
> +      assert.strictEqual(value, 100);
> 
> 
> Note: the fact that this assertion passes is the issue. Not sure it did pass, because we currently don't raise an error when Validators reject, but if it did, it shouldn't.

Then the test is probably wrong, because if the validator throws, the promise is rejected. See `"runs a validator that rejects"`.

> From how I understand this code works, there is no way to guarantee this will be executed before the `counter.add` calls below, unless we `await p` before going into the `counter.add` loop.

Yes, exactly.

2021-04-15 12:27 UTC, Dexterp37 commented
Ad discussed with @brizental , sadly we have no way to guarantee that metric calls executed after `testBeforeNextSubmit` get executed before the ping collection. This is due to the fact that the Glean.js dispatcher is asynchronous even in test mode (it's not in the other bindings). One way to make this happen would be to change the dispatcher to add "task dependencies", e.g. if task A has a dependency B, run B _right before_ running A.

Sadly, that's a bigger change. I'm closing this PR.

2021-04-15 17:36 UTC, Dexterp37 commented
Let's give this another opportunity.

2021-04-26 09:36 UTC, brizental commented on glean/src/core/dispatcher.ts
> +        const originalFunc = this.testLaunch;
There is an assumption here that only `testLaunch` will be called inside a `TestUnnestTask`, but there are no guarantees around it. I don't think it is unlikely that `launch` calls will also be inside `testBeforeNextSubmit`, so they should be monkeypatched too?

Did you consider monkeypatching Glean's whole dispatcher instead and then waiting for the temp dispatcher's queue to be emptied before leaving this block?

2021-04-26 09:36 UTC, brizental commented on glean/src/core/dispatcher.ts
> +        const originalFunc = this.testLaunch;
Relying on global state is what bothers me here though. If we have this scenario, would this break?

```js
const p = ping.testBeforeNextSubmit(async () => {
     assert.strictEqual(await counter.testGetValue(), 10);
});
ping.submit();
// Here testGetValue could be the monkey patched value, no?
assert.ok(await someOtherMetric.testGetValue());
await p;
```

2021-04-27 09:09 UTC, brizental commented on glean/src/core/pings/ping_type.ts
> +  private internalSubmit(reason?: string, testResolver?: PromiseCallback): void {
The `private` keywork is ignored by Javascript and even in Typescript it's very easy to bypass. Let's make this a static method l[ike on the MetricTypes that have an undispatched method](https://github.com/mozilla/glean.js/blob/main/glean/src/core/metrics/types/counter.ts#L35). So it doesn't show up on code completion for folks.

2021-04-27 09:10 UTC, brizental commented on glean/src/core/pings/ping_type.ts
> +    // will always resolve due to the use of `finally`.
This comment is outdated.

2021-04-27 09:15 UTC, brizental commented on glean/src/core/pings/ping_type.ts
> +          // after the calling promise is resolved.
This comment is a bit confusing, IMHO. The code itself is clear enough in this specific part I would say we can drop the comment.

2021-04-27 09:19 UTC, brizental commented on glean/src/core/pings/ping_type.ts
> +      // if tests run fast.
Again, I think this comment is a bit confusing and the code speaks for itself.

2021-04-27 09:28 UTC, brizental commented on glean/tests/core/pings/index.spec.ts
> +    assert.notStrictEqual(ping["testValidator"], undefined);
There is no guarantee that these values were not cleaned up before we got here. This _could_ create intermittents. No strong opinions on removing it or not, because most of the time it _should_ pass. If we leave it we should also check for `rejectTestPromiseFunction`, for consistency. Same for `undefined` checks above.

2021-04-27 09:32 UTC, brizental commented on glean/src/core/pings/ping_type.ts
> +          // after the calling promise is resolved.
Okay, looking at the tests code, if the API is used correctly i.e. aways `await` on the promise returned by `testBeforeNextSubmit` before doing anything else, people should never get the sort of issue this behaviour is trying to solve... We could clean up inside `internalSubmit` and remove some extra lines from this file.

2021-04-27 09:38 UTC, brizental commented on glean/tests/core/pings/index.spec.ts
> +    assert.strictEqual(ping["testValidator"], testFunction);
The behaviour here is not guaranteed. If somehow everything happens super fast, this could cause intermittents. If you do the `cleanup` inside `internalSubmit`, you could stop the dispatcher for this test. With the dispatcher stopped `cleanup` is guaranteed not to happen and this test is more predictable.

2021-04-27 09:42 UTC, brizental commented on glean/tests/core/pings/index.spec.ts
> +      await new Promise(r => setTimeout(r, 100));
Maybe leave a little comment stating why the timeout is necessary here. Without the timeout what happens is even more unpredictable.

2021-04-27 09:44 UTC, brizental commented on glean/tests/core/pings/index.spec.ts
> +      assert.strictEqual(value, undefined);
Also, a small comment stating why the expected value is `undefined`.

2021-04-27 09:45 UTC, brizental commented on glean/tests/core/pings/index.spec.ts
> +      assert.strictEqual(await counter.testGetValue(), 37, "Canary must match");
`"Canary must match"` but the test is for `counter`.

2021-04-27 09:46 UTC, brizental commented on glean/tests/core/pings/index.spec.ts
> +    const canary = new CounterMetricType({
Can we give these two counter more distinctive names? I was bit by the similarities when I was meddling with this test.

2021-04-27 11:08 UTC, Dexterp37 commented on glean/src/core/pings/ping_type.ts
> +  private internalSubmit(reason?: string, testResolver?: PromiseCallback): void {
I retained the keyword and additionally used static as you suggested.

2021-04-27 11:09 UTC, Dexterp37 commented on glean/src/core/pings/ping_type.ts
> +          // after the calling promise is resolved.
Removing this caused intermittents :(

2021-04-27 11:30 UTC, Dexterp37 commented on glean/tests/core/pings/index.spec.ts
> +    assert.notStrictEqual(ping["testValidator"], undefined);
Good catch for the missing asserts, I added them.

With respect to the interkittenity of this, I'm not entirely sure. Our [docs report](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function#description):

> The body of an async function can be thought of as being split by zero or more await expressions. Top-level code, up to and including the first await expression (if there is one), is run synchronously. In this way, an async function without an await expression will run synchronously. If there is an await expression inside the function body, however, the async function will always complete asynchronously.

Since `testBeforeNextSubmit` has no `await`, it should be executed synchronously. The same reasoning should apply to the executor part of the Promise, since it does not contain any await or asynchronous operation.

Does it make sense? Did you see this intermittently failing locally?

2021-04-27 12:05 UTC, brizental commented on glean/src/core/pings/ping_type.ts
> +          // after the calling promise is resolved.
Hm, that means I understand _something_ wrong from this code. Would you mind sharing what failed?

2021-04-27 12:18 UTC, brizental commented on glean/tests/core/pings/index.spec.ts
> +    assert.notStrictEqual(ping["testValidator"], undefined);
Interesting, TIL! I assumed because the whole body of the `async` function is wrapped inside a promise it was not guaranteed to be run sync unless `await`ed on.

Either way my concerns have no ground, I was wrong :) You make these checks before calling `ping.submit` so this is guaranteed to be true. Sorry for the false interkitten alarm.

2021-04-27 12:19 UTC, Dexterp37 commented on glean/tests/core/pings/index.spec.ts
> +    assert.strictEqual(ping["testValidator"], testFunction);
I think the same rationale of my previous comment should apply here, too.

2021-04-27 12:19 UTC, brizental commented on glean/tests/core/pings/index.spec.ts
> +    assert.strictEqual(ping["testValidator"], testFunction);
And once again I am wrong here. `testBeforeNextSubmit` does not trigger submission!

2021-04-27 14:17 UTC, brizental approved these changes
r+wc

2021-04-27 14:17 UTC, brizental commented on glean/src/core/pings/ping_type.ts
> +      // if tests run fast.
Still think this comment is not necessary... But also wrong now? Specifically

```
// [...] this is
// needed to make sure calling the testing APIs on metrics behave consistently
// if tests run fast.
```

2021-04-27 14:17 UTC, brizental commented on glean/src/core/pings/ping_type.ts
> +   *                   the ping content.
nit: Align the second line with `callbackFn`.

2021-04-27 14:17 UTC, brizental commented on glean/tests/core/pings/index.spec.ts
>      const storedPings = await Context.pingsDatabase["store"]._getWholeStore();
nit: can you rename this file to `ping_type.spec.ts` since we are here?

2021-04-27 14:29 UTC, merged