Bug 1677445 - Implement PingType and ping maker
mozilla/glean.js pull request #22
Opened 2021-01-11 14:22 UTC by brizental

This Pr turned out to be bigger than I expected, there are many things interconnected. I tried to make it as lean as possible, but I can also break if off into two Prs, one for the pings database and another that relies on that for ping type and ping maker. Please let me know if you would like me to do that.

In Glean.js we can't just save pings in files, so I created the concept of a pings database, which is an abstraction over the underlying storage just like the metrics database.

2021-01-11 14:23 UTC, brizental commented on src/utils.ts
> +export function sanitizeApplicationId(applicationId: string): string {
Just realized I forgot to bring tests for this function over from glean-core... Will add them in a subsequent commit.

2021-01-11 14:24 UTC, brizental commented on src/utils.ts
> +export function sanitizeApplicationId(applicationId: string): string {
Actually, this commit doesn't fit into this PR. I'll remove it altogether.

2021-01-11 14:29 UTC, brizental commented on src/constants.ts
> +const { version } = require("../package.json");
Not totally sure why `import` doesn't work for `.json` files, TBH.

2021-01-11 15:17 UTC, brizental commented on src/utils.ts
> +export function sanitizeApplicationId(applicationId: string): string {
AAAA Yes it was necessary, for the `makePath` function.

2021-01-12 13:30 UTC, Dexterp37 requested changes
This looks good overall. I have no major concern, but I'd like to take another look after the following changes are discussed/resolved!

2021-01-12 13:30 UTC, Dexterp37 commented on src/utils.ts
> +  }
```suggestion
  return applicationId.replace(/[^A-Za-z0-9]/g, "-");
```

Wouldn't this work the same way?

2021-01-12 13:36 UTC, brizental commented on src/utils.ts
> +  }
Not really because we skip when there is more than one alphanumeric in a row, so `bea@@@rizental` is transformed into `bea-rizental` instead of `bea---rizental`. Also you want `replaceAll` instead. This `return applicationId.replaceAll(/[a-z0-9]+/i, "-");` may work. I'll make the change :)

2021-01-12 13:37 UTC, brizental commented on src/pings/maker.ts
> +export async function getPingHeaders(): Promise<PingHeaders | undefined> {
I prefer returning undefined if there are no headers because then it is a falsy value. `{}` is truthy.

2021-01-12 13:42 UTC, brizental commented on src/pings/database.ts
> +class PingsDatabase {
I prefer them to be separate yes. The ping maker file is loaded already and although they are related they do different things. PingMaker builds pings, PingsDatabase manages ping storage.

2021-01-12 13:43 UTC, brizental commented on src/pings/maker.ts
> +
Yes, I ran into these sort of discussions myself. I preferred to put this here because it only really matters here and there is no reason need to leave it in the Glean object, at least not for now. 

There are limitations on glean-core's database because the Glean singleton is not available everywhere in that codebase, that we don't have here. There are many things centralized in the Glean object there that don't necessarily need to be here. 

I'd prefer spreading code around so that it is bundled only where it really matters, than having a giant `glean.js` file.

2021-01-12 13:43 UTC, brizental commented on src/glean.ts
> +  private _applicationId?: string;
Yeah, the next PR already adds a bit to this Configuration. we can maybe move it there.

2021-01-12 13:44 UTC, Dexterp37 commented on src/pings/maker.ts
> +
> I'd prefer spreading code around so that it is bundled only where it really matters, than having a giant `glean.js` file.

What do you mean? Do we actually exclude this block of code in some build configuration?

2021-01-12 13:45 UTC, brizental commented on src/glean.ts
> +  applicationId: string,
It's part of the Configuration object (https://github.com/mozilla/glean/blob/main/glean-core/src/lib.rs#L118-L131), which is passed to `initialize` (https://github.com/mozilla/glean/blob/main/glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt#L131). I copied this behaviour.

2021-01-12 13:46 UTC, brizental commented on src/glean.ts
> +interface Configuration {
Same thing I said here: https://github.com/mozilla/glean.js/pull/22#discussion_r555778595 :)

2021-01-12 13:47 UTC, brizental commented on src/constants.ts
> +const { version } = require("../package.json");
Aha, very nice! I should have looked at this myself now that I think about it, thanks for doing it anyways 💯

2021-01-12 13:48 UTC, Dexterp37 commented on src/glean.ts
> +  applicationId: string,
Yeah, but that behaviour doesn't apply in this case. In Kotlin and Swift we automatically detect the application id, that's why it's not passed through the API. The configuration object [does not contain the app id](https://github.com/mozilla/glean/blob/676c3fe53b26105acd40c5158143556d356cfa13/glean-core/android/src/main/java/mozilla/telemetry/glean/config/Configuration.kt#L69), because we get that from the app context, which we provide in `initialize`. In Python, C# and RLB, since we can't infer the app id (like here), we pass that via `initialize`.

2021-01-12 13:50 UTC, brizental commented on src/utils.ts
> +  }
`return applicationId.replace(/[a-z0-9]+/gi, "-");` worked :) `replaceAll` is not available for our target, but that is fine you were right, the `g` flag does the trick.

2021-01-12 14:02 UTC, brizental commented on src/glean.ts
> +  applicationId: string,
Argh, I see. I didn't realize Configuration meant something different in the bindings. I'll change this.

2021-01-12 14:08 UTC, brizental commented on src/pings/maker.ts
> +
Bundled in the sense of "lives together in the same file". This is just for code organization sake, no real difference of the final bundle structure.

2021-01-12 14:09 UTC, brizental commented on src/glean.ts
> +  applicationId: string,
This means we don't even need the Configuration structure right now :)

2021-01-12 14:27 UTC, brizental commented on src/constants.ts
> +const { version } = require("../package.json");
Hm, this is a bit annoying because it's webpack that adds this variable but then mocha can't run the tests because it is not using webpack... Turns I can actually use `import` for this information. No idea why I thought I couldn't, probably had an unrelated error and thought that was it.

2021-01-12 15:50 UTC, Dexterp37 commented on src/pings/maker.ts
> +
I see. The point I'm trying to make is that the more we keep the structure similar to the SDK, the easier it is for others to follow up in case we need more hands on this ;) But really up to you.

2021-01-12 15:51 UTC, Dexterp37 approved these changes
r+wc

2021-01-12 15:59 UTC, brizental commented on src/pings/maker.ts
> +
For this specific case I don't see a point in leaving that function on the Glean object. This is a completely valid discussion though, I'll make sure to flag when I make decisions that differ from glean-core's structure in the future so we can look at them closely.

2021-01-12 15:59 UTC, merged