Bug 1677440 - Implement a ping uploader
mozilla/glean.js pull request #24
Opened 2021-01-15 14:22 UTC by brizental

Note that there are no _actual_ uploading tests in this PR. I thought it was big enough as it is. 

Will write the remaning tests, anologous to these ones (https://github.com/mozilla/glean/blob/main/glean-core/android/src/test/java/mozilla/telemetry/glean/net/HttpURLConnectionUploaderTest.kt) while this review is going on.

2021-01-15 14:27 UTC, brizental commented on src/config.ts
> +  readonly serverEndpoint: URL
Hm, this should be optional.

2021-01-15 14:27 UTC, brizental commented on src/glean.ts
> +    // Stop ongoing upload jobs.
This comment is wrong. Should be "Stop ongoing jobs and clear pending pings queue".

2021-01-15 14:27 UTC, brizental commented on tests/upload.spec.ts
> +  // so that it doesn't interfere with this test.
This comment is unnecessary.

2021-01-15 15:28 UTC, Dexterp37 requested changes

2021-01-15 15:28 UTC, Dexterp37 commented on src/upload/adapter/index.ts
> +  post(url: URL, options: {
Do you expect this to have more than headers and body? Does an `options` object really buy us much?

2021-01-15 15:28 UTC, Dexterp37 commented on src/upload/adapter/index.ts
> +};
Can we do this in test files?

2021-01-15 15:28 UTC, Dexterp37 commented on src/upload/index.ts
> +      "X-Client-Type": "Glean.js",
You should check with @fbertsch if we're doing any special magic on this header when ingesting.

2021-01-15 15:28 UTC, Dexterp37 commented on src/upload/index.ts
> +    }
That's an interesting pattern :-) Do we really need a "fake switch" here? It's really 2-3 ifs. We can probably get away by checking `if (!status)` at the beginning and returning accordingly. Then checking the values.

Why wouldn't we have a `status` anyway?

2021-01-15 15:28 UTC, Dexterp37 commented on src/upload/index.ts
> +    await this.currentJob;
If this throws then the status remains stuck to `PingUploaderStatus.Uploading`, right? We should probably catch any error here, if we want to safely transition the states.

2021-01-15 15:28 UTC, Dexterp37 commented on src/upload/index.ts
> +}
Any specific reason why we're moving away from the status names (DONE, WAIT, UPLOAD) from glean-core?

2021-01-15 15:28 UTC, Dexterp37 commented on src/config.ts
> +interface Configuration {
Will you file a bug for allowing custom uploaders?

2021-01-15 15:32 UTC, brizental commented on src/upload/adapter/index.ts
> +};
Not really. We need a default export from this index file for tests to work. I've done this for all modules that have platform specific implementation. Webpack is the one that knows about the platform specific implementation, mocha just expects that the index file will have a default export.

2021-01-15 15:33 UTC, brizental commented on src/upload/adapter/index.ts
> +  post(url: URL, options: {
Nope, this signature is compatible with the fetch API for no strong reason. I can change it.

2021-01-15 15:34 UTC, brizental commented on src/upload/index.ts
> +      "X-Client-Type": "Glean.js",
Good point, I actually copied these from the POC. Asked on Riot.

2021-01-15 15:37 UTC, brizental commented on src/upload/index.ts
> +    }
> Why wouldn't we have a status anyway?

This is a question I plan to answer on my next PR, when I implement a real upload adapter for the browser. For now not sure, but I am thinking if no internet connection or timeout will result in `undefined` status. (will we even have timeout? fetch API doesnj't have IIRC).

> That's an interesting pattern :-) Do we really need a "fake switch" here?

Yeah this the trick to have conditios on each switch clause for Javascript. Honestly, really only used a switch here because that is what we do in glean-core. I can change, the main argument for not changing would be the fact that the function would look much different than the glean-core function. But who really cares? The module is already pretty different anyways.

2021-01-15 15:38 UTC, brizental commented on src/upload/index.ts
> +    await this.currentJob;
Good point. I can't think of a situation where `triggerUploadInternal` could throw, but I am sure it can, heh.

2021-01-15 15:43 UTC, brizental commented on src/upload/index.ts
> +}
These enums are not the same. This enum is about the status of the Glean.js PingUploader, whether or not an uploading job is happening right now. The enum in glean-core is an uploading task for a language binding, whether it should come back later, upload a new request or be done.

I would say it is even better that the names are not same, so as not to cause confusion.

Honestly, I should probably file a follow up to document how this uploader works, like we do for glean-core (https://mozilla.github.io/glean/book/dev/core/internal/upload.html). The uploaders are similar but their inner workings are different. There are enough similarities and differences to be super confusing.

2021-01-15 15:44 UTC, brizental commented on src/config.ts
> +interface Configuration {
Yes, this configuration is not in any way complete.

2021-01-18 10:18 UTC, Dexterp37 commented on src/upload/index.ts
> +}
Yes, it seems like a good idea.

2021-01-18 10:18 UTC, Dexterp37 approved these changes

2021-01-18 13:16 UTC, brizental commented on src/upload/index.ts
> +}
https://bugzilla.mozilla.org/show_bug.cgi?id=1687288

2021-01-18 13:16 UTC, brizental commented on src/config.ts
> +interface Configuration {
https://bugzilla.mozilla.org/show_bug.cgi?id=1687287

2021-01-18 13:17 UTC, merged