Bug 1694770 - Implement the timespan metric type
mozilla/glean.js pull request #253
Opened 2021-04-26 14:24 UTC by brizental

2021-04-27 08:02 UTC, Dexterp37 requested changes
Looks good overall, there's a few nits and a CHANGELOG entry should be added as well. Does the glean_parser already produce valid code to use this?

2021-04-27 08:28 UTC, brizental commented on glean/src/core/utils.ts
> +  return typeof performance === "undefined" ? Date.now() : performance.now();
No we can't. That was actually a bug in this code. If a variable hasn't even been _declared_ you can't pass it as an argument for a function.  `isUndefined` is useful for checking if something that has been declared has not been defined yet, I'd rather we use that instead of `typeof` wherever possible.

I can augment it's doccomment to state that, though.

2021-04-27 08:29 UTC, brizental commented on glean/src/core/metrics/types/timespan.ts
> +    this.startTime = undefined;
Oh yeah, great great catch. Tests should have caught this too, btw. I'll figure something out.

2021-04-27 08:37 UTC, Dexterp37 commented on glean/src/core/utils.ts
> +  return typeof performance === "undefined" ? Date.now() : performance.now();
Good catch, please do :) Would you kindly check for other usages of that function, too?

2021-04-27 08:39 UTC, Dexterp37 commented on glean/src/core/metrics/types/timespan.ts
> +    this.startTime = undefined;
Oh yeah, that kind of bothered me too :\

2021-04-27 14:22 UTC, brizental commented
> Does the glean_parser already produce valid code to use this?

Yes, we were only missing labeled. Unless we introduce a metric type that the Glean SDK does not also support, we are good.

2021-04-27 14:38 UTC, brizental commented on glean/src/core/utils.ts
> +  return typeof performance === "undefined" ? Date.now() : performance.now();
Just checked, all good. The only other place we check for existing APIs in the current environment is in the WebExt sotrage impl, but that is checking like here.

2021-04-28 05:12 UTC, Dexterp37 approved these changes
r+

2021-04-28 05:12 UTC, Dexterp37 commented on glean/src/core/metrics/types/timespan.ts
> +    Context.dispatcher.launch(() => {
Why wasn't this failing our tests? did you end up finding out?

2021-04-28 08:22 UTC, brizental commented on glean/src/core/metrics/types/timespan.ts
> +    Context.dispatcher.launch(() => {
Dispatched or not, start and cancel when called in sequence seem to run one after the other. Probably because neither have any actual `await` inside. I tried to make the tests fail, but they never did. One when I launch some setTimeout's in between do they fail, but I did not commit such a test because I thought it would be confusing.

2021-04-28 11:32 UTC, merged