Bug 1701203 - Declare a minimum node version in the package.json
mozilla/glean.js pull request #260
Opened 2021-04-27 23:15 UTC by AmrDhaliwal

Fixed the bug that required a minimum node version by adding the engine field to package.json.

2021-04-28 08:38 UTC, Dexterp37 commented
Hey @AmrDhaliwal , thank you for your PR and welcome!

This PR is currently failing our CI tests. Would you kindly check why that's happening? You can also run some tests locally with `npm run test:core`.

2021-04-28 09:03 UTC, AmrDhaliwal reviewed
Removed an extra comma from line 103 in package.json in glean that was causing errors.

2021-04-28 09:05 UTC, AmrDhaliwal commented
Hi @Dexterp37,

It seems there was an extra comma that was causing the problems.
But, I removed it and all the tests are now passing!

2021-04-28 13:34 UTC, Dexterp37 requested changes
Thanks for making the tests pass! I have one additional small request.

2021-04-28 13:34 UTC, Dexterp37 commented on glean/package.json
> +    "npm": ">7.0.0"
I think what we really want is `>=` here

2021-04-28 13:35 UTC, Dexterp37 commented on glean/package.json
> +    "node": ">=12.20.0",
Would you kindly add an entry to our  `CHANGELOG.md` file?

2021-04-28 15:27 UTC, AmrDhaliwal commented on glean/package.json
> +    "npm": ">7.0.0"
I have gone ahead and made that change.

2021-04-28 15:27 UTC, AmrDhaliwal commented on glean/package.json
> +    "node": ">=12.20.0",
Hi @Dexterp37,

I have added the bug as an entry into the CHANGELOG.md file.

2021-04-28 18:30 UTC, Dexterp37 requested changes
We're almost there! Thanks again for this!

2021-04-28 18:30 UTC, Dexterp37 commented on glean/package-lock.json
> +        "npm": ">7.0.0"
Please run `npm i --package-lock-only` to update the lock file

2021-04-28 19:01 UTC, AmrDhaliwal commented
Hi @Dexterp37,

I updated the CHANGELOG.md and updated the lock file.
Sorry this is taking me so long and thanks for the help.

2021-04-29 07:18 UTC, Dexterp37 approved these changes
Thank you! And don't worry about the delays, there's no rush :)

2021-04-29 07:18 UTC, merged