Add the doc for instructions on how to getting started (#)
mozilla/glean.js pull request #267
Opened 2021-04-28 23:22 UTC by ChinYing-Li

This PR fixes bug 1707601 on BugZilla, and hopefully this would help JavaScript newbies (like me!)
However, there may be more things to be added to the `getting_started` doc.
Any suggestion is appreciated!

2021-04-30 08:30 UTC, brizental requested changes
Thank you so much for picking up this bug @ChinYing-Li ! Very much appreciated.

For future reference, always start yours PR titles with `Bug <number> - ...` :) This will make sure to attach your pull requeest to the specific bug.

I will also assign you to this bug.

2021-04-30 08:30 UTC, brizental commented on CHANGELOG.md
> +* [#267](https://github.com/mozilla/glean.js/pull/267): Add instructions on how to get started.
Not necessary to add a changelog to this one, because it does not change anything for users of Glean.js as a library :)

2021-04-30 08:30 UTC, brizental commented on docs/getting_started.md
> +Glean.js uses [Node.js](https://nodejs.org/).
Also good to mention the minimum required versions here, https://github.com/mozilla/glean.js/commit/6020080d63d6013c526dc8576e42e5c64bc0329a they were added in this commit.

2021-04-30 08:30 UTC, brizental commented on docs/getting_started.md
> +* `test:platform`
Let's also add a tip here for how to run specific tests using `--grep` e.g. `npm run test:core -- --grep "specific test"`.

2021-04-30 08:30 UTC, brizental commented on docs/getting_started.md
> +To do so, substitute `test` in the command above with one of the followings:
Can you add a small explanation on what each of these mean? e.g. `npm run test:core` will execute all tests inside `tests/core` folder and so on.

2021-04-30 08:30 UTC, brizental commented on CONTRIBUTING.md
> +Here's the [guide](https://github.com/mozilla/glean.js/tree/main/docs/getting_started.md) to get you started!
Let's add this as a paragraph _after_ the `> **Note**`.

2021-04-30 08:30 UTC, brizental commented on docs/getting_started.md
> +1. At terminal, navigate the directory where you want the Glean.js repository to live. Then:
```suggestion
1. On a terminal, navigate to the directory you want the Glean.js repository to live.
```

2021-04-30 08:30 UTC, brizental commented on docs/getting_started.md
> +2.
Missing text on this bullet point.

2021-04-30 08:30 UTC, brizental commented on docs/getting_started.md
> +If you want to build certain components, please refer to the `scripts` section of [`package.json`](../glean/package.json)
I think this paragraph can be ommited :)

2021-04-30 08:30 UTC, brizental commented on docs/getting_started.md
> +Once you have [build](#building-gleanjs) Glean.js, run
```suggestion
Once you have [built](#building-gleanjs) Glean.js, run
```

2021-05-03 07:48 UTC, Dexterp37 approved these changes
This looks great! Thank you! @ChinYing-Li , would you be interested in working on another bug? If so, what about [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1708366)?

2021-05-03 07:49 UTC, merged