Bug 1687644 - Implement the external API for consumers
mozilla/glean.js pull request #27
Opened 2021-01-21 11:17 UTC by brizental

Now that we can acutally measure it, for reference:

- The webext build is 46K.
- The qt build is 44K.

2021-01-21 11:24 UTC, brizental commented
The Qt error seems unrelated. I will verify, but don't feel that it blocks the review :)

2021-01-21 11:41 UTC, Dexterp37 requested changes

2021-01-21 11:41 UTC, Dexterp37 commented on package.json
> +    "dev:webext": "webpack --watch --config webpack.config.webext.js --mode development --devtool inline-source-map",
Nice move :) I'll borrow this for Rally.

2021-01-21 11:41 UTC, Dexterp37 commented on src/index.ts
> +// Private stuff to export.
```suggestion
// Private Glean types to export.
```

2021-01-21 11:41 UTC, Dexterp37 commented on src/storage/utils.ts
> +      if (isJSONValue(temp)) {
Did you stumble upon non-JSON values being stored?

2021-01-21 11:41 UTC, Dexterp37 commented on src/upload/uploader/index.ts
> +  // eslint-disable-next-line @typescript-eslint/no-unused-vars
It makes sense since the abstract class has them. Do we need to specify this?

2021-01-21 11:41 UTC, Dexterp37 commented on src/storage/weak.ts
> +  //
It makes sense since the abstract class has it. Do we need to specify this?

2021-01-21 13:30 UTC, brizental commented on src/upload/uploader/index.ts
> +  // eslint-disable-next-line @typescript-eslint/no-unused-vars
Eh, you are right. I'll remove the comment.

2021-01-21 13:30 UTC, brizental commented on src/index.ts
> +// Private stuff to export.
Heh, much nicer.

2021-01-21 17:19 UTC, brizental commented
The Qt problems were actually related. We were using some browser APIs namely URL and crypto, which I didn't realize before. That was fixed. This is ready for a new look.

2021-01-22 13:38 UTC, Dexterp37 approved these changes

2021-01-22 13:41 UTC, merged