Bug 1687491 - Implement a dispatcher and add an instance to the Glean singleton
mozilla/glean.js pull request #31
Opened 2021-01-26 15:47 UTC by brizental

This is part 1. 

Other PRs will come for actually using this dispatcher on the external APIs.

2021-01-26 15:48 UTC, brizental commented on src/dispatcher.ts
> +  Block,
`Block` may have been a bad terminology choice. `Stop` might be better.

Also, I missed adding docs to each variant here...

2021-01-26 15:49 UTC, brizental commented on src/dispatcher.ts
> +   * and the queues length will exceed `maxPreInitQueueSize`.
```suggestion
   * Will not enqueue in case the dispatcher has not been initialized yet and the queues length exceeds `maxPreInitQueueSize`.
```

What a confusing little comment I wrote there.

2021-01-26 15:51 UTC, brizental commented on src/glean.ts
> +    await Glean.dispatcher.clear();
We should probably also clear the dispatcher `onUploadDisabled`, I need to check what is done on the bindings.

2021-01-26 15:53 UTC, brizental commented on src/dispatcher.ts
> +  async blockOnQueue(): Promise<void> {
Should probably rename this to `testBlockOnQueue`.

2021-01-26 15:54 UTC, brizental commented on src/dispatcher.ts
> +   * Flushes the tasks enqueued while the dispatcher was uuninitialized.
```suggestion
   * Flushes the tasks enqueued while the dispatcher was uninitialized.
```

2021-01-26 15:54 UTC, brizental commented on src/glean.ts
> +   * Gets this Gleans's instance dispatcher instance.
```suggestion
   * Gets this Gleans's instance dispatcher.
```

2021-01-26 15:56 UTC, brizental commented on src/glean.ts
> +  // to use this dispatcher to launch _any_ user facing API call.
```suggestion
    // A task dispatcher to execute asynchronous external API calls.
```

2021-01-26 15:57 UTC, brizental commented on src/glean.ts
> +  private _dispatcher: Dispatcher;
```suggestion
  // A task dispatcher to help execute in order asynchronous external API calls.
  private _dispatcher: Dispatcher;
```

2021-01-27 08:52 UTC, Dexterp37 requested changes

2021-01-27 08:52 UTC, Dexterp37 commented on src/dispatcher.ts
> +  async blockOnQueue(): Promise<void> {
Yes, good idea.

2021-01-27 08:52 UTC, Dexterp37 commented on src/dispatcher.ts
> +  Block,
Yes, let's rename and add docs, please :-)

2021-01-27 08:52 UTC, Dexterp37 commented on src/dispatcher.ts
> +    this.triggerExecution();
Can you add a comment before this line stating that while we know the `triggerExecution` is async, we don't want to block on it because of reasons XYZ. (please add that to the other call sites as well)

2021-01-27 08:52 UTC, Dexterp37 commented on src/dispatcher.ts
> +  launch(task: Task): boolean {
The return value is not being used anywhere (AFAICT). Do we need it or can it just be `void`?

2021-01-27 10:51 UTC, brizental commented on src/dispatcher.ts
> +  launch(task: Task): boolean {
Yeah you are right, at least for now we are not using it. I'll remove.

2021-01-27 11:01 UTC, brizental commented on src/glean.ts
> +    // Since the dispatcher is stopped, no external API calls will be executed.
Isn't this nice? The dispatcher actually fixed the issue. Now, it will only really be fixed after my next PR when the recording calls are indeed dispatched.

2021-01-27 11:15 UTC, Dexterp37 approved these changes

2021-01-27 11:15 UTC, Dexterp37 commented on tests/dispatcher.spec.ts
> + * @returns The promise.
nit: well, this could use some more explanation :D 
```suggestion
 * @returns The promise resolved when the timeout expires.
```

2021-01-27 11:21 UTC, brizental commented on tests/dispatcher.spec.ts
> + * @returns The promise.
Heh, for sure.

2021-01-27 13:03 UTC, merged