Bug 1710827 - Fail validation of counter and quantity if value is not int
mozilla/glean.js pull request #319
Opened 2021-05-17 15:37 UTC by brizental

2021-05-17 16:16 UTC, Dexterp37 requested changes

2021-05-17 16:16 UTC, Dexterp37 commented on glean/src/core/utils.ts
> +  return isNumber(v) && v % 1 === 0;
If we don't want to use `Number.isInteger`, can we at least use the [recommended polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isInteger#polyfill)?

2021-05-17 16:16 UTC, Dexterp37 commented on glean/src/core/utils.ts
> +
extra blank?

2021-05-17 16:16 UTC, Dexterp37 commented on glean/tests/core/utils.spec.ts
> +    // Invalid values
There's some other cases in [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isInteger#using_isinteger) :)

2021-05-18 08:46 UTC, brizental commented on glean/src/core/utils.ts
> +  return isNumber(v) && v % 1 === 0;
Sure :) Didn't know there was one... FWIW, all the listed test cases still pass with the current implementation the polyfill. I'll change to be extra sure.

2021-05-18 08:47 UTC, brizental commented on glean/tests/core/utils.spec.ts
> +    // Invalid values
```js
assert.strictEqual(utils.isInteger(5.0000000000000001), true);
assert.strictEqual(utils.isInteger(5.000000000000001), false);
```

Now this is a fun fact.

2021-05-18 08:47 UTC, brizental commented on glean/src/core/utils.ts
> +
Where is that linter rule when we need it?

2021-05-18 08:50 UTC, brizental commented on glean/src/core/utils.ts
> +  return isNumber(v) && v % 1 === 0;
Hm, actually we can't really use the polyfill because `Number.isFinite` has the same issue as `Number.isInteger`. This is interesting behaviour though. Why don't these work? I though `new Number()` was just another way to create a number in Javascript.

2021-05-18 08:53 UTC, brizental commented on glean/src/core/utils.ts
> +  return isNumber(v) && v % 1 === 0;
Ok, I was wrong about it! https://stackoverflow.com/questions/2381399/what-is-the-difference-between-new-number-and-number-in-javascript

2021-05-18 09:01 UTC, brizental commented on glean/src/core/utils.ts
> +  return isNumber(v) && v % 1 === 0;
Ok so, at some point I stumbled into this before because I do account for it in our checks. https://github.com/mozilla/glean.js/blob/main/glean/src/core/utils.ts#L78

To be consistent, I will remove `new Type()` from all our checks. These should not be the way most users if not all create primitives anyways. If ever this becomes a problem we can change it.

2021-05-18 09:02 UTC, Dexterp37 approved these changes

2021-05-18 09:24 UTC, merged