Bug 1702425
mozilla/glean.js pull request #341
Opened 2021-05-21 08:46 UTC by AmrDhaliwal

Creating a new pull request after the generated folder was created.

2021-05-21 08:47 UTC, AmrDhaliwal commented
@brizental Hi just made this pull request so the test.ts code can be reviewed.

2021-05-21 09:03 UTC, brizental requested changes
Test look good. Please also add a CI job to run it. You can do exactly what we do for the JS sample :) https://github.com/mozilla/glean.js/blob/main/.circleci/config.yml#L56-L80

2021-05-21 09:31 UTC, AmrDhaliwal commented
@brizental I added the CI job and I think I broke something.

2021-05-21 09:36 UTC, brizental requested changes

2021-05-21 09:36 UTC, brizental commented on .circleci/config.yml
> +          name: Build the JS sample
```suggestion
          name: Build the Typescript sample
```

2021-05-21 09:36 UTC, brizental commented on .circleci/config.yml
> +samples-tests:
This property has the exact same identifier as the one above, this is probably the issue. Maybe don't create a whole new one, but instead add the typecript steps to the `samples-tests` jobe above.

2021-05-21 09:44 UTC, AmrDhaliwal commented on .circleci/config.yml
> +samples-tests:
I seem to still be failing the ci checks.
Is it still the export PATH?

2021-05-21 09:52 UTC, AmrDhaliwal commented on .circleci/config.yml
> +samples-tests:
Oh I think I fixed it the commands were basically duplicated causing the errors.

2021-05-21 10:00 UTC, AmrDhaliwal commented on .circleci/config.yml
> +samples-tests:
@brizental it looks like the CI job failed since it timed out.

2021-05-21 12:34 UTC, brizental commented on .circleci/config.yml
> +            export PATH=.:$PATH && npm --prefix ./samples/web-extension/typescript run test
Just for us to see the error logs in more contained manner, would you mind moving the typescript command into their own jobs? Something like:

```yaml
name: Install Javascript dependencies for the JS sample
command: |
    npm --prefix ./samples/web-extension/javascript install
    npm --prefix ./samples/web-extension/javascript link @mozilla/glean
<...other JS sample related jobs...>
name: Install Typescript dependencies for the TS sample
    npm --prefix ./samples/web-extension/typescript install
    npm --prefix ./samples/web-extension/typescript link @mozilla/glean
<...other TS sample related jobs...>
```

2021-05-26 22:27 UTC, AmrDhaliwal commented
@brizental All the checks have passed please let me know if you need anything else for this bug.

2021-05-27 08:27 UTC, brizental approved these changes
Thanks for sticking to this bug @AmrDhaliwal ! The changes look good, please kindly rebase this branch before we can merge it :) Also, let me know if you are interested in taking a next bug and I can point you to some nice ones.

2021-05-27 09:19 UTC, AmrDhaliwal commented
@brizental so this was my first time actually rebasing a branch using git I'm hoping it was correct.

Also, no problem had fun even though it proved more difficult than I thought it would be.
And I would love to start on another bug if you have one in mind.

2021-05-27 09:34 UTC, brizental commented
> @brizental so this was my first time actually rebasing a branch using git I'm hoping it was correct.

Seems like you missed some steps. No worries though, try again following this instructions:

Inside the glean.js repository folder:

```bash
# Assuming the remote that points to the mozilla/glean.js repository is called `upstream`, 
# fetch all new changes without applying them:
git fetch upstream 
# Then rebase your branch on top of the newest changes in upstream's main branch:
git rebase upstream/main
```

Github is showing that your branch has conflicts, upon the second step you will probably be warned there are conflicts. Resolve the conflicts, then `git add` the changes files and run the command `git rebase --continue` to proceed with the rebase.

VSCode has [a nice visual  tool](https://code.visualstudio.com/docs/editor/versioncontrol#_merge-conflicts) to help with resolving conflicts, I use that quite a lot. Check it out if you have issues resolving the conflicts too :)

Once you are done with the rebase, use `git log` to check that your history is correct and then finally `git push origin --force-with-lease`. Force is necessary here because with rebase you will essentially change past history of your branch.

2021-05-27 09:50 UTC, AmrDhaliwal commented
@brizental when I try to rebase the branch and attempt to commit I keep getting a printout in the console saying "Nothing to commit working tree clean".

2021-05-27 09:53 UTC, brizental commented
> @brizental when I try to rebase the branch and attempt to commit I keep getting a printout in the console saying "Nothing to commit working tree clean".

You don't need to create any new commits indeed. Rebasing is about organizing the git history instead of creating new commits :)

2021-05-27 09:59 UTC, AmrDhaliwal commented
When I try to "git rebase --continue" I am now receiving the error "no rebase in progress?".

2021-05-27 10:00 UTC, AmrDhaliwal commented
OH, these conflicts are the ones with the fork of the project I have with the main repo?

2021-05-27 11:57 UTC, AmrDhaliwal commented
@brizental looks like I got it to work :)

2021-05-27 13:04 UTC, brizental commented
> @brizental looks like I got it to work :)

Indeed! Great work. I will merge this. 

Regarding next bugs, what do you think about giving [Bug 1712912](https://bugzilla.mozilla.org/show_bug.cgi?id=1712912) a try?

2021-05-27 13:05 UTC, merged

2021-05-27 14:57 UTC, AmrDhaliwal commented
@brizental bug seems interesting ill comment on it and take it :)