RFC: Initial implementation of post function for Qt
mozilla/glean.js pull request #346
Opened 2021-05-23 13:03 UTC by ChinYing-Li

This PR is a work in progress, and needs some comments before I can move on.
Right now, I implemented a `post` function in Javascript, so that the `post` function could be used in a `QML` file.

It's not immediately clear to me how this `Uploader` implementation would be exposed to a Qt application.
Will the Qt application import the entire Glean.js library? (From https://github.com/mozilla-mobile/mozilla-vpn-client/tree/main/glean, this doesn't seem to be the case.)

2021-05-24 07:55 UTC, Dexterp37 commented
> It's not immediately clear to me how this `Uploader` implementation would be exposed to a Qt application.
> Will the Qt application import the entire Glean.js library? (From https://github.com/mozilla-mobile/mozilla-vpn-client/tree/main/glean, this doesn't seem to be the case.)

Hi @ChinYing-Li ! Thank you for this PR. The uploader is used by the [Qt platform object](https://github.com/mozilla/glean.js/blob/9fc883e57d835ee6064e186bb2809d15e096ab16/glean/src/platform/qt/index.ts#L13). It should implement the `Uploader` interface (as the [test uploader does](https://github.com/mozilla/glean.js/blob/9fc883e57d835ee6064e186bb2809d15e096ab16/glean/src/platform/test/index.ts#L13-L22)). After you're done, you can check that this works by running the Qt sample.

2021-05-24 11:07 UTC, ChinYing-Li commented
I copied the `post` function of `BrowserUploader` to `qt/uploader.ts` to see why people aren't using the `webext`'s implementation for Qt platform, but it seems that the sample Qt app can run without running into any problem. 
Terminal output for your reference:

```console
chin-ying@chinying-Leopard-10SFK:~/repo/opensource/js/glean.js/samples/qt-qml-app$ .venv/bin/python3 main.py
qml: Initialized Glean succesfully.
qml: Adding to the `button_clicked` metric.
qml: Adding to the `button_clicked` metric.
qml: Adding to the `button_clicked` metric.
qml: Attempted to delete an entry from an invalid index. Ignoring.
qml: {
  "metrics": {
    "datetime": {
      "sample.app_started": "2021-05-24T06:51:47.559-04:00"
    },
    "counter": {
      "sample.button_clicked": 3
    }
  },
  "ping_info": {
    "seq": 0,
    "start_time": "2021-05-24T06:51-04:00",
    "end_time": "2021-05-24T06:52-04:00"
  },
  "client_info": {
    "telemetry_sdk_build": "0.12.0",
    "client_id": "d0c6f2e3-bf7a-4b41-b067-3c6fcb8cc438",
    "first_run_date": "2021-05-24-04:00",
    "os": "Linux",
    "os_version": "Unknown",
    "architecture": "Unknown",
    "locale": "en-US",
    "app_build": "Unknown",
    "app_display_version": "Unknown"
  }
}

```
I wonder if I missed some caveats of using the webext implementation in Qt. @Dexterp37

2021-05-26 07:49 UTC, Dexterp37 commented
> 
> 
> I copied the `post` function of `BrowserUploader` to `qt/uploader.ts` to see why people aren't using the `webext`'s implementation for Qt platform, but it seems that the sample Qt app can run without running into any problem.
>
> ...
> 
> I wonder if I missed some caveats of using the webext implementation in Qt. @Dexterp37

We were/are not sure about what subset of APIs are available on QT/QML: sadly not all of them are :-) Looks like we're lucky this time! My main concern was about `fetch`: to make sure that's working, you could spin up a local webserver (`nc -l 8080`) and pass `serverEndpoint` as a configuration option when initializing Glean in the qt-sample app (`{ serverEndpoint: "http://localhost:8080"}`). If you see the request being attempted, then this could be working :)

Would you kindly also update the code in this PR to reflect what you're currently testing?

2021-05-26 09:44 UTC, brizental reviewed
> I copied the post function of BrowserUploader to qt/uploader.ts to see why people aren't using the webext's implementation for Qt platform, but it seems that the sample Qt app can run without running into any problem.

Interesting. This should not be the case, as far as I remember Qt does not provide the `fetch` API. That is a browser only thing.

I see in the code changes that you have included a `uploader.js` file, but have not changed the exported uploader over on https://github.com/mozilla/glean.js/blob/main/glean/src/platform/qt/index.ts. That needs to be changed in order for the uploader to be actually picked up. Maybe this is the case why it seemed to work with the web ext uploader.

2021-05-26 09:44 UTC, brizental commented on glean/src/platform/qt/uploader.js
> +}
nit: Missing new line at the end of file.

2021-05-26 09:44 UTC, brizental commented on glean/src/platform/qt/uploader.js
> +        status: xhr.status,
No status is necessary when the result is not a Success result. See: https://github.com/mozilla/glean.js/blob/main/glean/src/core/upload/uploader.ts#L32-L33

2021-05-26 23:20 UTC, ChinYing-Li commented on glean/src/platform/qt/uploader.js
> +/* This Source Code Form is subject to the terms of the Mozilla Public
Indeed, I was confused how this would be exposed to QML, so I wrote it in javascript

2021-05-26 23:28 UTC, ChinYing-Li commented
> We were/are not sure about what subset of APIs are available on QT/QML: sadly not all of them are :-) Looks like we're lucky this time! My main concern was about `fetch`: to make sure that's working, you could spin up a local webserver (`nc -l 8080`) and pass `serverEndpoint` as a configuration option when initializing Glean in the qt-sample app (`{ serverEndpoint: "http://localhost:8080"}`). If you see the request being attempted, then this could be working :)

Thank you for the pointers; it turns out that the `webext`'s `BrowserUploader` does not work when listening on local webserver (using `nc -l 8080`). 
The current implementation, which uses `XMLHttpRequest`, partially worked: only the first log is received at port 8080.
```console
chin-ying@chinying-Leopard-10SFK:~/repo/opensource/js/glean.js/glean$ nc -l 8080
POST /submit/qt-qml-app/custom/1/3ee47bdb-9cdb-4d06-96f0-19434386ac76 HTTP/1.1
Host: localhost:8080
X-Client-Type: Glean.js
X-Client-Version: 0.12.0
Content-Type: application/json; charset=UTF-8
Content-Length: 441
Connection: Keep-Alive
Accept-Encoding: gzip, deflate
Accept-Language: en-US,*
User-Agent: Mozilla/5.0

{"metrics":{"datetime":{"sample.app_started":"2021-05-26T19:06:55.964-04:00"}},"ping_info":{"seq":0,"start_time":"2021-05-26T19:06-04:00","end_time":"2021-05-26T19:06-04:00"},"client_info":{"telemetry_sdk_build":"0.12.0","client_id":"29aa3260-d94f-4dc0-ae3b-721284c081d3","first_run_date":"2021-05-26-04:00","os":"Linux","os_version":"Unknown","architecture":"Unknown","locale":"en-US","app_build":"Unknown","app_display_version":"Unknown"}}
```

I will further investigate and update when the patch is ready!

2021-05-27 08:32 UTC, brizental commented on glean/src/platform/qt/uploader.js
> +/* This Source Code Form is subject to the terms of the Mozilla Public
For sure, this is not well documented yet. Qt applications cannot use npm, so we instead bundle Glean.js for this platform using webpack: https://github.com/mozilla/glean.js/blob/main/glean/webpack.config.qt.js and https://github.com/mozilla/glean.js/blob/main/glean/package.json#L54 

The bundle is added as an asset with each new Glean.js release: https://github.com/mozilla/glean.js/releases. Note the "Assets" section of each release.

2021-05-28 22:50 UTC, ChinYing-Li commented
So the problem of "hanging after receiving the first log" seems to be a server side issue instead of a client side issue.
I used the snippet below to create a local server:
```python
import socket
import sys

try:
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.bind(('127.0.0.1', 8080))  # (host, port) because AF_INET
    print("Listening...")
    sock.listen(1)
except Exception as e:
    print(repr(e))
    print('Failed to create socket')
    sys.exit()

if __name__ == "__main__":
    while True:
        conn, addr = sock.accept()
        print('Connected by', addr)
        print(conn.recv(4096)) # buffer size
        conn.close()
```
Every time the `Submit ping` in the Qt sample app is clicked, the server logs:
```console
Connected by ('127.0.0.1', 52400)
b'POST /submit/qt-qml-app/custom/1/e575aec8-8564-42f5-9580-ce3e8fdb28b8 HTTP/1.1\r\nHost: localhost:8080\r\nX-Client-Type: Glean.js\r\nX-Client-Version: 0.12.0\r\nContent-Type: application/json; charset=UTF-8\r\nContent-Length: 441\r\nConnection: Keep-Alive\r\nAccept-Encoding: gzip, deflate\r\nAccept-Language: en-US,*\r\nUser-Agent: Mozilla/5.0\r\n\r\n{"metrics":{"datetime":{"sample.app_started":"2021-05-28T18:43:19.156-04:00"}},"ping_info":{"seq":0,"start_time":"2021-05-28T18:43-04:00","end_time":"2021-05-28T18:43-04:00"},"client_info":{"telemetry_sdk_build":"0.12.0","client_id":"f9a3d823-2e0d-4407-a92e-951606ad2efb","first_run_date":"2021-05-28-04:00","os":"Linux","os_version":"Unknown","architecture":"Unknown","locale":"en-US","app_build":"Unknown","app_display_version":"Unknown"}}'
```

And the client (Qt app mode, in debug mode) logs to terminal:
```console
qml: Attempted to delete an entry from an invalid index. Ignoring.
qml: {
  "metrics": {
    "datetime": {
      "sample.app_started": "2021-05-28T18:43:19.156-04:00"
    }
  },
  "ping_info": {
    "seq": 0,
    "start_time": "2021-05-28T18:43-04:00",
    "end_time": "2021-05-28T18:43-04:00"
  },
  "client_info": {
    "telemetry_sdk_build": "0.12.0",
    "client_id": "f9a3d823-2e0d-4407-a92e-951606ad2efb",
    "first_run_date": "2021-05-28-04:00",
    "os": "Linux",
    "os_version": "Unknown",
    "architecture": "Unknown",
    "locale": "en-US",
    "app_build": "Unknown",
    "app_display_version": "Unknown"
  }
}
qml: Some network error occurred. undefined
qml: Recoverable upload failure while attempting to send ping e575aec8-8564-42f5-9580-ce3e8fdb28b8, will retry. Error was no status.
qml: Some network error occurred. undefined
qml: Recoverable upload failure while attempting to send ping e575aec8-8564-42f5-9580-ce3e8fdb28b8, will retry. Error was no status.
qml: Some network error occurred. undefined
qml: Recoverable upload failure while attempting to send ping e575aec8-8564-42f5-9580-ce3e8fdb28b8, will retry. Error was no status.
qml: Reached maximum recoverable failures for the current uploading window. You are done.
```
The `qml: Some network error occurred. undefined` lines are due to the fact that the server force-closed the connection. The error is raised by Qt app whenever I manually spin up and shut down a server.
Any suggestion is appreciated!

2021-05-31 09:59 UTC, brizental commented
> The qml: Some network error occurred. undefined lines are due to the fact that the server force-closed the connection. The error is raised by Qt app whenever I manually spin up and shut down a server.

Hm, could this be happening because there is no response from the server to the client? Note that Glean.js expects some response from the server. The body of the request shouldn't matter, only the status code. Try adding a `conn.send` statement returning a response that starts with `"HTTP/1.1 200 OK\n"` before closing the connection. I have not tested this, but it might work.

Wondering the we should provide a test server in our development documentation. WDYT? @ChinYing-Li @Dexterp37

2021-05-31 12:29 UTC, Dexterp37 commented
> Wondering if we should provide a test server in our development documentation. WDYT? @ChinYing-Li @Dexterp37

We do have a [simple test server](https://github.com/mozilla/gzipServer) if we want to make sure the ingestion is not the offending part.

2021-05-31 22:12 UTC, ChinYing-Li commented
I tested the code with https://github.com/mozilla/gzipServer, and it does work.
PR ready for review. Thank you for all your help!

2021-06-01 07:54 UTC, brizental requested changes
Great work here, @ChinYing-Li ! Let's also add some tests to the new uploader. We need to make sure that

1. When the request is completed succesfully, the correct UploadResult is returned;
2. When the request is not completed succesfully, the correct UploadResult is returned;
3. When the request times out, the correct UploadResult is returned.

Another thing. We need to be extra sure that the promise returned by the Uploader _always_ resolves. I notice the `onabort` event is not covered. Although the request unlikely to be aborted, I think it is best to make sure we cover all cases. Another option would be to resort to the `onloadend` event which is triggered when the request is completed withor without errors.

2021-06-01 07:54 UTC, brizental commented on glean/src/platform/qt/uploader.ts
> +import type { UploadResult} from "../../core/upload/uploader.js";
nit: Space before `}`.

2021-06-01 07:54 UTC, brizental commented on glean/src/platform/qt/uploader.ts
> +        console.error("Some network error occurred while attempting to upload ping.", e);
nit: Let's keep the error messages consistent between uploaders :) 

https://github.com/mozilla/glean.js/blob/main/glean/src/platform/webext/uploader.ts#L38

2021-06-05 21:48 UTC, ChinYing-Li commented
Just to update what I've been trying to do:
I attempted to use `sinon.SinonFakeServer` to mock the local server, as it seems doable, according to [this blog](https://rjzaworski.com/2015/05/testing-api-requests-with-xhr-and-sinon-js).
However, `SinonFakeServer` doesn't seem to intercept the `xhr`, and the unit tests for `QtUploader` always timeout (Promise not resolved).

Please let me know if you have any thought on this. 
Will continue investigating!

2021-06-07 08:33 UTC, Dexterp37 commented
> 
> 
> Just to update what I've been trying to do:
> I attempted to use `sinon.SinonFakeServer` to mock the local server, as it seems doable, according to [this blog](https://rjzaworski.com/2015/05/testing-api-requests-with-xhr-and-sinon-js).

Hey, our of curiosity, why are you trying to mock the server, @ChinYing-Li ?

2021-06-07 22:15 UTC, ChinYing-Li commented
> 
> Hey, our of curiosity, why are you trying to mock the server, @ChinYing-Li ?

I thought it's better to write unit tests for `QtUploader`, and I think a mock server is the right way to go for unit tests. Looking at the unit tests written for `BrowserUploader`, I didn't really see how I can stub `QtUploader.post` using sinon.sandbox. Do you have any suggestion?

2021-06-11 08:48 UTC, brizental requested changes

2021-06-11 08:48 UTC, brizental commented on glean/src/platform/qt/uploader.ts
> +        console.error("Timeout while attempting to upload ping.", e);
New thing, but over on #411 we added a new logging function to standardize log messages across the lib and tag them. Let's change this file to use the new `log` function. The log tag should be the path to this file, so `platform.qt.Uploader` :)

2021-06-11 08:48 UTC, brizental commented on glean/tests/unit/platform/qt_uploader.spec.ts
> +  it("timeout", async function () {
nit: Let's give this test a more descriptive title.

2021-06-11 08:48 UTC, brizental commented on glean/tests/unit/platform/qt_uploader.spec.ts
> +/* This Source Code Form is subject to the terms of the Mozilla Public
nit: In this case, let's actually create a `qt/` folder and put `uploader.spec.ts` in there. Same thing for the other uploader test file, let's put it inside the a `webext/` folder. Our tests folder structure loosely follows the library folder structure.

2021-06-11 08:53 UTC, brizental commented on glean/tests/unit/platform/qt_uploader.spec.ts
> +/* This Source Code Form is subject to the terms of the Mozilla Public
> Now that I've split the unit tests for uploader into two files (to accomodate to mocha/max-top-suite rule), I think the browser/uploader tests were silently skipped. I'll look into this, and let people know once the PR is ready for review.

Hm, that is interesting. That rule should not prevent the tests from running, since that is a linter rule. We also have more than one top level suite on the `storage.spec.ts` and they seem to be running normally. Why do you think the tests were being skipped?

2021-06-13 10:45 UTC, ChinYing-Li commented on glean/tests/unit/platform/qt_uploader.spec.ts
> +/* This Source Code Form is subject to the terms of the Mozilla Public
If I put both top level test suite in `uploader.spec.ts`, both test suites were ran; but if I separate them into `qt_uploader.spec.ts` and `webext_uploader.spec.ts`, the console only logs the message from `qt_uploader` unit tests, and `webext_uploader` unit tests disappeared.

2021-06-14 07:53 UTC, brizental requested changes
This is looking great, thanks for the hard work here! There are a just a few last nits to address, otherwise, good to go.

2021-06-14 07:53 UTC, brizental commented on glean/src/platform/qt/uploader.ts
> +import log, {LoggingLevel} from "../../core/log.js";
nit: Space around brackets.

2021-06-14 07:53 UTC, brizental commented on glean/package.json
> +    "request": "^2.88.2",
Why are we added this and the other dev dependency? If this is just left over from development let's remove them both :)

2021-06-14 07:53 UTC, brizental commented on glean/src/platform/qt/uploader.ts
> +        log(LOG_TAG, ["Network while attempting to upload ping.\n", e.type], LoggingLevel.Error);
```suggestion
        log(LOG_TAG, ["Network error while attempting to upload ping.\n", e.type], LoggingLevel.Error);
```

2021-06-14 07:53 UTC, brizental commented on glean/tests/unit/platform/qt/uploader.spec.ts
> +        {status: status, result: UploadResultStatus.Success});
nit: Space around brackets.

2021-06-14 07:53 UTC, brizental commented on glean/tests/unit/platform/qt/uploader.spec.ts
> +      {result: UploadResultStatus.RecoverableFailure});
nit: Space around brackets.

2021-06-15 08:14 UTC, ChinYing-Li commented on glean/src/platform/qt/uploader.ts
> +        log(LOG_TAG, ["Network while attempting to upload ping.\n", e.type], LoggingLevel.Error);
Should we add "error" to the message in webext/uploader.ts too?

2021-06-15 08:24 UTC, brizental commented on glean/src/platform/qt/uploader.ts
> +        log(LOG_TAG, ["Network while attempting to upload ping.\n", e.type], LoggingLevel.Error);
Yes, I did that a few days back :) https://github.com/mozilla/glean.js/blob/main/glean/src/platform/webext/uploader.ts#L41 Good think though!

2021-06-15 08:28 UTC, ChinYing-Li commented on glean/package.json
> +    "request": "^2.88.2",
Hi @brizental , these two packages are needed for xhr; if they are not included, errors will be thrown when running the unit tests:
```console
Error: Cannot find module 'request'
Require stack:
- /home/chin-ying/repo/opensource/js/glean.js/glean/node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js
- /home/chin-ying/repo/opensource/js/glean.js/glean/node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js
- /home/chin-ying/repo/opensource/js/glean.js/glean/node_modules/jsdom/lib/jsdom/living/generated/XMLHttpRequest.js
- /home/chin-ying/repo/opensource/js/glean.js/glean/node_modules/jsdom/lib/jsdom/living/interfaces.js
- /home/chin-ying/repo/opensource/js/glean.js/glean/node_modules/jsdom/lib/jsdom/browser/Window.js
- /home/chin-ying/repo/opensource/js/glean.js/glean/node_modules/jsdom/lib/api.js
- /home/chin-ying/repo/opensource/js/glean.js/glean/node_modules/jsdom-global/index.js
- /home/chin-ying/repo/opensource/js/glean.js/glean/node_modules/jsdom-global/register.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/home/chin-ying/repo/opensource/js/glean.js/glean/node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:3:17)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/home/chin-ying/repo/opensource/js/glean.js/glean/node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:10:18)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/home/chin-ying/repo/opensource/js/glean.js/glean/node_modules/jsdom/lib/jsdom/living/generated/XMLHttpRequest.js:617:14)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/home/chin-ying/repo/opensource/js/glean.js/glean/node_modules/jsdom/lib/jsdom/living/interfaces.js:166:19)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/home/chin-ying/repo/opensource/js/glean.js/glean/node_modules/jsdom/lib/jsdom/browser/Window.js:7:31)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/home/chin-ying/repo/opensource/js/glean.js/glean/node_modules/jsdom/lib/api.js:13:26)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at globalJsdom (/home/chin-ying/repo/opensource/js/glean.js/glean/node_modules/jsdom-global/index.js:28:15)
    at Object.<anonymous> (/home/chin-ying/repo/opensource/js/glean.js/glean/node_modules/jsdom-global/register.js:1:19)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:201:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:154:23)
    at Loader.import (node:internal/modules/esm/loader:177:24)
    at importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at formattedImport (/home/chin-ying/repo/opensource/js/glean.js/glean/node_modules/mocha/lib/esm-utils.js:7:14)
    at Object.exports.loadFilesAsync (/home/chin-ying/repo/opensource/js/glean.js/glean/node_modules/mocha/lib/esm-utils.js:55:20)
    at singleRun (/home/chin-ying/repo/opensource/js/glean.js/glean/node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at Object.exports.handler (/home/chin-ying/repo/opensource/js/glean.js/glean/node_modules/mocha/lib/cli/run.js:362:5)
```

2021-06-15 08:32 UTC, brizental commented on glean/package.json
> +    "request": "^2.88.2",
Hum, in this case please move it to the devDependencies list.

2021-06-16 08:28 UTC, brizental approved these changes
Great work here, @ChinYing-Li ! Thanks a lot, this is of great help to the project. We appreciate you taking bugs on Glean.js :)

2021-06-16 08:29 UTC, merged