Bug 1688902 - Create the events metric type
mozilla/glean.js pull request #36
Opened 2021-02-02 18:17 UTC by Dexterp37

See the individual commit messages descriptions for easier review.

This exclusively adds the metric type, it doesn't take care of adding the 'events' ping.

2021-02-02 18:19 UTC, Dexterp37 commented on src/metrics/events_database.ts
> +    this.eventsStore = new WeakStore("unused");
This should probably use the persistent storage :-P

2021-02-02 18:19 UTC, Dexterp37 commented on src/metrics/events_database.ts
> +    });
I wonder if there's any less ugly way to express this. Thoughts?

2021-02-03 09:30 UTC, brizental requested changes
Approach looks fine for me overall. Left a bunch of comments but most of them are nits. 

My main concern is the liebral usage of `as` to bypass the type checker.

2021-02-03 09:30 UTC, brizental commented on src/metrics/events_database.ts
> +      .filter((e) => {
nit: You could spare an iteration round here by using `reduce`.

```ts
return rawEvents.reduce((result, elem) => {
  const rawEventObj = elem as JSONObject;
  if (rawEventObj["category"] === metric.category && rawEventObj["name"] === metric.name) {
    result.push(RecordedEvent.fromJSONObject(e as JSONObject))
  }
}, []);
```

2021-02-03 09:30 UTC, brizental commented on src/metrics/events_database.ts
> +  async getPingMetrics(ping: string, clearPingLifetimeData: boolean): Promise<JSONArray | undefined> {
nit: `getPingEvents`

2021-02-03 09:30 UTC, brizental commented on src/metrics/events_database.ts
> +      const objA = a as unknown as RecordedEvent;
Why do you need the `as unknown` here? Ideally `getAndValidatePingData` should already return an array of `RecordedEvent`s in my mind. Then you wouldn't need so many castings here.

2021-02-03 09:30 UTC, brizental commented on src/metrics/events_database.ts
> +    });
What exactly are you finding ugly here? Heh. 

I guess for me the liberal use of `as` is concerning, but it also make it a bit "ugly", specially here where you have `as unknown as RecordedEvent`.

In glean-core we have a [`serialize_relative`](https://github.com/mozilla/glean/blob/main/glean-core/src/event_database/mod.rs#L49-L56) method in the RecordedEvent directly, that might separate things a bit and make it nicer.

Let me know if you meant that something else was ugly hehe.

2021-02-03 09:30 UTC, brizental commented on src/metrics/types/event.ts
> + * A datetime metric.
Oops, 🍝

2021-02-03 09:30 UTC, brizental commented on src/metrics/types/event.ts
> +    return Math.round(performance.now() / 1000);
`performance.now` is a browser API. Would you mind providing a fallback here? No need to overthink it, it can be a Date.now() and we add a nove about the fallback not being monotonic for now. This is probably why the Qt build failed.

2021-02-03 09:30 UTC, brizental commented on src/metrics/types/event.ts
> +   *              strings, keys are identifiers. This is used for events where
uber nit: identation shoud align with `extra`. At least that is how I've been aligning all this time.

2021-02-03 11:17 UTC, Dexterp37 commented on src/metrics/events_database.ts
> +    });
Yeah, the usage of `as unknown` was my concern :(

2021-02-03 11:21 UTC, Dexterp37 commented on package.json
> +    "test": "npm run build:test-webext && npm run test:unit --",
Good catch, it can be removed.

2021-02-03 11:28 UTC, Dexterp37 commented on src/metrics/events_database.ts
> +  async testGetValue(
Sounds good. I changed this to `getEvents` (trailing 's') though, because it can return multiple events for the same id.

2021-02-03 11:28 UTC, Dexterp37 commented on src/metrics/events_database.ts
> +  static toJSONObject(e: RecordedEvent): JSONObject {
In an attempt to have an easy optimization: we don't need them on each instance.

2021-02-03 11:31 UTC, Dexterp37 commented on src/metrics/events_database.ts
> +      .filter((e) => {
> Warning: untested code.

```
Type 'JSONValue' is not assignable to type 'RecordedEvent[] | undefined'.
  Type 'string' is not assignable to type 'RecordedEvent[] | undefined'.ts(2322)
```

:-D

2021-02-03 11:37 UTC, Dexterp37 commented on src/metrics/types/event.ts
> +    return Math.round(performance.now() / 1000);
@brizental we should probably have a "platform" level abstraction somwhere. WDYT?

2021-02-03 12:52 UTC, brizental commented on src/metrics/events_database.ts
> +    });
If the validation function returns the correct type that should make things nicer.

2021-02-03 12:53 UTC, brizental commented on src/metrics/events_database.ts
> +      .filter((e) => {
https://github.com/mozilla/glean.js/pull/36#discussion_r569388605 This should fix that though.

2021-02-03 12:57 UTC, brizental commented on src/metrics/types/event.ts
> +    return Math.round(performance.now() / 1000);
Honestly, for now I'd rather leave this here, if this function gets bigger we can break it into smaller parts. WDYT?

2021-02-03 13:22 UTC, brizental requested changes

2021-02-03 13:22 UTC, brizental commented on src/metrics/events_database.ts
> +    this.eventsStore = new WeakStore("unused");
Hey, I think this one was missed :)

2021-02-03 13:22 UTC, brizental commented on src/metrics/events_database.ts
> +      return undefined;
uber nit: If you change the return type to `Promise<RecordedEvent[] | void>` you can do just `return;` here.

2021-02-03 13:49 UTC, brizental approved these changes
r+wc!

2021-02-03 13:49 UTC, brizental commented on src/metrics/events_database.ts
> +    this.eventsStore = new PersistentStore("unused");
`"unused"` may not the most descriptive storage name. Maybe `"events"`?

2021-02-03 13:54 UTC, merged