Bug 1707896 - Make the Qt package a QML module
mozilla/glean.js pull request #375
Opened 2021-05-28 15:18 UTC by brizental

Opening as a draft as this depends on https://github.com/mozilla/glean_parser/pull/342

I have tested manually of course, but we will be sure once CI turns out green after updating glean_parser 👀 

Just remembered that I still need to:

- [ ] Change the way we release the Qt package in order to release it as a QML module (i.e. with the long path + qmldir file).

2021-05-28 15:23 UTC, brizental commented on glean/qt.entry.js
> +/* This Source Code Form is subject to the terms of the Mozilla Public
This file will be copied to the final `dist/qt/org/mozilla/` folder and it will be the actual entry point from QML, not the file under `src/index/`

2021-05-28 15:23 UTC, brizental commented on samples/qt-qml-app/main.qml
> +import "./generated"
Because the module created by glean_parser will [depend on `org.mozilla.Glean`](https://github.com/mozilla/glean_parser/pull/342/files#diff-4fc68f3830dc22e9638cb0c79eecf5185858b67c5fbf693b4744c74921c00ba2R5) it does not matter anymore whether the generated stuff is imported before of after the Glean import. As a matter of fact, it's not even necessary to have a Glean import at all for them to work, because [they import Glean themselves](https://github.com/mozilla/glean_parser/pull/342/files#diff-df168f83dce8d90814da12deb8e661a62d1ab187c912e5c9b3667716ecc21412R29).

2021-05-28 15:23 UTC, brizental commented on bin/prepare-release.sh
> +### Qt sample app ###
This is necessary because QML required that you add version number along with the import statements.

2021-05-28 15:35 UTC, Dexterp37 requested changes

2021-05-28 15:35 UTC, Dexterp37 commented on bin/prepare-release.sh
> +### Qt sample app ###
Can you add this as a comment in this file?

2021-05-28 15:35 UTC, Dexterp37 commented on bin/prepare-release.sh
> +# This gets the version without the path version.
```suggestion
# This gets the version without the patch version.
```

2021-05-28 15:35 UTC, Dexterp37 commented on bin/prepare-release.sh
> +GLEAN_VERSION_FOR_QML=$(node -p -e "require('${WORKSPACE_ROOT}/glean/package.json').version.split('.').reverse().slice(1).reverse().join('.')")
Mh, instead of doing this magic incantation, can't we take it from `${NEW_VERSION}` (dropping the patch version)? This will also make sure this still works if the order of the updates within this file changes..

2021-05-28 15:35 UTC, Dexterp37 commented on glean/qt.entry.js
> +/* This Source Code Form is subject to the terms of the Mozilla Public
Can we copy this under `src/index` then? Can we also add a comment to the `src/index/qt.ts` file stating this? (and also to this file..)

2021-05-28 15:35 UTC, Dexterp37 commented on glean/qt.entry.js
> +/* This Source Code Form is subject to the terms of the Mozilla Public
Maybe also expand on why we need this file and the index file is not alone (I understood why, but we should track this knowledge in the code)

2021-05-28 15:45 UTC, brizental commented on bin/prepare-release.sh
> +GLEAN_VERSION_FOR_QML=$(node -p -e "require('${WORKSPACE_ROOT}/glean/package.json').version.split('.').reverse().slice(1).reverse().join('.')")
Yeah... sure...  I was avoiding doing that lol

2021-05-28 15:45 UTC, brizental commented on glean/qt.entry.js
> +/* This Source Code Form is subject to the terms of the Mozilla Public
Sure,k I thought about putting it there but it looked weird. Then again, it looks weird where it is right now.

2021-06-03 13:36 UTC, Dexterp37 approved these changes
Neat. Would you kindly file a bug about adding docs about "adding Glean.js to a QML project"?

2021-06-03 13:37 UTC, Dexterp37 commented on .circleci/config.yml
> +            glean_parser translate metrics.yaml pings.yaml -f javascript -o generated \
Please let's also add a changelog entry.

2021-06-03 13:44 UTC, brizental commented
> Would you kindly file a bug about adding docs about "adding Glean.js to a QML project"?

https://bugzilla.mozilla.org/show_bug.cgi?id=1714361

2021-06-03 14:08 UTC, merged