Bug 1712912 - Remove unset API for debugging features
mozilla/glean.js pull request #376
Opened 2021-05-29 01:28 UTC by AmrDhaliwal

2021-05-29 02:19 UTC, AmrDhaliwal commented
Removed the unset API from the debugging feature. 
Had a few errors with circleci but, fixed them by removing
leftover parts of the unset code blocks.

2021-05-31 10:08 UTC, brizental requested changes
Thanks for taking on this work, @AmrDhaliwal ! Let's also remove the `unserSourceTags` API here.

2021-05-31 10:08 UTC, brizental commented on glean/tests/unit/core/pings/maker.spec.ts
> -    assert.strictEqual(PingMaker.getPingHeaders(Context.debugOptions), undefined);
I am not confortable removing this assertion. The way to unset these tags after removal of the unset APIs is to reset Glean itself. Thus, running `testResetGlean` should work to unset them.

2021-06-02 04:41 UTC, AmrDhaliwal commented on glean/tests/unit/core/pings/maker.spec.ts
> -    assert.strictEqual(PingMaker.getPingHeaders(Context.debugOptions), undefined);
Would I just want to place this assertion back into the maker.spec.ts file?

2021-06-02 07:50 UTC, brizental commented on glean/tests/unit/core/pings/maker.spec.ts
> -    assert.strictEqual(PingMaker.getPingHeaders(Context.debugOptions), undefined);
Yes.

2021-06-03 03:41 UTC, AmrDhaliwal commented
@brizental I put the assertion back in the maker.spec.ts file and removed the unsetSourceTags
but, I am unable to find why the circleci test is failing.

2021-06-03 15:40 UTC, brizental commented
> @brizental I put the assertion back in the maker.spec.ts file and removed the unsetSourceTags but, I am unable to find why the circleci test is failing.

Try running the failing test locally, to investigate the error message. Instructions on how to run the tests can be found [here](https://github.com/mozilla/glean.js/blob/main/docs/getting_started.md#running-tests). 

Note, that simply adding the assertion back will not be enough. That assertion verifies that the tags were cleared succesfully, but the code to API to clear the tags was removed, so we need to clear them in some other way. That way is by resetting Glean, which can be done in tests by calling the `testResetGlean` API.

2021-06-04 03:23 UTC, AmrDhaliwal commented
@brizental I added "Glean.testResetGlean();" to the maker.spec.ts file and am no longer receiving the error message
and all tests on circleci are passing as well.

2021-06-04 07:46 UTC, brizental approved these changes
Looks great! Thanks for the thorough work here. 

Les us know if you would like to take a next bug :)

2021-06-04 07:51 UTC, AmrDhaliwal commented
@brizental If you have another bug in mind I would be happy to take it on.

2021-06-04 09:36 UTC, brizental commented
> @brizental If you have another bug in mind I would be happy to take it on.

For sure, check out  https://bugzilla.mozilla.org/show_bug.cgi?id=1712914. It is very similar to this one in the sense that it is the _removal_ of an API. If you think it looks interesting just leave a comment there and I will assign it to you :) Otherwise I am open to discuss other bugs that you think are more interesting. Thanks a lot for the excitement in contributing to Glean.js!

2021-06-04 09:36 UTC, merged