Bug 1687491 - Dispatch all external API calls
mozilla/glean.js pull request #40
Opened 2021-02-05 14:57 UTC by brizental

Not only does this change the code to dispatch all external API calls but also it adequates the dispatcher and other parts of the code for all to work as expected. 

I attempted to separate the changes as well as possible in specific commits and be very descriptive in my commit messages. Sincerely hope that makes review clearer.

It seems this could have been broken in multiple PRs, but either tests would fail or the change wouldn't make sense by itself.

2021-02-05 15:01 UTC, brizental commented on src/dispatcher.ts
> +  testLaunch(task: Task): Promise<void> {
The best way that I found to make sure that `testGetValue` function were called for sure only after `set`/`add` function was to dispatch the testing functions themselves.

2021-02-05 16:46 UTC, Dexterp37 requested changes

2021-02-05 16:46 UTC, Dexterp37 commented on samples/qt-qml-app/main.qml
> +    Glean.Glean.initialize("qt-qml-app", true);
`Glean.Glean` is so... eugh. But not new in this PR :)

2021-02-05 16:46 UTC, Dexterp37 commented on src/glean.ts
> +  static initialize(
<3

2021-02-05 16:46 UTC, Dexterp37 commented on src/glean.ts
> +    // The configuration constructor will throw in case config hany any incorrect prop.
```suggestion
    // The configuration constructor will throw in case config has any incorrect prop.
```

2021-02-05 16:46 UTC, Dexterp37 commented on src/glean.ts
> +    // The configuration constructor will throw in case config hany any incorrect prop.
But.. it should probably not throw. The Glean SDK never throws, since it may break the consuming product.

2021-02-05 16:46 UTC, Dexterp37 commented on src/metrics/types/datetime.ts
> +  static async _private_setSync(instance: DatetimeMetricType, value?: Date): Promise<void> {
You know, it feels weird for `_private_setSync` to be marked as `async` :-D

2021-02-05 16:46 UTC, Dexterp37 commented on src/metrics/types/datetime.ts
> +  static async _private_setSync(instance: DatetimeMetricType, value?: Date): Promise<void> {
Maybe `_private_setUndispatched`?

2021-02-05 16:46 UTC, Dexterp37 commented on src/storage/persistent/webext.ts
> +      console.warn((e as Error).message, "Ignoring");
```suggestion
      console.warn("Ignoring key", e);
```

This is another option. The whole exception object will be accessible in the console.

2021-02-05 16:46 UTC, Dexterp37 commented on src/storage/weak.ts
> +
nit :) trailing whitespace

2021-02-05 16:46 UTC, Dexterp37 commented on src/storage/weak.ts
> +
nit :) trailing whitespace

2021-02-05 16:59 UTC, brizental commented on samples/qt-qml-app/main.qml
> +    Glean.Glean.initialize("qt-qml-app", true);
Yup, not sure how to bypass that though. Also didn't look into it too much hehe.

2021-02-05 17:02 UTC, brizental commented on src/storage/weak.ts
> +
```suggestion

```

2021-02-05 17:02 UTC, brizental commented on src/storage/weak.ts
> +
```suggestion

```

2021-02-08 12:39 UTC, Dexterp37 approved these changes
r+wc

2021-02-08 12:39 UTC, Dexterp37 commented on src/dispatcher.ts
> +            "IMPOSSIBLE: Something went wrong while the dispatcher was executing the tasks queue.",
Bets on when we'll see this message?

2021-02-08 12:39 UTC, Dexterp37 commented on tests/upload/index.spec.ts
> +    void uploader.triggerUpload();
What's this `void` here for?

2021-02-08 13:25 UTC, brizental commented on src/dispatcher.ts
> +            "IMPOSSIBLE: Something went wrong while the dispatcher was executing the tasks queue.",
no bets, unless we change the `executeTask` to not catch errors or use the observers for something else. right now it should be impossible for this to error. i only added the catch here because the linter was complaining :D

2021-02-08 13:27 UTC, brizental commented on tests/upload/index.spec.ts
> +    void uploader.triggerUpload();
ah, this is also a complaint from the linter, about not doing anything with a statement that returns a promise. but the `void` is pretty cool. it is not a typescript operator, it is a javacript operator and what it does is evalute whatever expression comes after it and return undefined.

2021-02-08 13:28 UTC, merged