Bug 1691365 - Use glean_parser for generating metrics and pings code in samples
mozilla/glean.js pull request #45
Opened 2021-02-10 14:12 UTC by brizental

This depends on https://github.com/mozilla/glean_parser/pull/274 being merged and new version of glean_parser being released after that. Before that happens CI should fail for Qt because we need to a glean_parser step to that script.

2021-02-10 17:22 UTC, Dexterp37 requested changes

2021-02-10 17:22 UTC, Dexterp37 commented on samples/qt-qml-app/metrics.yaml
> +$schema: moz://mozilla.org/schemas/glean/metrics/1-0-0
Let's use the schema 2-0-0 :-)

2021-02-10 17:22 UTC, Dexterp37 commented on samples/qt-qml-app/pings.yaml
> +$schema: moz://mozilla.org/schemas/glean/pings/1-0-0
Let's use the newer schema here, too!

2021-02-10 17:22 UTC, Dexterp37 commented on samples/web-extension/README.md
> +npm run glean_parser
Mh, this is really nitpicking, but should we think of a better name, especially if we're planning on exposing commands to external products? `npm run glean` seems good enough, IMHO :)

For consideration, but not for this PR:

- Is there any way we could expose an NPM hook to run at specific points ? (e.g. always run when touching code?)
- How can we nicely integrate with webextension build systems?

2021-02-10 17:22 UTC, Dexterp37 commented on samples/web-extension/metrics.yaml
> +$schema: moz://mozilla.org/schemas/glean/metrics/1-0-0
schema version :D

2021-02-10 17:22 UTC, Dexterp37 commented on samples/web-extension/pings.yaml
> +$schema: moz://mozilla.org/schemas/glean/pings/1-0-0
Version :-P

2021-02-10 17:22 UTC, Dexterp37 commented on src/internal_pings.ts
> + * Pings initialized here should be defined in `./pings.yaml`
What do you mean, here?

2021-02-10 17:22 UTC, Dexterp37 commented on src/metrics.yaml
> +$schema: moz://mozilla.org/schemas/glean/metrics/1-0-0
Schema version !

2021-02-10 17:22 UTC, Dexterp37 commented on src/pings.yaml
> +$schema: moz://mozilla.org/schemas/glean/pings/1-0-0
Guess what..? :-D

2021-02-11 08:16 UTC, brizental commented on samples/qt-qml-app/metrics.yaml
> +$schema: moz://mozilla.org/schemas/glean/metrics/1-0-0
Heh, this file is copied over from glean-core. Did you find a bug there? https://github.com/mozilla/glean/blob/9225273abbb7a3d91079145d202edcaf621bdf70/glean-core/pings.yaml#L10 Happy to file it if confirmed.

2021-02-11 08:22 UTC, Dexterp37 commented on samples/qt-qml-app/metrics.yaml
> +$schema: moz://mozilla.org/schemas/glean/metrics/1-0-0
It's not a bug. We're migrating things over. The glean parser version with the new schema was released [only 5 days ago](https://github.com/mozilla/glean_parser/blob/main/HISTORY.rst#200-2021-02-05).

2021-02-11 08:34 UTC, brizental commented on samples/web-extension/README.md
> +npm run glean_parser
> Is there any way we could expose an NPM hook to run at specific points ? (e.g. always run when touching code?)

We can run the script whenever we run `npm run dev` or `npm run build`. I thought that could get annoying because these files don't really need to be rebuilt everytime and I thought it was overkill to write some sort of script that checks if there were changes to the .yaml files before building, given that this is a sample app.

> How can we nicely integrate with webextension build systems?

I [filed a bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1692149) for investigation on this. Like I put in the note here, right now you need to have glean_parser installed as an available CLI tool for the command to work. My hunch is that the easiest path would be to provide a glean_parser npm package that will install glean_parser (the python package) magically for the user.

2021-02-11 08:36 UTC, brizental commented on src/internal_pings.ts
> + * Pings initialized here should be defined in `./pings.yaml`
That the pings defined here should be defined in pings.yaml. Not sure what is the confusion.

Autogenerating the internal metrics and pings is not a good idea here, we need a more robust and specific class than glean_parser provides (at least for metrics) and we would need to generate these files all the time... anyways would not play well with the development workflow IMO. I think glean_parser should stay as a user tool, not a glean internal development tool.

2021-02-11 08:37 UTC, brizental commented on src/internal_pings.ts
> + * Pings initialized here should be defined in `./pings.yaml`
> That the pings defined here should be defined in pings.yaml

We have this for glean_core, that is the only reason I also added .yaml files for internal metrics and pings here. There are really just for show, we should instantite manually for internal stuff.

2021-02-11 08:40 UTC, brizental commented on samples/qt-qml-app/metrics.yaml
> +$schema: moz://mozilla.org/schemas/glean/metrics/1-0-0
TIL!

2021-02-11 08:53 UTC, Dexterp37 commented on src/internal_pings.ts
> + * Pings initialized here should be defined in `./pings.yaml`
> 
> 
> That the pings defined here should be defined in pings.yaml. Not sure what is the confusion.

Well, the sentence was lacking the context you're providing below :)

> Autogenerating the internal metrics and pings is not a good idea here, we need a more robust and specific class than glean_parser provides (at least for metrics) and we would need to generate these files all the time... anyways would not play well with the development workflow IMO. I think glean_parser should stay as a user tool, not a glean internal development tool.

I'm not sure what you mean here. Why can't we dogfood?

2021-02-11 09:52 UTC, brizental commented on src/internal_pings.ts
> + * Pings initialized here should be defined in `./pings.yaml`
> I'm not sure what you mean here. Why can't we dogfood?

I tried it just now. The tl;dr; is: we can, but it is not so simple.

1. The `glean_parser` template I created was thought out to be used by a consumer of Glean
and not by Glean itself. Looking at an example:

```js
/* eslint-disable */

/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

"use strict";

// AUTOGENERATED BY glean_parser.  DO NOT EDIT.

// Global variable to use when in Qt/QML environments,
// where do not have access to the global object (i.e. window);
var gleanInternalMetrics;

// Universal Module Definition (UMD) template based on:
// https://github.com/umdjs/umd/blob/master/templates/returnExports.js
(function (root, factory) {
    if (typeof define === "function" && define.amd) {
        // AMD. Register as an anonymous module.
        define(["Glean"], factory);
    } else if (typeof module === "object" && module.exports) {
        // Node. Does not work with strict CommonJS, but
        // only CommonJS-like environments that support module.exports, like Node.
        module.exports = factory(require("glean"));
    } else if (typeof root === "undefined") {
        // In Qt/QML environments we can't change the global object from Javascript.
        // We will simply assing to a global variable in this case.
        gleanInternalMetrics = factory(Glean.Glean);
    } else {
        // Browser globals (root is window)
        if (!root["gleanAssets"]) {
            root["gleanAssets"] = {};
        }
        root["gleanAssets"]["gleanInternalMetrics"] = factory(root.Glean);
    }
})(typeof self !== "undefined" ? self : this, function(Glean) {
    return {
        /**
        * The name of the operating system.
        * Possible values:
        * Android, iOS, Linux, Darwin, Windows,
        * FreeBSD, NetBSD, OpenBSD, Solaris, unknown
        *
        * Generated from `os`.
        */
        os: new Glean._private.StringMetricType({
            category: "",
            name: "os",
            sendInPings: ["glean-client-info"],
            lifetime: "application",
            disabled: false,
        }, ),
    };
});
```

This is the branch we would fall on inside Glean.js:

```js
else if (typeof module === "object" && module.exports) {
    // Node. Does not work with strict CommonJS, but
    // only CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require("glean"));
}
```

Note that is assumes Glean is an installed package, named "glean". When we are inside Glean.js,
this assumption fails and this `require` statement returns `undefined` which will break everything.

2. The glean_parser template is a JS template, which means when we want to import it in Typescript,
Typescript is not too happy that it doesn't have type definitions. I have opened [a bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1692157) about that.

3. We would need to run the glean_parser command before all other commands, it is fast,
but even so it could get annoying. We could maybe write a script that checked if it is necessary
to run that command before doing that, but that is better as a follow up IMO (see also: https://github.com/mozilla/glean.js/pull/45#discussion_r574321319).

2021-02-11 10:00 UTC, Dexterp37 commented on src/internal_pings.ts
> + * Pings initialized here should be defined in `./pings.yaml`
Ok, let's file a bug about this and move on.

2021-02-11 10:00 UTC, Dexterp37 approved these changes

2021-02-11 10:06 UTC, merged