Bug 1681483 - Implement persistent storage for QML
mozilla/glean.js pull request #462
Opened 2021-06-23 13:13 UTC by brizental

### Pull Request checklist ###

- [x] **Quality**: Make sure this PR builds and runs cleanly.
  - Inside the `glean/folder`, run:
    - `npm run test` Runs _all_ tests
    - `npm run lint && npm run lint:circular-deps` Runs _all_ linters
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes a changelog entry to `CHANGELOG.md` or an explanation of why it does not need one
- [ ] **Documentation**: This PR includes documentation changes, an explanation of why it does not need that or a follow-up bug has been filed to do that work
  - Documentation should be added to [The Glean Book](https://mozilla.github.io/glean/book/index.html) when making changes to Glean's user facing API
    - When changes to the Glean Book are necessary, link to the corresponding PR on the [`mozilla/glean`](https://github.com/mozilla/glean) repository
  - Documentation should be added to [the Glean.js developer documentation](https://github.com/mozilla/glean.js/tree/main/docs) when making internal code changes

2021-06-23 13:14 UTC, brizental commented on glean/src/platform/qt/storage.ts
> +    return LocalStorage.LocalStorage.openDatabaseSync(
At the danger of showing my database ignorance, question: would it be better if I called this function only once instead of everytime I execute the query?

2021-06-23 13:17 UTC, brizental commented
Converted to draft because somehow running the QML tests make it so that the WebExt storage tests are not run (and also don't error, thus the green CI). 

This PR is ready for review on the QML side though.

2021-06-23 14:03 UTC, brizental commented
Ok, the Storage/WebExt error is not related, and actually might be happening for a while /o\ It is also happening on the events threshold PR.

Filed a bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1717845

2021-06-23 14:05 UTC, moz-glean commented
# Build size report

Merging https://github.com/mozilla/glean.js/pull/462 into [main](https://github.com/mozilla/glean.js) will:
* **Leave** the size of full **Web Extension** bundle **unchanged**.
* **Increase** the size of full **Qt/QML** bundle build by `4%`.

---

| | Current size | New size | Size increase |
|--:|:---:|:---:|:---:|
| **Web Extension** |
| core only | 45 KB | 45 KB | 📈 75 bytes |
| full bundle | 67 KB | 67 KB | 📈 75 bytes |
| **Qt/QML** |
| core only | 104 KB | 109 KB | 📈 4.4 KB |
| full bundle | 104 KB | 109 KB | 📈 4.4 KB |

2021-06-23 15:32 UTC, Dexterp37 requested changes

2021-06-23 15:32 UTC, Dexterp37 commented on glean/src/platform/qt/storage.ts
> +      // This allows for `REPLACE ITEM` to work.
Let's expand a bit: the "this" here is the unique index :)

2021-06-23 15:32 UTC, Dexterp37 commented on glean/src/platform/qt/storage.ts
> +    return LocalStorage.LocalStorage.openDatabaseSync(
From [Qt's sample](https://code.qt.io/cgit/qt/qtdeclarative.git/tree/examples/quick/localstorage/localstorage/Database.js?h=5.15#n63) it seems that it should be fine. The biggest I/O hit should be the first time this gets called, because the files get created.

Note that this [can throw](https://doc.qt.io/qt-5/qtquick-localstorage-qmlmodule.html#opendatabasesync): please handle accordingly.

2021-06-23 15:32 UTC, Dexterp37 commented on glean/src/platform/qt/storage.ts
> +      this.name, "1.0", `${this.name} Storage`, 1000000
Why did you pick this value as the estimated DB size?

2021-06-23 15:32 UTC, Dexterp37 commented on glean/src/platform/qt/storage.ts
> +        `REPLACE INTO ${this.tableName}(key, value) VALUES('${key}', '${value.replace("'", "''")}');`
Why can't we use `UPDATE` here? Any specific reason?

2021-06-23 15:32 UTC, Dexterp37 commented on glean/src/platform/qt/storage.ts
> +const SEPARATOR = "+";
Are you sure `#` can't be used? For labels we explicitly look at the last `#` because we know we could be using it :)

2021-06-23 15:34 UTC, brizental commented on glean/src/platform/qt/storage.ts
> +      this.name, "1.0", `${this.name} Storage`, 1000000
Because I copy pasted: https://doc.qt.io/qt-5/qtquick-localstorage-qmlmodule.html

2021-06-23 15:34 UTC, brizental commented on glean/src/platform/qt/storage.ts
> +        `REPLACE INTO ${this.tableName}(key, value) VALUES('${key}', '${value.replace("'", "''")}');`
Hm, no reason really. We can use update too.

2021-06-23 15:37 UTC, brizental commented on glean/src/platform/qt/storage.ts
> +const SEPARATOR = "+";
I did not test it, no. But if we did use `#`, then that would mean labeled stuff would be saved as:

```json
{
    "type": {
        "category.name": {
            "label": "value"
        }
    }
}
```

Instead of:

```json
{
    "type": {
        "category.name#label": "value"
    }
}
```

And that would cause problems.

2021-06-23 15:37 UTC, brizental commented on glean/src/platform/qt/storage.ts
> +const SEPARATOR = "+";
(Wouldn't it? /me goes check)

2021-06-24 08:00 UTC, Dexterp37 commented on glean/src/platform/qt/storage.ts
> +      this.name, "1.0", `${this.name} Storage`, 1000000
I think we can inspect the average size of the Glean DB for the mobile and pick the double of the 90 percentile or the 99p as a good starting value :-)

2021-06-24 08:01 UTC, Dexterp37 commented on glean/src/platform/qt/storage.ts
> +        `REPLACE INTO ${this.tableName}(key, value) VALUES('${key}', '${value.replace("'", "''")}');`
I think using UPDATE would allow us to remove the unique value index

2021-06-24 08:07 UTC, Dexterp37 commented on glean/src/platform/qt/storage.ts
> +const SEPARATOR = "+";
Wouldn't a more realistic index be something like `{ping}#{type}#{id}#{label}`?

Anyway, note that we already use `#` for names too. If we'll ever _split_ based on `#`, then using this as a separator would cause problems. Otherwise, I believe it should work. If we end up using `+` we need to make sure we won't allow it in metric names (I don't think we do, but we should make sure)

2021-06-24 09:46 UTC, brizental commented on glean/src/platform/qt/storage.ts
> +const SEPARATOR = "+";
Ah! I remembered wrong and [we actually use `/` for labels](https://github.com/mozilla/glean.js/blob/caa10fe041666306f2fdae8dc3e5006f80159c47/glean/src/core/metrics/types/labeled.ts#L76). So this character cannot be used as a separator here either. You are right, we use `#` for names e.g. [on the sequence number metric](https://github.com/mozilla/glean.js/blob/caa10fe041666306f2fdae8dc3e5006f80159c47/glean/src/core/pings/maker.ts#L33). That can't be a separator either. Finally,  [we use `.` for joining category and name](https://github.com/mozilla/glean.js/blob/caa10fe041666306f2fdae8dc3e5006f80159c47/glean/src/core/metrics/index.ts#L76). That can't be a separator.

I checked, for categories glean_parser allows [dotted_snake_case](https://github.com/mozilla/glean_parser/blob/main/glean_parser/schemas/metrics.2-0-0.schema.yaml#L28), and metric names [snake_case](https://github.com/mozilla/glean_parser/blob/main/glean_parser/schemas/metrics.2-0-0.schema.yaml#L24). Neither of them allow the `+` character, so we should be fine unless we decide to go adding more special characters to metric names we create internally. If we do something that breaks this storage implementation test should fail though (once we have Qt integration tests, at least /o\).

2021-06-24 10:16 UTC, Dexterp37 commented on glean/src/platform/qt/storage.ts
> +const SEPARATOR = "+";
Since you did this nice and thorough investigation, would you mind adding it to the glean dev docs?

2021-06-24 10:17 UTC, Dexterp37 commented on glean/src/platform/qt/storage.ts
> +const ESTIMATED_DATABASE_SIZE = 150 * 2 * 10**3; // 300Kb
Can you write a comment documenting how you got to this value?

2021-06-24 10:23 UTC, Dexterp37 commented on glean/src/platform/qt/storage.ts
> +      this.dbHandle = handle;
Why are we storing this internally? Can't we only rely on the returned state?

2021-06-24 10:29 UTC, brizental commented on glean/src/platform/qt/storage.ts
> +      this.dbHandle = handle;
This is just in case `openDatabaseSync` throws and then we can use the handle retrived on the previous call `dbHandle`. Not sure how common it is for this to throw, so just trying to do a best effort here.

2021-06-24 12:14 UTC, brizental commented on glean/src/platform/qt/storage.ts
> +const SEPARATOR = "+";
https://bugzilla.mozilla.org/show_bug.cgi?id=1718040

2021-06-24 13:22 UTC, Dexterp37 commented on glean/src/platform/qt/storage.ts
> +      this.dbHandle = handle;
But as the docs state, the handle might be invalid (the handle gets closed when garbage collection kicks in). Moreover, the reason why opening fails might invalidate that handle, too. I'd really just rely on the currently active handle.

2021-06-24 14:27 UTC, brizental commented on glean/src/platform/qt/storage.ts
> +      this.dbHandle = handle;
> I'd really just rely on the currently active handle.

That is what the code is doing right now. We always _attempt_ to get the handle when we call `this._dbHandle`. It's only in case that call fails that we fallback and use the handle we got from a previous call.

We can not do that, but then what should we do if we fail to get the handle?

2021-06-25 08:00 UTC, Dexterp37 commented on glean/src/platform/qt/storage.ts
> +      this.dbHandle = handle;
> We can not do that, but then what should we do if we fail to get the handle?

If we fail, I'm not sure getting a previous handle (which might be broken as well) is better. I would just do the same thing we do in glean-core when we fail with storage :)

2021-06-25 08:02 UTC, Dexterp37 approved these changes
r+, the handle thing can be done in a follow-up and reviewed by @badboy if needed.

2021-06-25 08:14 UTC, brizental commented on glean/src/platform/qt/storage.ts
> +      this.dbHandle = handle;
So, in glean-core, IIRC, [we bail initialization if we can't open the database](https://github.com/mozilla/glean/blob/1a8ad8003c220281e2f1cddc3b6aeabe7875cd35/glean-core/src/lib.rs#L271xf). If we are attempting to open it on every query execution that is not really possible. 

How about we return `undefined` if opening the database fails, instead of saving the handle and file a bug to record some metric on database errors, so we can understand better how many times does this error and then handle accordingly once we have that information?

2021-06-25 08:19 UTC, brizental commented on glean/src/platform/qt/storage.ts
> +      this.dbHandle = handle;
Ok, just saw the approval, neverming the above comment. Filed a bug for further investigation. https://bugzilla.mozilla.org/show_bug.cgi?id=1718213

2021-06-25 09:15 UTC, merged