Bug 1716724 - Implement new logic to sort events from different application runs
mozilla/glean.js pull request #526
Opened 2021-07-12 13:55 UTC by brizental

### Pull Request checklist ###

- [x] **Quality**: Make sure this PR builds and runs cleanly.
  - Inside the `glean/` folder, run:
    - `npm run test` Runs _all_ tests
    - `npm run lint && npm run lint:circular-deps` Runs _all_ linters
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes a changelog entry to `CHANGELOG.md` or an explanation of why it does not need one
- [ ] **Documentation**: This PR includes documentation changes, an explanation of why it does not need that or a follow-up bug has been filed to do that work
  - Documentation should be added to [The Glean Book](https://mozilla.github.io/glean/book/index.html) when making changes to Glean's user facing API
    - When changes to the Glean Book are necessary, link to the corresponding PR on the [`mozilla/glean`](https://github.com/mozilla/glean) repository
  - Documentation should be added to [the Glean.js developer documentation](https://github.com/mozilla/glean.js/tree/main/docs) when making internal code changes

2021-07-14 12:29 UTC, brizental commented on glean/src/metrics.yaml
> +        type: quantity
I left these here, but I kinda think we should not add them. These are internal Glean.js details, don't need to be called out here. WDYT?

2021-07-26 12:01 UTC, badboy requested changes
The code looks good, I left a couple of minor nits throughout the files (I hope they show up correctly).

I do have one request though before greenlighting that:
Can we add some more explicit tests for the timings of events?
I know in the proposal we had several scenarios sketched. We could reproduce those in the tests with explicitly chosen timestamps and then validate that the ping payload has the right times.
Right now we check that the timestamps are monotonically increasing, but don't check that the offsets are what we expect.

2021-07-26 12:42 UTC, brizental commented on glean/src/core/metrics/events_database.ts
> +function createDateObject(str = ""): Date {
Because in the places where we call this function, the value we pass to it might be undefined. In order not to have to add a default everytime I call it, I decided to just add a default here.

2021-07-26 12:56 UTC, badboy commented on glean/src/core/metrics/events_database.ts
> +function createDateObject(str = ""): Date {
Wait, if you pass undefined _explicitly_ it will fall back to the default value?

2021-07-26 13:22 UTC, brizental commented on glean/src/core/metrics/events_database.ts
> +function createDateObject(str = ""): Date {
Heh, yeap.

2021-07-26 13:43 UTC, badboy commented on glean/src/core/metrics/events_database.ts
> +function createDateObject(str = ""): Date {
Iiiiinteresting

2021-07-27 13:53 UTC, brizental commented on glean/src/core/metrics/events_database/index.ts
> +        await recordGleanRestartedEvent([ping]);
I debated not using `Context.startTime` when injecting the `restarted` event on the first recording for a given ping and instead doing `new Date()`. This way timestamp offsets on different sessions would be calculated based on the time of the recording of the first event, which is what we do for events before restarts.

I thought that would make it ~even more~ confusing in the code though, so I left it like this.

2021-07-27 13:53 UTC, brizental commented on glean/src/core/metrics/events_database/index.ts
> +      sortedEvents.shift();
Note: We only drop the first `glean.restarted` event, so it is possible to have stray `glean.restarted` events at the end of the `events` array. I wonder if it would be best to drop stray `restarts`. That can be done as follow-up though.

2021-07-29 13:33 UTC, badboy approved these changes
This looks pretty good now. Thanks for adding the additional tests.

Let's land it and take it to production!

2021-07-29 13:33 UTC, badboy commented on glean/src/core/metrics/events_database/index.ts
> +      // 1. The ping was already sent during this session and the events storare was cleared;
```suggestion
      // 1. The ping was already sent during this session and the events storage was cleared;
```

2021-07-29 13:33 UTC, badboy commented on glean/tests/unit/core/metrics/events_database.spec.ts
> +  it("events are correctly sorted if time decides to stand still throughout restarts", async function() {
Remind me: is the `glean.restarted` timer trimmed to minutes or is it to second precision?
If it's minute, this might occur easily because of using the app again within a minute, right?
So regardless second precision sounds more reasonable to me, unless there was some other reason

2021-07-29 13:33 UTC, badboy commented on glean/tests/unit/core/metrics/events_database.spec.ts
> +    ] = payload.events as JSONObject[];
Would this fail if there are more or less events in `payload.events`?
If not please add an explicit assert for the length.

2021-07-29 15:17 UTC, brizental commented on glean/tests/unit/core/metrics/events_database.spec.ts
> +  it("events are correctly sorted if time decides to stand still throughout restarts", async function() {
It's in milliseconds, actually. We just `toISOString` a `Date` object. This way it's easy to convert it back to a `Date` object from the string.

2021-07-29 15:18 UTC, brizental commented on glean/tests/unit/core/metrics/events_database.spec.ts
> +    ] = payload.events as JSONObject[];
If there are less, yes, this would fail. If there are more it depends, if the events are just appended to the env of the array this would pass, otherwise no.

2021-07-29 15:36 UTC, badboy commented on glean/src/core/metrics/events_database/index.ts
> +        await recordGleanRestartedEvent([ping]);
Hm, code-wise it could be as easy as passing `new Date()` here as a second argument and make `recordGleanRestartedEvent` take that as optional and use `Context.startTime` as the default. Not too complicated.

I _think_ this would make more sense.

Consider this:

1. App started. Idle for 10 minutes.
2. 1 Event (`a`) recorded. Initial `glean.restarted` added.
3. App stopped. Not touched for 10 minutes.
4. App started. `glean.restarted` inserted. Idle for 1 minute.
5. 1 Event (`b`) recorded
6. Ping submitted.

If using `Contex.startTime` then we have these events with timestamps (in minutes):

1. `a, ts=0`
2. `glean.restarted, ts=20` (10 minutes from initial start + 10 minutes stopped)
3. `b, ts=21`

With `new Date` we get:

1. `a, ts=0`
2. `glean.restarted, ts=10` (10 minutes stopped)
3. `b, ts=11`

First: is this example right? Please check if my thoughts make sense.
Second: 11 minutes difference between event `a` and event `b` is the "correct" thing here.

2021-07-29 15:36 UTC, badboy commented on glean/src/core/metrics/events_database/index.ts
> +      sortedEvents.shift();
yeah, do a follow-up.

2021-07-29 15:50 UTC, brizental commented on glean/src/core/metrics/events_database/index.ts
> +        await recordGleanRestartedEvent([ping]);
Yes, the code would be straight forward. What I think would make it confusing is having the `GLEAN_STARTUP_DATE_EXTRA_KEY`, but then record an arbitrary time in it. That makes it so that it is not really the `GLEAN_STARTUP_DATE_EXTRA_KEY` anymore, its more of a `GLEAN_REFERENCE_POINT_EXTRA_KEY`.

The first `glean.restarted` event is always trimmed from the payload, so that is more of an internal confusion. That would be less of a big deal if this implementation was not already super confusing.

Also, yes. Example is exactly what I had in mind :)

2021-07-29 16:30 UTC, brizental commented
# DATA REVIEW REQUEST

1. What questions will you answer with this data?

Was there an application restart between recorded events in a ping?

2. Why does Mozilla need to answer these questions? Are there benefits for users?
   Do we need this information to address product or business requirements?

Knowing when a restart happens in between events in a ping is useful
for sessionization of events at analysis time.

3. What alternative methods did you consider to answer these questions?
   Why were they not sufficient?

The current behaviour of the Glean SDKs is to send any ping that contains
events at startup. That is fine for the Glean-internal `events` ping, but is
unwanted behaviour for user defined pings, aka custom pings.

That is the current alternative. The `glean.restarted` event is necessary
in order to drop it, but retain the knowledge regarding whether there was a
restart between events. Additionally this alternative makes it more explicit
that a restart happened, while the current approach leaves it for the analyzer
to guess from shape of pings / submission_timestamps / other metrics
that a restart did happen.

See also: https://docs.google.com/document/d/1R-tIZYz4Izx8rDB_YUiJXU9Xtk8VcJoF8Pmhggps_GU/

4. Can current instrumentation answer these questions?

Sort of[^1] and at the cost of submitting custom pings at startup time.

[^1]: The current instrumentation does not _reliably_ answer the question about
whether a restart happened or not. For `events` pings, where the `restarted` ping reason
can be consulted to make sure the ping was sent due to a restart, yes it does. However,
for custom pings guess work is necessary to figure out that there was a restart,
since the `restarted` reason is dropped before ping submission, unless it is defined
as a known reason for the ping.

5. List all proposed measurements and indicate the category of data collection for each
   measurement, using the Firefox data collection categories found on the Mozilla wiki.

Measurement Name | Measurement Description | Data Collection Category | Tracking Bug
---------------- | ----------------------- | ------------------------ | ------------
glean.restarted | Event that signals an application restart. | 2 | [1716724](https://bugzilla.mozilla.org/show_bug.cgi?id=1716724)

6. Please provide a link to the documentation for this data collection which
   describes the ultimate data set in a public, complete, and accurate way.

This collection is Glean so is documented
[in the Glean Dictionary](https://dictionary.telemetry.mozilla.org).

7. How long will this data be collected?

This collection never expires.

8. What populations will you measure?

All channels, countries, and locales. No filters.

9. If this data collection is default on, what is the opt-out mechanism for users?

These collections are Glean. The opt-out can be found in the product's preferences.

10. Please provide a general description of how you will analyze this data.

Users analyzing events in custom pings will analyze this metric in a case-by-case basis.

11. Where do you intend to share the results of your analysis?

N/A

12. Is there a third-party tool (i.e. not Telemetry) that you
    are proposing to use for this data collection?

No.

2021-07-29 16:31 UTC, brizental commented
Hey @chutten pinging you here specifically for the data review :) Thanks!

2021-07-30 09:43 UTC, brizental commented on glean/src/core/metrics/events_database/index.ts
> +      sortedEvents.shift();
https://bugzilla.mozilla.org/show_bug.cgi?id=1723090

2021-07-30 12:46 UTC, chutten commented
@brizental Are you the individual responsible for the data collection over its non-expiring lifetime?

2021-07-30 12:51 UTC, brizental commented
> @brizental Are you the individual responsible for the data collection over its non-expiring lifetime?

Yes. Me, falling back to the Glean team if I am not available.

2021-07-30 13:25 UTC, chutten commented
DATA COLLECTION REVIEW RESPONSE:

    Is there or will there be documentation that describes the schema for the ultimate data set available publicly, complete and accurate?

Yes.

    Is there a control mechanism that allows the user to turn the data collection on and off?

Yes. This collection is Telemetry so can be controlled through Firefox's Preferences.

    If the request is for permanent data collection, is there someone who will monitor the data over time?

Yes, Bea Rizental is responsible.

    Using the category system of data types on the Mozilla wiki, what collection type of data do the requested measurements fall under?

Category 1, Technical.

    Is the data collection request for default-on or default-off?

Default on for all channels.

    Does the instrumentation include the addition of any new identifiers?

No.

    Is the data collection covered by the existing Firefox privacy notice?

Yes.

    Does the data collection use a third-party collection tool?

No.

---
Result: datareview+

2021-07-30 13:29 UTC, chutten approved these changes
(data-r+ specifically)

2021-08-02 12:33 UTC, brizental commented on glean/src/core/metrics/events_database/index.ts
> +        await recordGleanRestartedEvent([ping]);
11caecc

2021-08-02 12:41 UTC, moz-glean commented
# Build size report

Merging https://github.com/mozilla/glean.js/pull/526 into [main](https://github.com/mozilla/glean.js) will:
* **Increase** the size of full **Web Extension** bundle build by `3%`.
* **Increase** the size of full **Qt/QML** bundle build by `3%`.

---

| | Current size | New size | Size increase |
|--:|:---:|:---:|:---:|
| **Web Extension** |
| core only | 46 KB | 50 KB | 📈 3.1 KB |
| full bundle | 71 KB | 73 KB | 📈 2.4 KB |
| **Qt/QML** |
| core only | 115 KB | 119 KB | 📈 3.6 KB |
| full bundle | 115 KB | 119 KB | 📈 3.6 KB |

2021-08-02 12:44 UTC, merged