Bug 1702206: Refactor Uploader into class for external use
mozilla/glean.js pull request #534
Opened 2021-07-17 18:37 UTC by ChinYing-Li

### Pull Request checklist ###

- [x] **Quality**: Make sure this PR builds and runs cleanly.
  - Inside the `glean/` folder, run:
    - `npm run test` Runs _all_ tests
    - `npm run lint && npm run lint:circular-deps` Runs _all_ linters
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes a changelog entry to `CHANGELOG.md` or an explanation of why it does not need one
- [x] **Documentation**: This PR includes documentation changes, an explanation of why it does not need that or a follow-up bug has been filed to do that work
  - Documentation should be added to [The Glean Book](https://mozilla.github.io/glean/book/index.html) when making changes to Glean's user facing API
    - When changes to the Glean Book are necessary, link to the corresponding PR on the [`mozilla/glean`](https://github.com/mozilla/glean) repository
  - Documentation should be added to [the Glean.js developer documentation](https://github.com/mozilla/glean.js/tree/main/docs) when making internal code changes

This PR aims to tackle bug 1702206; no new test added but some test cases have been modified.
Please ignore my question on Bugzilla, as I now understand why this approach is preferred. PR ready for review, and will modify `CHANGELOG.md` if there's no problem. Thanks!

2021-07-19 08:08 UTC, brizental requested changes
Thanks for the work here @ChinYing-Li ! This looks great. I left some very minor comments, but otherwise this is good to go.

2021-07-19 08:08 UTC, brizental commented on glean/src/core/upload/uploader.ts
>  }
You can  make this whole constructor declaration more succint, with the following syntax:

```ts
export class UploadResult {
   constructor(
      // The status of an upload attempt
      readonly result: UploadResultStatus,
      // The status is only present if `result` is UploadResultStatus.Success
      readonly status?: number
   ): {}
}
```

This is equivalient to:


```ts
export class UploadResult {
  // The status is only present if `result` is UploadResultStatus.Success
  readonly status?: number;
  // The status of an upload attempt
  readonly result: UploadResultStatus;

  constructor(result: UploadResultStatus, status?: number) {
    this.result = result;
    this.status = status;
  }
}
```

2021-07-19 08:08 UTC, brizental commented on glean/tests/unit/platform/qt/uploader.spec.ts
> +import {DEFAULT_UPLOAD_TIMEOUT_MS, UploadResult, UploadResultStatus} from "../../../../src/core/upload/uploader";
nit: Space before `}`

2021-07-19 08:08 UTC, brizental commented on glean/tests/unit/platform/webext/uploader.spec.ts
> +import {UploadResult, UploadResultStatus} from "../../../../src/core/upload/uploader";
nit: Space after `{` and before `}`

2021-07-19 08:08 UTC, brizental commented on samples/web-extension/typescript/package.json
> +    "webpack-cli": "^4.7.2"
Hm, why are these changes part of this PR?

2021-07-19 08:08 UTC, brizental commented on CHANGELOG.md
> +* [#534](https://github.com/mozilla/glean.js/pull/534): Refactor Uploader into abstract class for external use
The changelog is aimed at users, so it's ideal to write the message here tailored for these readers. They don't necessarily have context related to internals and mostly care about how changes affect external APIs.

How about, something more like:

> Expose `Uploader` base class through `@mozilla/glean/<platform>/uploader` entry point.

WDYT?

2021-07-19 08:48 UTC, ChinYing-Li commented on samples/web-extension/typescript/package.json
> +    "webpack-cli": "^4.7.2"
I ran the sample to test out the change, and somehow `package.json` got modified? I will revert the change.

2021-07-22 13:58 UTC, brizental approved these changes
Thanks for working on this @ChinYing-Li ! Looks great :D

2021-07-26 09:26 UTC, merged