Draft: Bug 1716956: Initial attempt to implement metric type "StringList"
mozilla/glean.js pull request #614
Opened 2021-08-07 13:09 UTC by ChinYing-Li

### Pull Request checklist ###

- [ ] **Quality**: Make sure this PR builds and runs cleanly.
  - Inside the `glean/` folder, run:
    - `npm run test` Runs _all_ tests
    - `npm run lint` Runs _all_ linters
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes a changelog entry to `CHANGELOG.md` or an explanation of why it does not need one
- [x] **Documentation**: This PR includes documentation changes, an explanation of why it does not need that or a follow-up bug has been filed to do that work
  - Documentation should be added to [The Glean Book](https://mozilla.github.io/glean/book/index.html) when making changes to Glean's user facing API
    - When changes to the Glean Book are necessary, link to the corresponding PR on the [`mozilla/glean`](https://github.com/mozilla/glean) repository
  - Documentation should be added to [the Glean.js developer documentation](https://github.com/mozilla/glean.js/tree/main/docs) when making internal code changes

Currently one unit test case and schema test fails. Opening a draft and is not ready for review.

2021-08-12 17:50 UTC, brizental commented
Hey @ChinYing-Li , just FYI I am on PTO this week and will come back to review this PR on Monday! Thank you for seding this in and sorry for the delayed response 👋

2021-08-16 09:58 UTC, brizental reviewed
Great work here @ChinYing-Li ! This is definitely on the right path, nothing major is wrong and the apporach is correct. Left a few comments, let me know if you have any questions.

2021-08-16 09:58 UTC, brizental commented on glean/src/core/metrics/types/string_list.ts
> +    for (const s in v) {
This should be a  [for...of](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of) loop, otherwise `s` is the indexes in `v`, not the values.

2021-08-16 09:58 UTC, brizental commented on glean/src/core/metrics/types/string_list.ts
> +  static async _private_addUndispatched(instance: StringListMetricType, value?: string): Promise<void> {
The undispatched methods are only necessary for metric types that will be recorded internally by Glean. That is not the case for this metric type. In this case, please merge this method with the `add`. Same with `set`.

2021-08-16 09:58 UTC, brizental commented on glean/src/core/metrics/types/string_list.ts
> +    super("stringlist", meta);
```suggestion
    super("string_list", meta);
```

2021-08-16 09:58 UTC, brizental commented on glean/src/core/metrics/types/string_list.ts
> +  length: number;
Why is this a property on the metric type itself?

2021-08-16 09:58 UTC, brizental commented on glean/src/core/metrics/types/string_list.ts
> +    let i = 0;
nit: This variable can be declared inside the loop.

2021-08-16 09:58 UTC, brizental commented on glean/src/core/metrics/types/string_list.ts
> +    const truncatedList: string[] = [];
nit: Let's declare this variable right before the loop below, so it's closer to the place where it is used.

2021-08-16 09:58 UTC, brizental commented on glean/src/core/metrics/types/string_list.ts
> +    console.log(`Length of string list: ${this.length}`)
Letf over `console.log`?

2021-08-16 09:58 UTC, brizental commented on glean/src/core/metrics/types/string_list.ts
> +    if (isUndefined(value)) {
Let's make `value` a required argument so that it is not necessary to have this check here.

2021-08-16 09:58 UTC, brizental commented on glean/src/core/metrics/utils.ts
> +  "stringlist": StringListMetric,
```suggestion
  "string_list": StringListMetric,
```

2021-08-16 09:58 UTC, brizental commented on glean/tests/unit/core/metrics/stringlist.spec.ts
> +  it("attempt to add string to string list of maximum length logs an error", async function() {
```suggestion
  it("attempt to add string to string list of maximum length records an error", async function() {
```

2021-08-16 09:58 UTC, brizental commented on glean/tests/unit/core/metrics/stringlist.spec.ts
> +})
Make sure all the test cases covered on glean-core https://github.com/mozilla/glean/blob/3d0b2cc2ea0ce696e92cc8b30cb6f69d9f9a1056/glean-core/tests/string_list.rs are also covered here. If I understand correct, the only one missing here is `set_does_not_record_error_when_receiving_empty_list`.

2021-08-16 09:58 UTC, brizental commented on glean/src/core/metrics/types/string_list.ts
> +   */
Reminder to update all the function doc strings before taking this PR out of draft mode :)

2021-08-16 10:01 UTC, brizental commented
> Currently one unit test case and schema test fails. Opening a draft and is not ready for review.

Heh, just saw this comment. Left a review anyways, hope it is helpful.

Regarding the schema test, it's possible it is failing because of the `stringlist` -> `string_list` change I requested in the review. [The Glean schema](https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/18ae30533ca6b7235725c99fb272362b0dcee307/schemas/glean/glean/glean.1.schema.json#L360-L373) is expecting the payload to contain `string_list` with the underline and anything different should cause a schema error.

2021-08-21 19:01 UTC, ChinYing-Li commented on glean/src/core/metrics/types/string_list.ts
> +  static async _private_addUndispatched(instance: StringListMetricType, value?: string): Promise<void> {
Since `add` calls the async function `Context.metricsDatabase.transform`, should `add` and `set` be made async? I saw that other metric types does not have async `set`.

2021-08-21 21:38 UTC, ChinYing-Li commented
Without `async` means I have to write something like
```javascript
truncatedValule = "";
 const truncatedValuePromise = truncateStringAtBoundaryWithError(this, value, MAX_STRING_LENGTH);
truncatedValuePromise.then((v) => {
  truncatedValue = v;
});
```
However the code above led to failure of unit test case `attempt to add string to string list of maximum length records an error`: the empty string "" was inserted instead.

2021-08-21 21:48 UTC, ChinYing-Li commented on glean/src/core/metrics/types/string_list.ts
> +  static async _private_addUndispatched(instance: StringListMetricType, value?: string): Promise<void> {
IMO, it's better to keep the `static asyn` internal methods, so that we can maintain the coherence of the interface (let `add` and `set` be normal functions) and avoid lint error `Promises must be handled appropriately or explicitly marked as ignored `.

2021-08-23 09:49 UTC, brizental commented on glean/src/core/metrics/types/string_list.ts
> +  static async _private_addUndispatched(instance: StringListMetricType, value?: string): Promise<void> {
> Since add calls the async function Context.metricsDatabase.transform, should add and set be made async? I saw that other metric types does not have async set.

The body of public functions in MetricTypes need to be wrapped in a `dispatcher.launch` call, which returns `void`. They must never return a `Promise`, this is very important as we don't want users to have to `await` on any of Glean's public APIs.

> IMO, it's better to keep the static asyn internal methods, so that we can maintain the coherence of the interface (let add and set be normal functions)

Sure, this makes sense. You are right :)

> and avoid lint error Promises must be handled appropriately or explicitly marked as ignored .

As I mentioned above this functions must never return promises, so this should not happen.

2021-08-23 09:59 UTC, brizental commented
> Without `async` means I have to write something like
> 
> ```js
> truncatedValule = "";
>  const truncatedValuePromise = truncateStringAtBoundaryWithError(this, value, MAX_STRING_LENGTH);
> truncatedValuePromise.then((v) => {
>   truncatedValue = v;
> });
> ```

By wrapping the whole function body in a `dispatcher.launch` call, it will be inside an `async` function block so you can use `await` normally. You can see that pattern in action on the URL metric type `set` function (https://github.com/mozilla/glean.js/blob/main/glean/src/core/metrics/types/url.ts#L94-L113) or any other metric type.

The dispatcher orchestrates Glean's async tasks, so that they are run in the order the user called them. But that all happens in the background, without the user having to `await` on anything. That is a bit confusing, let me know if it's still unclear I am happy to try and clarify more :)

> However the code above led to failure of unit test cas

They failure is probably happening because the code is not using the dispatcher, so at the time the assertion is called the action that should precede has not completed yet.

2021-08-23 09:59 UTC, brizental requested changes

2021-08-23 09:59 UTC, brizental commented on glean/src/core/metrics/types/string_list.ts
> +    Context.metricsDatabase.record(this, metric);
The whole body needs to be wrapped in a `dispatcher.launch` call, like so:

```suggestion
Context.dispatcher.launch(async () => {
    if (!this.shouldRecord(Context.uploadEnabled)) {
      return;
    }

    if (value.length > MAX_LIST_LENGTH) {
      Context.errorManager.record(
        this,
        ErrorType.InvalidValue,
        `String list length of ${value.length} exceeds maximum of ${MAX_LIST_LENGTH}.`
      );
    }

    const truncatedList: string[] = [];
    const newLength = Math.min(value.length, MAX_LIST_LENGTH);
    for (let i = 0; i < newLength; ++i) {
      const truncatedString = truncateStringAtBoundaryWithError(this, value[i], MAX_STRING_LENGTH);
      truncatedString.then((v) => {
        truncatedList.push(v);
      });
    }
    const metric = new StringListMetric(truncatedList);
    Context.metricsDatabase.record(this, metric);
 });
```

2021-08-23 09:59 UTC, brizental commented on glean/src/core/metrics/types/string_list.ts
> +    if (!this.shouldRecord(Context.uploadEnabled)) {
Same comment regarding the `dispatcher.launch` as I left in the `set` function.

2021-08-23 11:41 UTC, ChinYing-Li commented on glean/src/core/metrics/types/string_list.ts
> +    Context.metricsDatabase.record(this, metric);
Hi @brizental , I just want to make sure that you still want me to merge `_private_addUndispatched` and `add`, is that correct? Or does it make more sense to keep `_private_addUndispatched`?

2021-08-23 11:55 UTC, brizental commented on glean/src/core/metrics/types/string_list.ts
> +    Context.metricsDatabase.record(this, metric);
On a second look, I keep my initial opinion that it is not necessary to have the undispatched methods.

2021-08-23 13:00 UTC, ChinYing-Li commented
@brizental I've addressed all the issues, and would be great if you can take a look. Thank you so much for the guidance!

2021-08-24 10:12 UTC, brizental requested changes
This is looking great, I left a few nits, but nothing major. Once these are adressed this should be good to go.

Thanks for the work here @ChinYing-Li !

2021-08-24 10:12 UTC, brizental commented on glean/src/core/metrics/types/string_list.ts
> +      let currentLen = -1;
Why did you choose to start this as `-1`? Why not `0`?

2021-08-24 10:12 UTC, brizental commented on glean/src/core/metrics/types/string_list.ts
> +      if (currentLen == MAX_LIST_LENGTH) {
```suggestion
      if (currentLen >= MAX_LIST_LENGTH) {
```

Just to be extra sure, hehe.

2021-08-24 10:12 UTC, brizental commented on glean/src/core/metrics/types/string_list.ts
> +          `String list length of ${currentLen}+1 exceeds maximum of ${MAX_LIST_LENGTH}.`
```suggestion
          `String list length of ${currentLen} exceeds maximum of ${MAX_LIST_LENGTH}.`
```
?

2021-08-24 10:12 UTC, brizental commented on glean/src/core/metrics/types/string_list.ts
> +export default StringListMetricType;
Missing blank line at the onf file.

2021-08-24 10:12 UTC, brizental commented on samples/web-extension/typescript/package-lock.json
> +<<<<<<< HEAD
Let's take these changes out of this PR.

2021-08-24 10:12 UTC, brizental commented on glean/tests/unit/core/metrics/string_list.spec.ts
> +});
Missing blank line at the end of file.

2021-08-24 10:12 UTC, brizental commented on glean/tests/unit/core/metrics/string_list.spec.ts
> +    }
This block can be replaced by:

```js
const testStringList = Array(MAX_LIST_LENGTH - 2).fill("test")
```

That is also a bit less confusing, IMO. It took me a while to understand why we have `i < MAX_LIST_LENGTH - 1`.

2021-08-24 11:13 UTC, ChinYing-Li commented on glean/src/core/metrics/types/string_list.ts
> +          `String list length of ${currentLen}+1 exceeds maximum of ${MAX_LIST_LENGTH}.`
`currentLen` is the size of the string list before pushing another string to it, so the error message should use `currentLen + 1`.

2021-08-24 11:59 UTC, brizental commented on glean/src/core/metrics/types/string_list.ts
> +          `String list length of ${currentLen}+1 exceeds maximum of ${MAX_LIST_LENGTH}.`
Ok, I see. In this case, the `+` needs to be inside the `{}`.

2021-09-01 09:58 UTC, brizental commented
Hey @ChinYing-Li I see you addressed the review comments, but there are three still missing :) Would you mind addressing those and rebasing this PR so I can merge? Thank you so much :)

Also, the `package-lock.json` can be dropped. That has already ben fixed in a different PR.

2021-09-01 15:50 UTC, ChinYing-Li commented
Hi @brizental , sorry for the delay! Please review and let me know if anything else needs to be fixed. Thank you.

2021-09-02 09:06 UTC, merged

2021-09-02 09:49 UTC, ChinYing-Li commented
Hi @brizental , Sure, I can update the Glean book!