Bug 1712920 - Implement rate limiting in ping upload
mozilla/glean.js pull request #658
Opened 2021-08-23 12:51 UTC by brizental

This actually fixes a bug: there was no code path to re-start the PingUploader dispatcher once it was stopped due to max recoverable error being hit. None of our consumers have updated yet,s o if I make a release after this is merged we should be fine.

### Pull Request checklist ###

- [x] **Quality**: Make sure this PR builds and runs cleanly.
  - Inside the `glean/` folder, run:
    - `npm run test` Runs _all_ tests
    - `npm run lint` Runs _all_ linters
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes a changelog entry to `CHANGELOG.md` or an explanation of why it does not need one
- [x] **Documentation**: This PR includes documentation changes, an explanation of why it does not need that or a follow-up bug has been filed to do that work
  - https://github.com/mozilla/glean/pull/1758

2021-08-23 12:58 UTC, brizental commented on glean/src/core/upload/index.ts
> +            `Pending pings will be processed in ${(remainingTime || 0) / 1000}s.`
I kinda of don't like this message, as it is promising something that is not true: the pings _may_ be processed after the remaining time, but it doesn't mean they will, there is no trigger that goes off once that time is over. 

On the other SDKs we do have one though, so I will file a bug to do the same here. See how that happens in the [Python](https://github.com/mozilla/glean/blob/main/glean-core/python/glean/net/ping_upload_worker.py#L156) or [Android](https://github.com/mozilla/glean/blob/main/glean-core/android/src/main/java/mozilla/telemetry/glean/scheduler/PingUploadWorker.kt#L120) SDKs.

Question is: is everyone confortable with the empty promise here until that is merged? I personally don't think it is a big deal, but best to flag it.

2021-08-23 13:14 UTC, brizental commented on glean/src/core/upload/index.ts
> +            `Pending pings will be processed in ${(remainingTime || 0) / 1000}s.`
https://bugzilla.mozilla.org/show_bug.cgi?id=1727076 filed.

2021-08-23 13:51 UTC, Dexterp37 commented on glean/src/core/upload/index.ts
> +            `Pending pings will be processed in ${(remainingTime || 0) / 1000}s.`
> Question is: is everyone confortable with the empty promise here until that is done? I personally don't think it is a big deal, but best to flag it.

I don't think it's a big deal.

2021-08-24 08:49 UTC, Dexterp37 requested changes

2021-08-24 08:49 UTC, Dexterp37 commented on glean/src/core/upload/rate_limiter.ts
> +  // This variant contains the remaining time (in milliseconds)
This is a bit confusing: the enum itself is not holding the remaining time in MS, it's just that we return the time from `getState`: could you clarify this a bit?

2021-08-24 08:49 UTC, Dexterp37 commented on glean/src/core/upload/rate_limiter.ts
> +  Stopped,
We seem to be returning the remaining time in this case, too: should we amend this comment or change `getState`?

2021-08-24 08:49 UTC, Dexterp37 commented on glean/src/core/upload/rate_limiter.ts
> +        remainingTime,
We're returning the remaining time here, do we need to fix the comment on the enum definition or remove this?

2021-08-24 08:49 UTC, Dexterp37 commented on glean/src/core/upload/rate_limiter.ts
> +    // It's very unlekily elapsed will be a negative number since we are using a monotonic timer
```suggestion
    // It's very unlikely elapsed will be a negative number since we are using a monotonic timer
```

2021-08-24 08:49 UTC, Dexterp37 commented on glean/src/core/upload/rate_limiter.ts
> +   * 1. It has never started;
Why is this the case? If it has never started, it should already be in the stopped state, right?

2021-08-24 09:00 UTC, brizental commented on glean/src/core/upload/rate_limiter.ts
> +  // This variant contains the remaining time (in milliseconds)
Ack, this is because I copy pasted this comment from Rust, where enums may hold data. Which is not the case for TypeScript. I'll reword it.

2021-08-24 09:01 UTC, brizental commented on glean/src/core/upload/rate_limiter.ts
> +  Stopped,
Nah, I don't think we need to mention the remaining time at all in these enum comments.

2021-08-24 09:01 UTC, brizental commented on glean/src/core/upload/rate_limiter.ts
> +        remainingTime,
Answered by the previous responses I think.

2021-08-24 09:02 UTC, brizental commented on glean/src/core/upload/rate_limiter.ts
> +   * 1. It has never started;
If it has never started it does not have a `startTime` so we need to generate it. I can reword it to say exactly this though. Full disclaimer, this was also copied from the Rust code, hehe. 

Maybe I should re-read these comments after sending the PR?!

2021-08-24 10:06 UTC, Dexterp37 approved these changes

2021-08-24 10:12 UTC, merged