Bug 1679375 - Implement a Storage that users the web ext storage API
mozilla/glean.js pull request #8
Opened 2020-12-07 09:02 UTC by brizental

This is a split off of #7, containing only the storage implementation for web extensions. This doesnt contain tests as I am still figuring out last issue with testing direcly on browsers. This might mean that there are bugs on this implementation, but since I have done manual testing, no big changes should come on the tests PR and the overall approach will still be the same.

2020-12-07 09:20 UTC, Dexterp37 requested changes

2020-12-07 09:20 UTC, Dexterp37 commented on src/storage/index.ts
> +export function isStorageValue(v: unknown): v is StorageValue {
Can you document what's the purpose of this?

2020-12-07 09:20 UTC, Dexterp37 commented on src/storage/index.ts
> +  return true;
Do we ever get here?

2020-12-07 09:20 UTC, Dexterp37 commented on src/storage/index.ts
> +  }
```suggestion
  if (isUndefined(v) || isString(v)) {
    return true;
  } 
  
  if (isObject(v)) {
    for (const key in v) {
      return isStorageValue(v[key]);
    }
  }

  return false;
```

This seems slightly more readable. What do you think?

2020-12-07 09:20 UTC, Dexterp37 commented on src/storage/persistent/webext.ts
> + * [`mozilla/webextension-polyfill`](https://github.com/mozilla/webextension-polyfill).
Do we need this here? Should we move this at README level? It will apply to everything that uses `browser`. Moreover, this has less to do with Chrome and more to do with "Chromium-based browsers"

2020-12-07 09:20 UTC, Dexterp37 commented on src/storage/persistent/webext.ts
> +    debugger;
stray ?

2020-12-07 11:43 UTC, brizental commented on src/storage/index.ts
> +  return true;
Not that I know of, but Typescript complains about it. It gives an error that goes more or less "can't return undefined if return value is bool" /o\

2020-12-07 11:44 UTC, brizental commented on src/storage/persistent/webext.ts
> + * [`mozilla/webextension-polyfill`](https://github.com/mozilla/webextension-polyfill).
Yeap good point. I'll move it.

2020-12-07 11:49 UTC, Dexterp37 commented on src/storage/index.ts
> +  return true;
Does reshaping it as recommended in the other comment help?

2020-12-08 16:11 UTC, brizental commented on src/storage/index.ts
> +  return true;
Yes, it does :)

2020-12-08 16:15 UTC, brizental commented on src/storage/persistent/webext.ts
> + * [`mozilla/webextension-polyfill`](https://github.com/mozilla/webextension-polyfill).
So, I was going to make this change, but as is, our README.md is not really meant for this type of information. 

On the proposal we talked about having Glean.js information on the Glean Book, in practice I am not really sure how that will work yet. For brevity's sake, how about we leave this here for now (since this is the only code that it will appy to ATM, anyways) and deal with the whole documentation issue later? 

I'll make sure to file a follow up to define how we will merge Glean.js with Glean SDK documentation, if you agree.

2020-12-08 16:16 UTC, brizental commented on src/storage/persistent/webext.ts
> + * [`mozilla/webextension-polyfill`](https://github.com/mozilla/webextension-polyfill).
I'll still leave the change about "Chromium based browsers"

2020-12-08 16:59 UTC, brizental commented
The check-size job will fail because it will try to run the new build:webext command on main which doesn't have it yet. I propose we ignore that failure for now.

2020-12-08 16:59 UTC, brizental commented on bin/build-size-check.sh
> +# we should find a better way to deal with that though.
Self-reminder to file a follow-up for this.

2020-12-09 09:37 UTC, Dexterp37 requested changes

2020-12-09 09:37 UTC, Dexterp37 commented on bin/build-size-check.sh
> +# we should find a better way to deal with that though.
Let's file a bug and add the bug number here, please :)

2020-12-09 09:37 UTC, Dexterp37 commented on src/index.ts
> +);
Stray log?

2020-12-09 09:37 UTC, Dexterp37 commented on src/storage/index.ts
> +export type StorageValue = null | undefined | string | StorageObject;
Why do we need `null` here, too?

2020-12-09 09:37 UTC, Dexterp37 commented on webpack.config.qt.js
> +      // TODO: This is temporary until we actually have a persistent storage impl for Qt.
Let's file a bug about this and add the bug number here please.

2020-12-09 09:40 UTC, brizental commented on src/storage/index.ts
> +export type StorageValue = null | undefined | string | StorageObject;
This was a workaround for me to be able to create a query that has `null` as default for the web ext storage. When running the tests this morning I actually realized this causes a bug, I'll send a commit removing this, shortly.

2020-12-09 09:40 UTC, brizental commented on src/index.ts
> +);
Oops.

2020-12-09 10:31 UTC, brizental commented on src/index.ts
> +);
Hm, sorry actually there are not stray. If I leave the imports unused I realized webpacks doesn't include them in the final bundle. I will leave a comment about that though, to be clear.

2020-12-09 10:36 UTC, brizental commented on src/storage/persistent/webext.ts
> +      if (!isUndefined(response) && !isString(response)) {
Typescript complains about not being sure that `response` is not null with only the `isObject` check... `isUndefined` + `isString` do the trick though... go figure.

2020-12-09 10:37 UTC, brizental commented on src/storage/persistent/webext.ts
> +type WebExtStoreQuery = { [x: string]: { [x: string]: null; } | null; };
This is what I was trying to avoid with adding `null` to StorageValue. No surprise that introduces bugs since it then allows users to save `null` values to the Storage.

2020-12-09 10:38 UTC, brizental commented on src/storage/persistent/webext.ts
> -    if (isStorageValue(store) && isObject(store)) {
No need to check here since _testOnly_getWholeStore already returns a StorageObject.

2020-12-09 10:39 UTC, brizental commented on src/storage/persistent/webext.ts
>      const store = await this._testOnly_getWholeStore();
Question, is it to terrible to use this test function inside the actual code. I wondered about changing its name to _getWholeStore, but then it wouldn't be clear it is supposed to be used for tests?

2020-12-09 11:18 UTC, Dexterp37 commented on src/index.ts
> +);
oh, that's interesting. Can you file a follow-up bug to investigate this? I'm fairly sure there's some option to make Webpack not do that.

2020-12-09 11:21 UTC, Dexterp37 approved these changes
r+wc

2020-12-09 11:21 UTC, Dexterp37 commented on src/index.ts
> +);
Let's add the bug number to this commet please.

2020-12-09 11:21 UTC, Dexterp37 commented on src/storage/persistent/webext.ts
>      const store = await this._testOnly_getWholeStore();
It is terrible :) Make it `_getWholeStore` if you're relying on it internally.

2020-12-09 12:47 UTC, brizental commented on src/index.ts
> +);
I am not sure it would be worth the effort looking into this. I am only doing it now so that these modules are added to the final bundle and the size increase is added to the size comment, so that we keep track. All of this goes away when we are done with milestone 1 and overall not including unused imports to the bundle is IMO the preferred behaviour in the long run.

2020-12-09 13:19 UTC, merged