Bug 1726726 - Implement a Store for the web platform
mozilla/glean.js pull request #898
Opened 2021-10-25 13:57 UTC by brizental

### Pull Request checklist ###

- [x] **Quality**: Make sure this PR builds and runs cleanly.
  - Inside the `glean/` folder, run:
    - `npm run test` Runs _all_ tests
    - `npm run lint` Runs _all_ linters
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes a changelog entry to `CHANGELOG.md` or an explanation of why it does not need one
- [x] **Documentation**: This PR includes documentation changes, an explanation of why it does not need that or a follow-up bug has been filed to do that work
  - https://bugzilla.mozilla.org/show_bug.cgi?id=1736352

2021-11-03 13:10 UTC, Dexterp37 requested changes

2021-11-03 13:10 UTC, Dexterp37 commented on glean/src/platform/browser/web/storage.ts
> +        const store = transaction?.objectStore(STORE_NAME);
I would have expected the `?` to not be required here, given the check on line 74!

2021-11-03 13:10 UTC, Dexterp37 commented on glean/src/platform/browser/web/storage.ts
> +        // We want this to work in Node.js **only** for testing purposes.
What do you mean here? What's `self`?

2021-11-03 13:29 UTC, brizental commented on glean/src/platform/browser/web/storage.ts
> +        const store = transaction?.objectStore(STORE_NAME);
Tell that to the typeScript checker!

2021-11-03 13:29 UTC, brizental commented on glean/src/platform/browser/web/storage.ts
> +        const store = transaction?.objectStore(STORE_NAME);
(Jokes aside, maybe this is leftover from developement. I'll check if TS really complains).

2021-11-04 08:41 UTC, Dexterp37 approved these changes

2021-11-04 09:52 UTC, merged