Bug 1679375 - Implement the base of the metrics database module
mozilla/glean.js pull request #9
Opened 2020-12-10 16:30 UTC by brizental

As was described in the proposal, the database module will differ from the glean-core database module.

While it will serve as an abstraction layer over the underlying storage, it will also be the interface to retrive the ping payload data from the storage. This is a bit easier for Glean.js, because the data is saved already in the format that is expected by the ping schema.

I will leave comments on the code about some doubts that lingered after I was finished with this implementation.

2020-12-10 16:37 UTC, brizental commented on src/database.ts
> +export interface PingPayload {
The PingPayload will evolve as we add more metrics. I hope that we can use it to validate that it only contain valid metrics and that the metrics payloads are correct. I did not add that to this PR because we have no metrics yet.

2020-12-10 16:37 UTC, brizental commented on src/database.ts
> +      console.error(`Unexpected value found for metric ${metric}: ${JSON.stringify(value)}. Clearing.`);
Please let me know what you think about this. This is JSland and anyone can do anything to our data, I decided to simply delete if we find something that is not of the expected format.

2020-12-10 16:37 UTC, brizental commented on src/database.ts
> +   * the whole ping payload for that lifetime will be thrown away.
Now, this I am not so sure. We probably should only delete the metrics that are incorrect, right? Also, what if we end up deleting stuff like `first_run_date` or `client_id`? This is possible although unlikely, again: JSland.

I purposefully did not rabbit hole into this for this PR, but do let me know your thoughts I think this will result in new bugs to figure out what  to do with unexpected data in the storage.

2020-12-10 17:03 UTC, brizental commented
FYI: CI didn;t run for this Pr because it was not set up to run for PRs from forks. I changed that and it should run for next commits.

2020-12-14 09:22 UTC, Dexterp37 requested changes

2020-12-14 09:22 UTC, Dexterp37 commented on src/database.ts
> +  if (isObject(v)) {
To reduce indentation, privilege early returns. For example, you could change this by doing:

```js
if (!isObject(v)) {
  return false;
}

for (...)
```

2020-12-14 09:22 UTC, Dexterp37 commented on src/database.ts
> + * @param v The value to verify
Please document the return value (even though it's trivial).

2020-12-14 09:22 UTC, Dexterp37 commented on src/database.ts
> + *      "metricCategory?.metricName": metricPayload
Why the question mark between the category and the name?

2020-12-14 09:22 UTC, Dexterp37 commented on src/database.ts
> +      return `${metric.category}.${metric.name}`;
You would probably want a method on the `Metric` called `id`, because `category.name` is the id. Each metric will know how to build the id, and the database knows how to map ids to keys.

2020-12-14 09:22 UTC, Dexterp37 commented on src/database.ts
> +    if (!metric.disabled) {
To reduce indentation, privilege early returns:

```js
if (metric.disabled) {
  return;
}
```

2020-12-14 09:22 UTC, Dexterp37 commented on src/database.ts
> +    if (!metric.disabled) {
I'd privilege the early return here too, to improve the readability of the code below.

2020-12-14 09:22 UTC, Dexterp37 commented on src/database.ts
> +            throw new Error(`Unexpected value found for metric ${metric}: ${JSON.stringify(v)}.`);
Does this mean our specific metrics APIs will potentially throw? If so, this could mean breaking the user's functionalities. The Glean SDK intentionally avoids this, I believe we should do the same.

2020-12-14 09:22 UTC, Dexterp37 commented on src/database.ts
> +      console.error(`Unexpected value found for metric ${metric}: ${JSON.stringify(value)}. Clearing.`);
I think this makes sense. But why is an object an invalid value here?

2020-12-14 09:22 UTC, Dexterp37 commented on src/database.ts
> +   * the whole ping payload for that lifetime will be thrown away.
Yeah, I believe we should only delete the specific value that's not expected and leave the rest alone.

2020-12-14 09:22 UTC, Dexterp37 commented on src/database.ts
> +    this.pingStore = new PersistentStore("ping");
Since we'll likely be storing pings in a  `PersistentStorage` as well, does it make sense to have more explicit names for keys, e.g. "pingLifetimeMetrics"?

2020-12-14 09:22 UTC, Dexterp37 commented on src/database.ts
> +    // because it is the one that will probably have more data since it is the default.
And what difference does this make? :)

2020-12-14 09:22 UTC, Dexterp37 commented on src/database.ts
> +   *          `undefined` in case the ping doesn't contain any recorded metrics.
The function returns either `{}` or `undefined`. I think we should settle on one :)

2020-12-14 09:22 UTC, Dexterp37 commented on src/database.ts
> +      return;
This will return `undefined`, but we're also returning `{}` above. How do you want this API to behave?

2020-12-14 09:22 UTC, Dexterp37 commented on src/database.ts
> +   *        If not provided, data for all lifetimes will be cleared.
When do we delete data for all the stores?

I'd rather have a separate function just to do that, to make sure we don't mistakenly clear the all data when we don't want to.

2020-12-14 09:22 UTC, Dexterp37 commented on src/metrics/index.ts
> +    if (meta.category) this.category = meta.category;
Can we retain the same style that we used in the rest of the code?

```suggestion
    if (meta.category) {
      this.category = meta.category;
    }
```

2020-12-14 09:22 UTC, Dexterp37 commented on src/metrics/index.ts
> +  constructor(type: string, meta: CommonMetricData) {
Can we add a computed property called `id`?

2020-12-14 09:22 UTC, Dexterp37 commented on tests/database.spec.ts
> +describe("Database", function() {
Did you make sure to port back all the applicable tests from the Glean SDK related module?

2020-12-14 09:39 UTC, brizental commented on src/database.ts
> + * We have one store such in format for each lifetime: user, ping and application.
```suggestion
 * We have one store in this format for each lifetime: user, ping and application.
```

2020-12-14 09:39 UTC, brizental commented on src/storage/utils.ts
> +    target[finalKey] = transformFn(undefined);
```suggestion
    target[finalKey] = transformFn();
```

2020-12-14 09:39 UTC, brizental commented on src/database.ts
> + *      "metricCategory?.metricName": metricPayload
The question mark means that we may not have a category. This will go away when I move the identifier building logic to the metric code anyways.

2020-12-14 09:39 UTC, brizental commented on src/database.ts
> +            throw new Error(`Unexpected value found for metric ${metric}: ${JSON.stringify(v)}.`);
Nope, I changed the update function to expect errors from this transformation function. It will catch this error and ignore the incorrect value if it happens.

2020-12-14 09:39 UTC, brizental commented on src/database.ts
> +      console.error(`Unexpected value found for metric ${metric}: ${JSON.stringify(value)}. Clearing.`);
I am assuming for now that metric payloads are be strings (or undefined if it hasn't been recorded yet). When we start having actual metrics we will probably have a union type `MetricPayload` with the possible metric payloads and here we will change this conditional to `isMetricPayload`.

2020-12-14 09:39 UTC, brizental commented on src/database.ts
> +   * the whole ping payload for that lifetime will be thrown away.
I agree, would mind if I made this into a folow up though? I think there is a rabbit hole potential here, I am not sure what we should do for example if the problematic value is a user lifetime metric, or a key metric such as client_id. This is not as simple as just delete whatever is wrong.

2020-12-14 09:39 UTC, brizental commented on src/database.ts
> +   *          `undefined` in case the ping doesn't contain any recorded metrics.
Argh, this was a mistake, it this it is best to return `undefined` when there are no metrics... Then callers can just do `if (ping) { ... }`. `{}` is a truthy value.

2020-12-14 09:39 UTC, brizental commented on src/database.ts
> +    // because it is the one that will probably have more data since it is the default.
Less iterations, because we don't iterate on the store that probably has the most entries. It's not a big deal, I can remvoe the comment so as not to make it a big deal :D

2020-12-14 09:39 UTC, brizental commented on src/database.ts
> +      return;
Yes, that was mistake as I said above... Nice catch though.

2020-12-14 09:39 UTC, brizental commented on src/database.ts
> +   *        If not provided, data for all lifetimes will be cleared.
> When do we delete data for all the stores?

When upload is disabled.

I agree about creating adifferent function for that though.

2020-12-14 09:39 UTC, brizental commented on tests/database.spec.ts
> +describe("Database", function() {
Good point, I didn't check.

2020-12-14 10:00 UTC, Dexterp37 commented on src/database.ts
> +            throw new Error(`Unexpected value found for metric ${metric}: ${JSON.stringify(v)}.`);
Cool, ok then!

2020-12-14 10:01 UTC, Dexterp37 commented on src/database.ts
> +   * the whole ping payload for that lifetime will be thrown away.
Ok, that's fine: let's file a follow-up .

2020-12-14 11:03 UTC, brizental commented on src/database.ts
> +   *          `undefined` in case the ping doesn't contain any recorded metrics.
Hm, actually taking a closer look I realized there is no mistake, the function doesn't ever return an empty object.

The inner function I defined `getAndValidatePingData` does, but the actual `getPing` function only checks and if the ping object is empty it returns undefined.

2020-12-14 11:05 UTC, Dexterp37 commented on src/database.ts
> +   *          `undefined` in case the ping doesn't contain any recorded metrics.
The two returns [here](https://github.com/mozilla/glean.js/pull/9/files/7b428a6d8d680042f9ef8ea78e2e24d7ea80301d#diff-724f334a2b47a5e7cbcab252ce04fc232071d0bc058c96ed6fd4ac96e5dff308R185-R191) explicitly return `{}`?

2020-12-14 11:13 UTC, brizental commented on src/database.ts
> +   *          `undefined` in case the ping doesn't contain any recorded metrics.
Yup, but they are inside the inner function `getAndValidatePingData`. `getPing` returns [here](https://github.com/mozilla/glean.js/pull/9/files/7b428a6d8d680042f9ef8ea78e2e24d7ea80301d#diff-724f334a2b47a5e7cbcab252ce04fc232071d0bc058c96ed6fd4ac96e5dff308R218) and it checks if the object is empty before doing so.

2020-12-14 11:16 UTC, Dexterp37 commented on src/database.ts
> +   *          `undefined` in case the ping doesn't contain any recorded metrics.
SHISH. Can we please take that helper function out ? :)

2020-12-14 11:17 UTC, brizental commented on src/database.ts
> +   *          `undefined` in case the ping doesn't contain any recorded metrics.
Heh, I already did. I was just waiting for that request :D

2020-12-14 11:33 UTC, brizental commented on src/database.ts
> +  if (isObject(v)) {
If I do this for this specific case, Typescript complains that `v` may not be an object...

2020-12-14 11:36 UTC, brizental commented on tests/database.spec.ts
> +describe("Database", function() {
I checked and this suite cover all the cases covered by the suite in glean-core. We of course don't have coverage for the `remove_metric` function because I didn't add it to the Database for now (it is only necessary for experiments).

2020-12-14 11:39 UTC, brizental commented on tests/database.spec.ts
> +      assert.strictEqual(true, isValidPingPayload({ "string": {} }));
Hey Alessio, would you mind confirming that this should actually be an invalid payload? I will file a follow up to fix the `delete` function in case that is the case.

2020-12-14 11:39 UTC, Dexterp37 commented on src/database.ts
> +  if (isObject(v)) {
Ok leave it be

2020-12-14 11:41 UTC, Dexterp37 commented on tests/database.spec.ts
> +      assert.strictEqual(true, isValidPingPayload({ "string": {} }));
What's valid or not is dictated by the Glean schema. You can check how validation is performed in the SDK and apply schema validation here, too: we don't need to reinvent the wheel :)

2020-12-14 12:15 UTC, brizental commented on tests/database.spec.ts
> +      assert.strictEqual(true, isValidPingPayload({ "string": {} }));
I have looked at the schema, but it is still unclear to me wether a metric type containing an empty object is considered valid. I _think_ so, but I just wanted to confirm :)

2020-12-14 12:25 UTC, brizental commented on src/database.ts
> +   * the whole ping payload for that lifetime will be thrown away.
https://bugzilla.mozilla.org/show_bug.cgi?id=1682273

2020-12-14 13:05 UTC, Dexterp37 commented on tests/database.spec.ts
> +      assert.strictEqual(true, isValidPingPayload({ "string": {} }));
I think so too, but my point is: we shouldn't "know" :-) Let's have a test running the schema in a validator :) Can you file a follow-up?

2020-12-14 13:09 UTC, brizental commented on tests/database.spec.ts
> +      assert.strictEqual(true, isValidPingPayload({ "string": {} }));
Ah! I see! That is a task for after we implement the ping maker, but I'll still file that bug :)

2020-12-14 13:11 UTC, Dexterp37 approved these changes
r+wc

2020-12-14 13:11 UTC, Dexterp37 commented on src/database.ts
> +    debugger;
Stray `debugger` statement :)

2020-12-14 13:11 UTC, Dexterp37 commented on src/database.ts
> +      return;
I'm still a bit puzzled by this, but we can revisit later: promises can be resolved or rejected, so maybe we can just assume that if it is resolved it has a value, otherwise rejected? Nothing to do now.

2020-12-14 13:12 UTC, brizental commented on src/database.ts
> +    debugger;
AAAAAAAAAAAAA 🤦‍♀️

2020-12-14 13:16 UTC, brizental commented on src/database.ts
> +      return;
Yeah, I considered just leaving the data there. But that would just mean this would fail until we record/transform again, because we leave the corrupted data there...

2020-12-14 13:19 UTC, brizental commented on src/database.ts
> +    debugger;
Added a lint rule to check for these...

2020-12-14 13:24 UTC, brizental commented on tests/database.spec.ts
> +      assert.strictEqual(true, isValidPingPayload({ "string": {} }));
https://bugzilla.mozilla.org/show_bug.cgi?id=1682282

2020-12-14 13:25 UTC, brizental commented on src/database.ts
> +      return;
We can keep up this discussion on the bug I opened to investigate the best behaviour for this :)

2020-12-14 13:25 UTC, merged