Bug 1689547 - Create plugin / events infrastructure and define `afterPingCollection` event
mozilla/glean.js pull request #94
Opened 2021-03-03 14:02 UTC by brizental

2021-03-03 14:41 UTC, Dexterp37 requested changes

2021-03-03 14:41 UTC, Dexterp37 commented on glean/src/core/config.ts
> +  // Optional list of plugins to instrument the current Glean instance.
```suggestion
  // Optional list of plugins to enable in the current Glean instance.
```

2021-03-03 14:41 UTC, Dexterp37 commented on glean/src/core/config.ts
> +import GleanEvents from "./events";
Why do you need this?

2021-03-03 14:41 UTC, Dexterp37 commented on glean/src/core/events.ts
> +export const AfterPingCollection: GleanEvent<[PingPayload], Promise<JSONObject>> = {
Can you document what's this? When is this called? What's it for?

2021-03-03 14:41 UTC, Dexterp37 commented on glean/src/core/glean.ts
> +          `Attempted to register plugin '${plugin.name}', which instruments the event '${plugin.event}'.`,
Mh, what do you mean by "instrument"? We usually use this term to mean "add something to measure".

2021-03-03 14:41 UTC, Dexterp37 commented on glean/src/core/pings/maker.ts
> +  const modifiedPayload = await Glean.triggerEvent(AfterPingCollection, collectedPayload);
We should consider (not in this PR) a different way to inject the dependency here, reducing the calls to the Glean object.

2021-03-03 14:41 UTC, Dexterp37 commented on glean/src/core/pings/maker.ts
> +    payload = collectedPayload;
```suggestion
  const modifiedPayload = await Glean.triggerEvent(AfterPingCollection, collectedPayload) ?? collectedPayload;
```

What about this?

2021-03-03 14:41 UTC, Dexterp37 commented on glean/tests/core/pings/maker.spec.ts
> +    await Glean.testUninitialize();
I wish we could just test  this in isolation. We might want to reconsider how we propagate our dependencies within Glean.js :(

2021-03-03 15:07 UTC, brizental commented on glean/src/core/pings/maker.ts
> +    payload = collectedPayload;
Much better.

2021-03-03 15:14 UTC, brizental commented on glean/src/core/glean.ts
> +          `Attempted to register plugin '${plugin.name}', which instruments the event '${plugin.event}'.`,
Hum, maybe I am using this word wrong... _checks wikipedia_ ... 100% I am using it wrong 🆘 Maybe I want "listens to"?

2021-03-03 15:18 UTC, brizental commented on glean/src/core/events.ts
> +export const AfterPingCollection: GleanEvent<[PingPayload], Promise<JSONObject>> = {
So, this is here to define:

- The type of the context provided by this event (`[PingPayload]`);
- The type of the result expected from this event (`[Promise<JSONObject>]`);
- The name of this event.

This way, when we define a plugin like this `class MyPlugin extends GleanPlugin<typeof AfterPingCollection>` the `action` in this plugin will already expected the correct arguments and return type defined by the event.

2021-03-03 15:21 UTC, brizental commented on glean/src/core/pings/maker.ts
> +  const modifiedPayload = await Glean.triggerEvent(AfterPingCollection, collectedPayload);
I considered making events completely unaware of the Glean singleton, but didn't try that out. I do think if we are going to go that way it should be now, otherwise we will be a bit stuck.

Let me attempt that and open an alternate to this PR with the different approach. I did not go that way before, because it would be quite different from what I defined in the proposal for this, but there is no harm in testing.

2021-03-03 15:23 UTC, brizental commented on glean/src/core/config.ts
> +import GleanEvents from "./events";
They are types, we pass plugins through the `ConfigurationInterface` to `Glean.initialize`, and this is here to help define exactly _what_ we are passing through that property.

2021-03-03 15:25 UTC, brizental commented on glean/src/core/config.ts
> +import GleanEvents from "./events";
`GleanEvents` is a union of all the possible GleanEvents types (not a union right now since we only defined one event, but you get the gist). And `GleanPlugin` is the type of the accepted plugin class. Each plugin is always attached to a type of event. To ensure we only accept plugins that listen to valid Glean events, the final type for the `plugins` property is `GleanPlugin<GleanEvents>[]`.

2021-03-03 15:26 UTC, brizental commented on glean/src/core/glean.ts
> +          `Attempted to register plugin '${plugin.name}', which instruments the event '${plugin.event}'.`,
Thankfully I can always claim that English is not my first language 🥇

2021-03-04 15:25 UTC, brizental commented
Closing in favour of #95

2021-03-04 15:25 UTC, closed without merging