Bug 1689547 - First attempt at providing a ping encryption plugin
mozilla/glean.js pull request #96
Opened 2021-03-04 16:16 UTC by brizental

Opening this as a draft to get feedback on the encryption implementation.

2021-03-04 16:17 UTC, brizental commented on glean/src/plugins/encryption.ts
> +    const encodedPayload = await new CompactEncrypt(encoder.encode(JSON.stringify(payload)))
Question 1: `payload` comes as an object, it is correct that I stringify it?

2021-03-04 16:19 UTC, brizental commented on glean/src/plugins/encryption.ts
> +      .setProtectedHeader({ kid: this.jwk.kid })
Question 2: I am setting this header as described in the proposal:
> Since JSON is the supported transport for our data ingestion platform, the encrypted payload will be in the JWE Compact Serialization format and must include a key id (kid) header identifying the public key used for encryption. 

I saw in the example keys you sent me that the keys don't have this headers though. If this key is required, should I validate that the JWK contains all the expected keys upon instantiation?

2021-03-04 16:21 UTC, brizental commented on glean/src/plugins/encryption.ts
> +  constructor(readonly jwk: JWK) {
I am using the provided JWK type from jose (https://github.com/panva/jose/blob/main/src/types.d.ts#L10-L68), all the properties are optioonal on it. Are we requiring any specific properties and should I validate that they exist before instantiation?

2021-03-04 16:27 UTC, brizental commented on glean/src/plugins/encryption.ts
> +    const key = await parseJwk(this.jwk);
This function will either gets the algorith as an argument of infers it from the `alg` property of the JWK. Do our JWKs contain this property? Or are we using the same algortihm always and I should just hard-code it here?

2021-03-04 17:28 UTC, brizental commented on glean/src/plugins/encryption.ts
> +      })
I am setting this header as described in the proposal:

> Since JSON is the supported transport for our data ingestion platform, the encrypted payload will be in the JWE Compact Serialization format and must include a key id (kid) header identifying the public key used for encryption.

I saw in the example keys you sent me that the keys don't have this header though. If this key is required, should I validate that the JWK contains all the expected keys upon instantiation?

2021-03-04 17:30 UTC, brizental commented on glean/src/plugins/encryption.ts
> +        kid: this.jwk.kid,
I am setting this header as described in the proposal:

> Since JSON is the supported transport for our data ingestion platform, the encrypted payload will be in the JWE Compact Serialization format and must include a key id (kid) header identifying the public key used for encryption.

I saw in the example keys you sent me that the keys don't have this header though. If this key is required, should I validate that the JWK contains all the expected keys upon instantiation?

2021-03-04 17:31 UTC, brizental commented on glean/tests/plugins/encryption.spec.ts
> +      "y": "PiEQVUlywi2bEsA3_5D0VFrCHClCyUlLW52ajYs-5uc"
Key copied over from: https://github.com/mozilla/gcp-ingestion/blob/master/ingestion-beam/src/test/resources/pioneer/study-foo.public.json

Generated payload for reference: 
```
'eyJraWQiOiJ0ZXN0IiwiYWxnIjoiRUNESC1FUyIsImVuYyI6IkEyNTZHQ00iLCJ0eXAiOiJKV0UiLCJlcGsiOnsiY3J2IjoiUC0yNTYiLCJrdHkiOiJFQyIsIngiOiJocWRHSTlTcFRhX0FHSkhGdnVwa0xQcTZJUWZvdHZGdHBUYUEzeklyVEpZIiwieSI6IlRqRG9tVUpubU5XRVVZT3J3dV9XRmJLTVc0Q2Z3NldqQmVqbzQwUjVwMm8ifX0..Uka-v-MUTLfJ3o0I.-iYdgmD9pYfGmxxIyms4Ppij7AroTrB2CQZh6SIaV8mysZxa0PyNMAfKi3tU2ts8mGcW4SUz1oLCUt7G-p-JShAqNxj2iK_9myNNsvBiHPlKurik-djRq3T6GYvkmk960o21n0-zoZhpU2JRcnwFs09WMa5lCSsWmbURKGkiG1-Zqymyao4yFKv6ITpYFnce_4XtejtEr9aaiC12FQ0H1r7QCbujx2z1XYLGiNqYyYeb-42jvtZZQnoxG4WjNGpBhGuEkBDHqgC_ALmjx4scZtNtV-mTGxPS3CtQodfYtZHcs2PYRVQRzO8reSrnv40p9O0mcCQWpJLdFWhPTgUyhT3jQ0HgrgG7leRgksIj-L_ftjwGwPBDVKSrtAA5uv93iImDS4rHhHBPXAZyvqmr8fps9DB55yW094-IJrDrVimmVkzeoKTIOwvmc_6DwQDDcC5gAXPXgHknU_RoPYNeBN1kiSTmzNC9VL3LzyOG.AGPJZ5I2SutdWxttwRoyeA'
```

2021-03-04 17:31 UTC, brizental commented on glean/tests/plugins/encryption.spec.ts
> +      "y": "PiEQVUlywi2bEsA3_5D0VFrCHClCyUlLW52ajYs-5uc"
Included `alg` and `kid` of course.

2021-03-04 17:33 UTC, brizental commented on glean/src/plugins/encryption.ts
> +    return { payload: encodedPayload };
Self reminder: This generated the following payload:

```js
 payload: {
  "payload": "eyJraWQiO..."
}
```

Obviously incorrect, will probably need to accept `JSONValue` on the ping maker in order for the plugin to be allowed to return simply a string.

2021-03-04 22:36 UTC, acmiyaguchi commented on glean/src/plugins/encryption.ts
> +    const key = await parseJwk(this.jwk);
This is what an example of a provisioned JWK looks like (https://bugzilla.mozilla.org/show_bug.cgi?id=1693305#c9). 

```
{
    "crv": "P-256",
    "kid": "citp-news-disinfo-two",
    "kty": "EC",
    "x": "Q20tsJdrryWJeuPXTM27wIPb_YbsdYPpkK2N9O6aXwM",
    "y": "1onW1swaCcN1jkmkIwhXpCm55aMP8GRJln5E8WQKLJk"
}
```

I don't think you should have to do anything special in order to parse the key correctly.

2021-03-04 22:36 UTC, acmiyaguchi commented on glean/src/plugins/encryption.ts
> +  constructor(readonly jwk: JWK) {
The properties on the key depends on the type of encryption it's for, which could potentially change in the future. I don't think it necessary to validate the keys outside the encryption function actually succeeding.

2021-03-04 22:36 UTC, acmiyaguchi commented on glean/src/plugins/encryption.ts
> +        kid: this.jwk.kid,
The keys don't need the header, but the encrypted payload does as per the spec: https://tools.ietf.org/html/rfc7516#page-8. Specifically:

```
  In the JWE Compact Serialization, a JWE is represented as the
   concatenation:

      BASE64URL(UTF8(JWE Protected Header)) || '.' ||
      BASE64URL(JWE Encrypted Key) || '.' ||
      BASE64URL(JWE Initialization Vector) || '.' ||
      BASE64URL(JWE Ciphertext) || '.' ||
      BASE64URL(JWE Authentication Tag)
```

The JWE encrypted key is the second element, while the ciphertext is the 3rd element. The library should take care of setting the parameters of encryption for the most part.  Looking at the JWE implemention in Firefox, it looks like the key is in the protected header (https://searchfox.org/mozilla-central/rev/eeb8cf278192d68b3977d0adb4d43f1463439269/services/crypto/modules/jwcrypto.jsm#129-136), so you might be right on this one. The decoder doesn't actually look at the kid atm and chooses a key based purely on the the routing parameters in the submission url.

2021-03-04 22:43 UTC, acmiyaguchi commented on glean/src/plugins/encryption.ts
> +        kid: this.jwk.kid,
I think I mispoke, this is pretty much what my testing code does. https://github.com/mozilla/gcp-ingestion/blob/97619c801279670bddba8ce200799e8b8cda5e60/ingestion-beam/src/test/resources/pioneer.py#L53-L58

The algorithm is "ECDH-ES".

2021-03-09 09:34 UTC, brizental commented
@acmiyaguchi I attended to your review comments in 9b69d77 this commit :)

2021-03-09 10:20 UTC, brizental commented on glean/src/plugins/encryption.ts
> +    return { payload: encodedPayload };
Yeah, this was not the case. I guess I got confused because we have the `payload` property inside the the payload now. I left a bit more comprehensive tests in 92d7825 just to be sure.

2021-03-09 18:20 UTC, acmiyaguchi reviewed
Thanks for addressing my comments :) What do you still have left in this PR?

2021-03-09 18:20 UTC, acmiyaguchi commented on glean/src/plugins/encryption.ts
> +   *            we will look for the `alg` key in the JWK. If neither is present we defaut to "ECDH-ES".
```suggestion
   *            we will look for the `alg` key in the JWK. If neither is present we default to "ECDH-ES".
```

2021-03-10 08:32 UTC, brizental commented
> Thanks for addressing my comments :) What do you still have left in this PR?

If I have your green light on the encryption I'll just request Alessio's review for sanity check on the Glean.js specific parts and merge! Thanks @acmiyaguchi :D

2021-03-10 09:30 UTC, brizental commented on glean/package.json
> +    "test:plugins": "ts-mocha \"tests/plugins/**/*.spec.ts\" --recursive",
Forgot to add this command to the `test` command above.

2021-03-10 13:09 UTC, Dexterp37 requested changes
I left a few comments below. Did you check that "log pings" allow us to ... log pings with this?

2021-03-10 13:09 UTC, Dexterp37 commented on glean/src/plugins/encryption.ts
> +      this.alg = jwk.alg ? jwk.alg : "ECDH-ES";
Why this default? Should we throw instead?

2021-03-10 13:09 UTC, Dexterp37 commented on glean/tests/plugins/encryption.spec.ts
> +  it("collect and store triggers the AfterPingCollection and deals with possible result correctly", async function () {
Can you add a test that provides an `alg`?

2021-03-10 13:09 UTC, Dexterp37 commented on glean/tests/plugins/encryption.spec.ts
> +    await Glean.testInitialize(
Can't both this lines be summarized to `Glean.testResetGlean(...)`? If not, why?

2021-03-10 13:09 UTC, Dexterp37 commented on glean/tests/plugins/encryption.spec.ts
> +      "something something",
Let's try to be more specific here: `gleanjs.unit.test` (in case we see these in the wild)?

2021-03-10 13:09 UTC, Dexterp37 commented on glean/src/plugins/encryption.ts
> +        enc: "A256GCM",
Doesn't this depend on `alg`, too?

2021-03-10 13:13 UTC, brizental commented on glean/tests/plugins/encryption.spec.ts
> +      "something something",
Hah, sure. Should maybe do that with all tests though, I use this app id everywhere.

2021-03-10 13:15 UTC, brizental commented on glean/src/plugins/encryption.ts
> +      this.alg = jwk.alg ? jwk.alg : "ECDH-ES";
https://github.com/mozilla/glean.js/pull/96#discussion_r587880928

2021-03-10 13:16 UTC, brizental commented on glean/src/plugins/encryption.ts
> +        enc: "A256GCM",
🤔 Hm, yeap I think you are right. I'll just go ahead and support `"ECDH-ES"` do avoid confusion. That is the only alg we need at the moment IIUC. We cross the multiple algs bridge when we get there.

2021-03-10 13:20 UTC, Dexterp37 commented on glean/tests/plugins/encryption.spec.ts
> +      "something something",
Yes, that's fine to take it outside of this PR of course. But you might as well just with this file :)

2021-03-10 13:21 UTC, brizental commented
> Did you check that "log pings" allow us to ... log pings with this?

Nope, but I can check that and even go further and a test for it.

2021-03-10 13:22 UTC, Dexterp37 commented
> 
> 
> > Did you check that "log pings" allow us to ... log pings with this?
> 
> Nope, but I can check that and even go further and a test for it.

Yes please :)

2021-03-11 10:12 UTC, brizental commented on glean/src/plugins/encryption.ts
> +        enc: "A256GCM",
Well, I according to the RFC `enc` is related to the content encryption, so _I think_ it is unrelated to `alg`.

2021-03-11 10:21 UTC, Dexterp37 commented on glean/src/plugins/encryption.ts
> +        enc: "A256GCM",
Then the follow-up question is: why this default? :) Can you leave a comment about it in the code?

2021-03-11 11:08 UTC, brizental commented on glean/src/plugins/encryption.ts
> +        enc: "A256GCM",
Ok I tried to understand why, but the truth is I copied from https://github.com/mozilla/gcp-ingestion/blob/97619c801279670bddba8ce200799e8b8cda5e60/ingestion-beam/src/test/resources/pioneer.py#L53-L58. @acmiyaguchi do you know the eact reason for this choice?

During my research I learned that `alg` and `enc` do seem to be related somehow, some pairs will fail. I will go ahead with what I said before and support only what we need for now.

2021-03-11 11:12 UTC, brizental commented on glean/src/plugins/encryption.ts
> +        enc: "A256GCM",
If we are leaving a comment about this we will probably want to leave a comment on the reasoning behind choosing the `ECDH-ES` algorithm, so @acmiyaguchi if you know the reason for that as well, please do tell :)

2021-03-11 13:42 UTC, brizental commented on glean/tests/plugins/encryption.spec.ts
> +      "something something",
https://github.com/mozilla/glean.js/pull/96/commits/0909b35e4b54aeb3ca467d799300b77bfc8153b6

2021-03-11 13:45 UTC, Dexterp37 commented on glean/src/plugins/encryption.ts
>   * with the JWK provided upon initialization.
Let's mention that this offers a specific encryption mechanism in the comment here.

2021-03-11 13:46 UTC, brizental commented on glean/src/plugins/encryption.ts
>   * with the JWK provided upon initialization.
Yeah I left this open on purpose. I will add descriptions and more descriptive doc strings there once Anthony gets back  to us here https://github.com/mozilla/glean.js/pull/96#discussion_r592271956

2021-03-11 18:34 UTC, acmiyaguchi commented on glean/src/plugins/encryption.ts
> +        enc: "A256GCM",
ECDH-ES is the only algorithm supported by Firefox's hand-rolled JWE implementation, and so :rhelmer ended up setting most of the parameters that we use. https://searchfox.org/mozilla-central/rev/eeb8cf278192d68b3977d0adb4d43f1463439269/services/crypto/modules/jwcrypto.jsm#58-74

2021-03-12 11:55 UTC, brizental commented on glean/src/core/events/index.ts
> +  // The plugin to be triggered eveytime this even occurs.
Since we are here...

```suggestion
  // The plugin to be triggered eveytime this event occurs.
```

2021-03-12 11:55 UTC, brizental commented on glean/src/core/pings/maker.ts
> +      "Ping will not be submitted. See more logs below.\n\n",
```suggestion
      "Ping will not be submitted. See more logs below.\n",
```

Why did I add two line breaks...

2021-03-12 11:55 UTC, brizental commented on glean/src/plugins/encryption.ts
> +    const key = await parseJwk(this.jwk, JWE_ALGORITHM);
Note: This will throw an error in case the provided `jwk` is incorrect for the default algorithm.

2021-03-12 11:55 UTC, brizental commented on glean/src/core/pings/maker.ts
> +  try {
I considered just adding the `try / catch` block inside the `trigger` method, but I think this is something to decide in an event by event basis. Here I thought it would be best to not send a ping if a plugin errors, for the encryption plugin, sending the unencrypted payload would probably be a terrible decision.

2021-03-12 12:12 UTC, Dexterp37 approved these changes

2021-03-12 14:17 UTC, merged