Add labeled metric types
mozilla/glean.js pull request #97
Opened 2021-03-09 11:18 UTC by Dexterp37

This introduces the labelled metric types for string, boolean and counter types. The implementation closely follows what's in the Glean SDK, with no major deviation.

Note that this required adding a couple more functions to the database.

TODO:

- [x] Port test coverage.
- [x] Enable dynamic labels.
- [ ] Add documentation.
- [x] Enforce label limits.
- [x] Enable different labelled metric types (instead of hardcoding)

2021-03-09 11:19 UTC, Dexterp37 commented on glean/src/core/metrics/types/labeled.ts
> +export class LabeledMetric extends Metric<JSONValue, JSONValue> {
Note for @brizental as you can see, this is not validating anything at all. That's because the internal representation is being handled by the sub-metric type. So we just copy stuff over with this.

2021-03-09 11:29 UTC, brizental commented on glean/src/core/metrics/types/labeled.ts
> +  payload(): JSONValue {
Random thought: we should provide a default for this method that does this. We have other metrics that just return `this._inner`, I think most of them do this even. Anyways, no need to do that in this PR.

2021-03-09 13:47 UTC, brizental commented on glean/src/core/metrics/types/labeled.ts
> +  // Define an index signature (https://www.typescriptlang.org/docs/handbook/interfaces.html#indexable-types)
This link in deprecated. I think we can leave this comment out. This is a normal Typescript pattern and I have used in other parts of the code anyways :D (https://github.com/mozilla/glean.js/blob/main/glean/src/core/events/index.ts#L69). To make things clearer, maybe instead of `[key: string]` we use `[label: string]`?

2021-03-09 13:47 UTC, brizental commented on glean/src/core/metrics/utils.ts
> +  "labeled_counter": LabeledMetric,
Shouldn't this have `LabeledMetric<CounterMetricType>`?

2021-03-09 13:47 UTC, brizental commented on glean/src/core/metrics/types/labeled.ts
> +export class LabeledMetric extends Metric<JSONValue, JSONValue> {
Ok, after reading the code a bit more I understand that you are saving these metrics as if they were not labeled. That is counterintuitive for me, why can't we save them already as labeled metrics?

2021-03-09 13:47 UTC, brizental commented on glean/src/core/metrics/types/labeled.ts
> +  // Define an index signature (https://www.typescriptlang.org/docs/handbook/interfaces.html#indexable-types)
Or maybe `labels: Record<string, T>`?

2021-03-09 13:47 UTC, brizental commented on glean/src/core/metrics/types/labeled.ts
> +    return new Proxy(this, {
Bear with me here as I have never used `Proxy` before, but after reading about it, I don't understand why we need it. Why can't `get` be a method of this class that returns `T`? We could do sorta what glean-core does and save a reference to the desired submetric constructor to this class. Like so:

```ts
constructor<A>(meta: CommonMetricData, submetric: new(...args: A) -> T, labels?: string[]) {
    this.submetric = submetric
}
```

Or we could even do _exactly_ like glean-core and provide an instance of the submetric and clone when necessary. There is apparently a crazy way to clone instances of classes in JS (https://stackoverflow.com/questions/41474986/how-to-clone-a-javascript-es6-class-instance), but we can also force metrics to define  `clone` method by making it an abstract method on the `MetricType` class.

I think something similar to this will be necessary anyways to do [this](https://github.com/mozilla/glean.js/pull/97/files#diff-25b869315615f9e430ce2ebcb8e11349dc38fdbab44706dac5d0fbaf7cb2486dR79).

2021-03-09 13:47 UTC, brizental commented on glean/src/core/metrics/types/labeled.ts
> +export class LabeledMetric extends Metric<JSONValue, JSONValue> {
Since we are currently saving metrics as their submetric type, this class is probably never used.

2021-03-10 09:39 UTC, Dexterp37 commented on glean/src/core/metrics/types/labeled.ts
> +  // Define an index signature (https://www.typescriptlang.org/docs/handbook/interfaces.html#indexable-types)
> 
> 
> Or maybe `labels: Record<string, T>`?

This would break compilation :)

2021-03-12 16:08 UTC, brizental commented on glean/src/core/metrics/database.ts
> +   * @returns `true` if the metric was found (regardless of the validity of the
Why does the validity of the stored data not matter?

2021-03-12 16:12 UTC, Dexterp37 commented on glean/src/core/metrics/database.ts
> +   * @returns `true` if the metric was found (regardless of the validity of the
Because this is used to count things to enforce the label limit. And in glean-core we enforce the limit regardless of the content.

2021-03-12 17:04 UTC, brizental requested changes
It is Friday EOD and I probably missing something in this review. Please consider this a "first pass" and I'll take a closer look on Monday 🧇

2021-03-12 17:05 UTC, brizental commented on glean/src/core/metrics/index.ts
> +export class PassthroughMetric extends Metric<JSONValue, JSONValue> {
Reminder to self: I don't understand why we need the `PassthorughMetric` at all.

2021-03-15 09:56 UTC, brizental commented on glean/src/core/metrics/index.ts
> +export class PassthroughMetric extends Metric<JSONValue, JSONValue> {
Yeah I get it now. I was wrong when I assumed Labeled metrics did not need a `Metric` declaration. Even though we don't care about their internal representation, they need a `Metric` representation for generating the ping payload. I am sorry for the back and forth here, but I would prefer if instead of `PassthrougMetric` you made this `LabeledMetric`.

2021-03-15 09:57 UTC, Dexterp37 commented on glean/src/core/metrics/index.ts
> +export class PassthroughMetric extends Metric<JSONValue, JSONValue> {
Mh, too bad :) Now, I could do that and move it back to the labeled metric implementation file. Unfortunately doing so will trigger a circular dependency that breaks the TS build :(

2021-03-15 09:58 UTC, Dexterp37 commented on glean/src/core/metrics/types/labeled.ts
> +const LABEL_REGEX = /^[a-z_][a-z0-9_-]{0,29}(\.[a-z_][a-z0-9_-]{0,29})*$/;
This is the regular expression I took from the comment, so I assume this covers the cases we care about. The label length is checked for in the code outside of this regex (see the MAX_LABEL_LENGTH const)

2021-03-15 10:02 UTC, Dexterp37 commented on glean/src/core/metrics/database.ts
> +   * @returns `true` if the metric was found (regardless of the validity of the
> 
> 
> Hm, but this is counterintuitive for me, because a metric will be deleted in case it is invalid, so it's like it never existed. Also https://github.com/mozilla/glean/blob/main/glean-core/src/database/mod.rs#L414

From looking at the code the comment seems to refer to the fact that if reading fails, the count will be 0. We don't validate the data AFAICT! That deep we really have no proper way to know what to expect, unless we leak the type to the database, which is undesireable, IMHO, from an architectural POV

2021-03-15 10:06 UTC, brizental commented on glean/src/core/metrics/index.ts
> +export class PassthroughMetric extends Metric<JSONValue, JSONValue> {
Argh, come on TS.

2021-03-15 10:12 UTC, brizental commented on glean/src/core/metrics/database.ts
> +   * @returns `true` if the metric was found (regardless of the validity of the
Still counter intuitive for me for the reasons I said above. BUT, you are right that glean-core doesn't validate. I confused reading with deserializing, so... Fine by me.

2021-03-15 11:07 UTC, Dexterp37 commented on glean/src/core/metrics/types/labeled.ts
> +  private static createFromDynamicLabel<T extends new (...args: any) => InstanceType<T>>(
The TS compiler disagrees :-) I guess that's because it's a static function

2021-03-15 12:39 UTC, Dexterp37 commented on glean/src/core/metrics/database.ts
> +   * @returns `true` if the metric was found (regardless of the validity of the
> 
> 
> That would be a problem on the counting function below... I know it's annyoing...

What do you mean?

2021-03-15 12:41 UTC, brizental commented on glean/src/core/metrics/database.ts
> +   * @returns `true` if the metric was found (regardless of the validity of the
In case you were validating here it would make sense to validate below. Not the case in both functions from the previous discussion.

2021-03-15 12:42 UTC, brizental commented on glean/src/core/metrics/types/labeled.ts
> +  private static createFromDynamicLabel<T extends new (...args: any) => InstanceType<T>>(
TIL! Indeed it's because it is static.

2021-03-15 13:03 UTC, brizental commented on glean/src/core/metrics/index.ts
> +export class PassthroughMetric extends Metric<JSONValue, JSONValue> {
So, if you move [this line](https://github.com/mozilla/glean.js/pull/97/files/a70deda5c5666961b03b39ab1c894bc1d6070404#diff-92a923012f502164643de6a0da030333f187db543246ceddeb72afc3b6820d5cR7) to somewhere _after_ you define the `Metric` abstract class the error goes away.

2021-03-15 13:27 UTC, brizental requested changes

2021-03-15 13:27 UTC, brizental commented on glean/src/core/metrics/types/labeled.ts
> +  ): T {
```suggestion
  ): InstanceType<T> {
```

2021-03-15 13:27 UTC, brizental commented on glean/src/core/metrics/types/labeled.ts
> +  ): T {
```suggestion
  ): InstanceType<T> {
```

2021-03-15 13:27 UTC, brizental commented on glean/src/core/metrics/types/labeled.ts
> +      get: (_target: LabeledMetricType<T>, label: string): any => {
```suggestion
      get: (_target: LabeledMetricType<T>, label: string): T => {
```

We need to be mindful of returning `any` here specially because it is the user facing API.

2021-03-15 13:27 UTC, brizental commented on glean/src/core/metrics/types/labeled.ts
> +  static async getValidDynamicLabel(metric: MetricType): Promise<string> {
nit: Missing documentation.

2021-03-15 13:27 UTC, brizental commented on glean/tests/core/metrics/labeled.spec.ts
> +    await Glean.testResetGlean("gleanjs.unit.test");
https://github.com/mozilla/glean.js/blob/main/glean/tests/core/glean.spec.ts#L31-L34 Please create the test id the same as in other tests.

2021-03-15 16:08 UTC, brizental approved these changes
Good to go, assuming the `PassthroughMetric` comments are addressed.

2021-03-15 16:08 UTC, brizental commented on CHANGELOG.md
>  * [#101](https://github.com/mozilla/glean.js/pull/101): BUGFIX: Only validate Debug View Tag and Source Tags when they are present.
Why do we have two entries here... Whathever, can be fixed when we make the next release.

2021-03-15 18:53 UTC, Dexterp37 commented on glean/src/core/metrics/index.ts
> +export class PassthroughMetric extends Metric<JSONValue, JSONValue> {
I renamed this as requested and added a better comment.

2021-03-15 18:57 UTC, merged